/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as common from './common';

export type Int64 = string | number;

export enum ValueType {
  String = 1,
}

export interface Answer {
  content?: string;
}

export interface ChatWithLLMReq {
  /** 文本內容 */
  text?: string;
  /** 時長 */
  duration?: number;
  /** 音頻 ID */
  audio_id?: string;
  /** 對話 ID */
  conversation_id?: string;
  /** 消息 ID, 若爲空則創建新消息 */
  message_id?: Int64;
  base?: base.Base;
}

export interface ChatWithLLMResp {
  content?: string;
  is_finished?: boolean;
  message_id?: string;
  role?: common.MessageRole;
  conversation_id?: string;
  base_resp?: base.BaseResp;
}

export interface CheckTextAccuracyReq {
  text: string;
  original_text: string;
  base?: base.Base;
}

export interface CheckTextAccuracyResp {
  /** 準確度合格 */
  accuracy_qualified?: boolean;
  base_resp?: base.BaseResp;
}

export interface CheckUserAudioReq {
  body: Blob;
  'Content-Type': string;
  /** 3-5僅爲聲明，不使用，從body的Form中解析 */
  audio_body?: string;
  original_content?: string;
  need_check_accuracy?: boolean;
  base?: base.Base;
}

export interface CheckUserAudioResp {
  /** 音頻id */
  audio_id?: Int64;
  /** 音頻文本內容 */
  text?: string;
  /** 準確度合格 */
  accuracy_qualified?: boolean;
  base_resp?: base.BaseResp;
}

export interface CloseConversationReq {
  conversation_id: string;
  base?: base.Base;
}

export interface CloseConversationResp {
  conversation?: common.Conversation;
  base_resp?: base.BaseResp;
}

export interface CompleteMeetingReq {
  /** 學習記錄id */
  learning_id: Int64;
  base?: base.Base;
}

export interface CompleteMeetingResp {
  base_resp?: base.BaseResp;
}

export interface ContinueMeetingReq {
  /** 學習記錄id */
  learning_id: Int64;
  /** 題目id */
  exercise_id: Int64;
  /** 題號 */
  exercise_seq: Int64;
  /** 用戶答案 */
  user_answer?: string;
  /** 用戶音頻id */
  user_audio_id?: Int64;
  /** 原句 */
  original_content: string;
  base?: base.Base;
}

export interface ContinueMeetingResp {
  base_resp?: base.BaseResp;
}

export interface CreateConversationReportReq {
  conversation_id: string;
  base?: base.Base;
}

export interface CreateConversationReportResp {
  report?: common.ConversationReport;
  base_resp?: base.BaseResp;
}

/** 題目 */
export interface Exercise {
  /** 題目id */
  exercise_id?: Int64;
  /** 角色id */
  role_id?: Int64;
  /** 題號 */
  exercise_seq?: number;
  /** 題型 */
  exercise_type?: common.EnglishExerciseType;
  /** 原句 */
  original_content?: string;
  /** 挖空的題 */
  mask_content?: string;
  /** 選項 */
  options?: Array<ExerciseOption>;
  /** 正確答案 */
  correct_answer?: Array<Answer>;
  /** 題目音頻 */
  exercise_audio?: common.AudioDetail;
  /** 問題翻譯 */
  answer_translate?: string;
  /** 答案解析 */
  answer_analysis?: string;
  created_at?: Int64;
  updated_at?: Int64;
}

/** 題目選項 */
export interface ExerciseOption {
  content?: string;
}

export interface GenerateRoleMessageReq {
  /** 會話id */
  conversation_id: Int64;
  /** 用戶回答 */
  user_response?: string;
  base?: base.Base;
}

export interface GenerateRoleMessageResp {
  chunk?: common.StreamChunk;
  message_id?: Int64;
  base_resp?: base.BaseResp;
}

export interface GetAISuggestionReq {
  /** 會話id */
  conversation_id: Int64;
  base?: base.Base;
}

export interface GetAISuggestionResp {
  output?: common.AISuggestionOutput;
  base_resp?: base.BaseResp;
}

export interface GetConversationDetailReq {
  id: Int64;
  base?: base.Base;
}

export interface GetConversationDetailResp {
  conversation?: common.Conversation;
  base_resp?: base.BaseResp;
}

export interface GetExerciseInfoReq {
  exercise_id: string;
  base?: base.Base;
}

export interface GetExerciseInfoResp {
  exercise_info?: common.Exercise;
  phrase_list?: Array<common.Phrase>;
  task_list?: Array<common.ExerciseTask>;
  base_resp?: base.BaseResp;
}

export interface GetJSSDKConfigReq {
  url: string;
  base?: base.Base;
}

export interface GetJSSDKConfigResp {
  config?: common.JSSDKConfig;
  base_resp?: base.BaseResp;
}

export interface GetLastConversationReq {
  exercise_id: Int64;
  base?: base.Base;
}

export interface GetLastConversationResp {
  conversation?: common.Conversation;
  base_resp?: base.BaseResp;
}

export interface GetLearningPathReq {
  base?: base.Base;
}

export interface GetLearningPathResp {
  phase_list?: Array<common.Phase>;
  is_new_user?: boolean;
  base_resp?: base.BaseResp;
}

export interface GetMeetingAIChatDetailReq {
  /** 學習記錄id */
  learning_id: Int64;
  base?: base.Base;
}

export interface GetMeetingAIChatDetailResp {
  meeting_detail?: MeetingDetail;
  meeting_role_list?: Array<MeetingRole>;
  meeting_ai_chat_message_list?: Array<MeetingAIChatMessage>;
  conversation_id?: Int64;
  base_resp?: base.BaseResp;
}

export interface GetMeetingCategoryReq {
  study_module_type: common.StudyModuleType;
  base?: base.Base;
}

export interface GetMeetingCategoryResp {
  category_list?: Array<MeetingCategory>;
  base_resp?: base.BaseResp;
}

export interface GetMeetingListReq {
  meeting_type: common.MeetingType;
  category_id?: Int64;
  /** 是否只返回未學習的 */
  only_not_learn?: boolean;
  base?: base.Base;
}

export interface GetMeetingListResp {
  meeting_list?: Array<MeetingListItem>;
  base_resp?: base.BaseResp;
}

export interface GetMeetingSlideReq {
  base?: base.Base;
}

export interface GetMeetingSlideResp {
  meeting_slide_list?: Array<MeetingListItem>;
  base_resp?: base.BaseResp;
}

export interface GetMessageTipReq {
  message_id?: string;
  base?: base.Base;
}

export interface GetMessageTipResp {
  tip?: string;
  base_resp?: base.BaseResp;
}

export interface GetOralScoreReq {
  user_response: string;
  base?: base.Base;
}

export interface GetOralScoreResp {
  oral_score?: common.OralScoreType;
  base_resp?: base.BaseResp;
}

export interface GetTodayDurationReq {
  module_type?: common.StudyModuleType;
  base?: base.Base;
}

export interface GetTodayDurationResp {
  duration?: number;
  base_resp?: base.BaseResp;
}

export interface GetTotalDurationReq {
  module_type?: common.StudyModuleType;
  base?: base.Base;
}

export interface GetTotalDurationResp {
  duration?: number;
  base_resp?: base.BaseResp;
}

export interface GetTTSTokenReq {
  base?: base.Base;
}

export interface GetTTSTokenResp {
  data: common.VoiceToken;
  base_resp?: base.BaseResp;
}

export interface GetUserLevelReq {
  base?: base.Base;
}

export interface GetUserLevelResp {
  data?: common.UserLevelData;
  base_resp?: base.BaseResp;
}

export interface LeaveAiChatRoomReq {
  /** 會話id */
  conversation_id: Int64;
  base?: base.Base;
}

export interface LeaveAiChatRoomResp {
  base_resp?: base.BaseResp;
}

export interface ListConversationRecordReq {
  exercise_id?: Int64;
  status?: common.ConversationStatus;
  page?: number;
  page_size?: number;
  base?: base.Base;
}

export interface ListConversationRecordResp {
  conversations?: Array<common.Conversation>;
  total?: number;
  page?: number;
  page_size?: number;
  base_resp?: base.BaseResp;
}

export interface ListPhaseReq {
  base?: base.Base;
}

export interface ListPhaseResp {
  phase_list?: Array<common.Phase>;
  base_resp?: base.BaseResp;
}

export interface MeetingAIChatMessage {
  message_id?: Int64;
  role_id?: Int64;
  role?: common.ChatRole;
  content?: string;
  msg_index?: Int64;
  created_at?: Int64;
  updated_at?: Int64;
}

export interface MeetingCategory {
  category_id?: Int64;
  category_name?: string;
  category_type?: common.MeetingCategoryType;
  icon_url?: string;
  sub_category_list?: Array<MeetingCategory>;
}

export interface MeetingDetail {
  meeting_type?: common.MeetingType;
  title?: string;
  desc?: string;
}

export interface MeetingListItem {
  meeting_id?: Int64;
  meeting_type: common.MeetingType;
  title?: string;
  desc?: string;
  icon_url?: string;
  category_icon_url?: string;
  exercise_count?: number;
  estimate_duration?: Int64;
  learning_status?: common.MeetingLearningStatus;
  learning_id?: Int64;
  /** 是否有進行過ai_chat */
  has_ai_chat?: boolean;
  max_oral_score?: Int64;
  updated_at?: Int64;
}

export interface MeetingRole {
  role_id?: Int64;
  name?: string;
  icon_url?: string;
  speaker_id?: string;
}

export interface MessageEvalReq {
  message_id?: string;
  base?: base.Base;
}

export interface MessageEvalResp {
  data?: common.MessageEvalData;
  base_resp?: base.BaseResp;
}

export interface ResumeConversationReq {
  conversation_id: string;
  base?: base.Base;
}

export interface ResumeConversationResp {
  conversation?: common.Conversation;
  base_resp?: base.BaseResp;
}

export interface SelectPhaseReq {
  /** 階段 id */
  phase_id: string;
  base?: base.Base;
}

export interface SelectPhaseResp {
  selected_phase?: common.Phase;
  base_resp?: base.BaseResp;
}

export interface StartChatReq {
  /** 練習 id */
  exercise_id: string;
  /** conversation id */
  conversation_id?: Int64;
  base?: base.Base;
}

export interface StartChatResp {
  content?: string;
  is_finished?: boolean;
  message_id?: string;
  role?: common.MessageRole;
  conversation_id?: string;
  base_resp?: base.BaseResp;
}

export interface StartMeetingReq {
  /** 會議素材id */
  meeting_id: Int64;
  base?: base.Base;
}

export interface StartMeetingResp {
  /** 學習記錄id */
  learning_id?: Int64;
  meeting_detail?: MeetingDetail;
  meeting_role_list?: Array<MeetingRole>;
  meeting_exercise_list?: Array<Exercise>;
  conversation_id?: Int64;
  base_resp?: base.BaseResp;
}

export interface TranslateMessageReq {
  message_id: string;
  base?: base.Base;
}

export interface TranslateMessageResp {
  translation?: string;
  base_resp?: base.BaseResp;
}

export interface TranslateMessageV2Req {
  content: string;
  history_message_list?: Array<common.HistoryMessage>;
  base?: base.Base;
}

export interface TranslateMessageV2Resp {
  translation?: string;
  base_resp?: base.BaseResp;
}

export interface UnlockTopicReq {
  topic_id: string;
  base?: base.Base;
}

export interface UnlockTopicResp {
  unlocked_topic?: common.Topic;
  base_resp?: base.BaseResp;
}

export interface UpdateStudyDurationReq {
  duration: number;
  module_type?: common.StudyModuleType;
  base?: base.Base;
}

export interface UpdateStudyDurationResp {
  success?: boolean;
  base_resp?: base.BaseResp;
}
/* eslint-enable */
