/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** 組件元信息 */
export interface ComponentMetaInfo {
  id?: string;
  /** 組件名 */
  name?: string;
  /** 組件標題 */
  title?: string;
  /** 組件描述 */
  description?: string;
  /** 組件icon */
  iconUri?: string;
  /** 組件url */
  iconUrl?: string;
}

export interface Package {
  id?: string;
  metaInfo?: PackageMetaInfo;
  /** 組件包名 */
  pkgName?: string;
  /** 組件包版本 */
  version?: string;
  /** 組件包創建者uid */
  uid?: string;
  /** 組件包可訪問空間id */
  spaceIds?: Array<string>;
  /** 組件包更新時間 */
  updateTime?: string;
  /** 是否最新 */
  isLatest?: boolean;
  /** 組件包渠道 */
  channel?: number;
  /** 組件包在registry中的id */
  registryComponentId?: string;
  /** 產物cdn地址 */
  cdnHost?: string;
}

/** 組件包元信息 */
export interface PackageMetaInfo {
  /** 組件包名 */
  name?: string;
  /** 組件包標題 */
  title?: string;
  /** 組件包描述 */
  description?: string;
  /** 組件包包含的組件 */
  contains?: Array<ComponentMetaInfo>;
  /** 組件包icon */
  iconUri?: string;
  /** 組件包url */
  iconUrl?: string;
}
/* eslint-enable */
