/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum AgentType {
  Start_Agent = 0,
  LLM_Agent = 1,
  Task_Agent = 2,
  Global_Agent = 3,
  Bot_Agent = 4,
}

/** 版本兼容：0-舊版本 1-可回退的新版本 2-不可回退的新版本 3-可回退的新版本(不再提示) */
export enum AgentVersionCompat {
  OldVersion = 0,
  MiddleVersion = 1,
  NewVersion = 2,
  MiddleVersionNotPrompt = 3,
}

/** AnswerActions */
export enum AnswerActionsMode {
  Default = 1,
  Customize = 2,
}

export enum AnswerActionTriggerType {
  /** 平臺預設Trigger action */
  Direct = 1,
  /** 點擊Action 顯示自定義的H5頁面 */
  WebView = 2,
  /** 點擊Action 發送自定義的用戶消息 */
  SendMessage = 3,
}

export enum BacktrackMode {
  Current = 1,
  Previous = 2,
  Start = 3,
  MostSuitable = 4,
}

export enum BotMode {
  SingleMode = 0,
  MultiMode = 1,
  WorkflowMode = 2,
}

export enum BotSpecies {
  /** bot種類
從flow創建 */
  Default = 0,
  /** 從coze創建 */
  Function = 1,
}

export enum BotStatus {
  Deleted = 0,
  Using = 1,
  Banned = 2,
}

export enum BotTableRWMode {
  LimitedReadWrite = 1,
  ReadOnly = 2,
  UnlimitedReadWrite = 3,
  RWModeMax = 4,
}

export enum BusinessType {
  Default = 0,
  DouyinAvatar = 1,
}

export enum CacheType {
  /** 緩存關閉 */
  CacheClosed = 0,
  /** 前綴緩存 */
  PrefixCache = 1,
}

/** 上下文允許傳輸的類型 */
export enum ContextMode {
  Chat = 0,
  FunctionCall_1 = 1,
  FunctionCall_2 = 2,
  FunctionCall_3 = 3,
}

export enum DefaultUserInputType {
  /** 沒設置 */
  NotSet = 0,
  /** 文字 */
  Text = 1,
  /** 按住語音 */
  Voice = 2,
  /** 語音通話 */
  Call = 3,
  /** 視頻通話 */
  VideoCall = 4,
}

export enum DisablePromptCalling {
  Off = 0,
  On = 1,
}

export enum FieldItemType {
  /** 文本 String */
  Text = 1,
  /** 數字 Integer */
  Number = 2,
  /** 時間 Time */
  Date = 3,
  /** float Number */
  Float = 4,
  /** bool Boolean */
  Boolean = 5,
}

export enum FileboxInfoMode {
  Off = 0,
  On = 1,
}

export enum IndependentRecognitionModelType {
  /** 小模型 */
  SLM = 0,
  /** 大模型 */
  LLM = 1,
}

export enum IndependentTiming {
  /** 判斷用戶輸入（前置） */
  Pre = 1,
  /** 判斷節點輸出（後置） */
  Post = 2,
  /** 前置模式和後置模式支持同時選擇 */
  PreAndPost = 3,
}

export enum KnowledgeNoRecallReplyMode {
  Default = 0,
  CustomizePrompt = 1,
}

export enum KnowledgeShowSourceMode {
  ReplyBottom = 0,
  CardList = 1,
}

export enum KnowledgeType {
  Coze = 0,
  Volcano = 1,
}

export enum KnowledgeTypeMode {
  Coze = 0,
  Volcano = 1,
}

export enum MessageFeedbackDetailType {
  UnlikeDefault = 0,
  /** 有害信息 */
  UnlikeHarmful = 1,
  /** 信息有誤 */
  UnlikeIncorrect = 2,
  /** 未遵循指令 */
  UnlikeNotFollowInstructions = 3,
  /** 其他 */
  UnlikeOthers = 4,
}

export enum MessageFeedbackType {
  Default = 0,
  Like = 1,
  Unlike = 2,
}

export enum ModelFuncConfigStatus {
  FullSupport = 0,
  PoorSupport = 1,
  NotSupport = 2,
}

export enum ModelFuncConfigType {
  Plugin = 1,
  Workflow = 2,
  ImageFlow = 3,
  Trigger = 4,
  KnowledgeText = 5,
  KnowledgeTable = 6,
  KnowledgeAutoCall = 7,
  KnowledgeOnDemandCall = 8,
  Variable = 9,
  Database = 10,
  LongTermMemory = 11,
  FileBox = 12,
  Onboarding = 13,
  Suggestion = 14,
  ShortcutCommand = 15,
  BackGroundImage = 16,
  TTS = 17,
  MultiAgentRecognize = 18,
  KnowledgePhoto = 19,
  HookInfo = 20,
  KnowledgeValcanoUnstructured = 21,
  KnowledgeValcanoStructured = 22,
  Model = 23,
}

export enum ModelResponseFormat {
  Text = 0,
  Markdown = 1,
  JSON = 2,
}

export enum ModelStyle {
  Custom = 0,
  Creative = 1,
  Balance = 2,
  Precise = 3,
}

export enum MultiAgentConnectorType {
  Curve = 0,
  Straight = 1,
}

export enum MultiAgentSessionType {
  Flow = 1,
  Host = 2,
}

/** onboarding內容生成模式 */
export enum OnboardingMode {
  /** 不需要 */
  NO_NEED = 1,
  /** 人工指定內容（多語言支持由LLM兜底） */
  USE_MANUAL = 2,
  /** 由LLM生成 */
  USE_LLM = 3,
}

export enum PromptMode {
  Standard = 0,
  /** 前綴提示詞 */
  PrefixPrompt = 1,
}

export enum RecognitionMode {
  FunctionCall = 1,
  Independent = 2,
}

export enum ReferenceInfoStatus {
  /** 1:有可用更新 */
  HasUpdates = 1,
  /** 2:被刪除 */
  IsDelete = 2,
}

/** struct ContentAttachment {
    1: required string FileID (api.body = "file_id")
}
 struct MetaContent{
     1: required string Type (agw.key="type"),
     2: optional string Text ( agw.key="text"),
     3: optional string FileID (agw.key="file_id"),
     4: optional string FileURL (agw.key="file_url"),
     5: optional string Card (agw.key="card"),
 }
 struct EnterMessage  {
     1: required string Role (agw.key = "role")
     2: string Content(agw.key = "content")     // 內容
     3: map<string,string> MetaData(agw.key = "meta_data")
     4: string ContentType(agw.key = "content_type")//text/card/object_string
     5: string Type(agw.key = "type")
 }
 struct OpenMessageApi {
     1: string Id(agw.key = "id")             // 主鍵ID
     2: string BotId(agw.key = "bot_id")        // bot id //已TODO 所有的i64加註解str,入參和出參都要
     3: string Role(agw.key = "role")
     4: string Content(agw.key = "content")          // 內容
     5: string ConversationId(agw.key = "conversation_id")   // conversation id
     6: map<string,string> MetaData(agw.key = "meta_data")
     7: string CreatedAt(agw.key = "created_at")      // 創建時間
     8: string UpdatedAt(agw.key = "updated_at")      // 更新時間 //已TODO 時間改成int
     9: string ChatId(agw.key = "chat_id")
     10: string ContentType(agw.key = "content_type")
     11: string Type(agw.key = "type")
 } */
export enum ReferenceUpdateType {
  ManualUpdate = 1,
  AutoUpdate = 2,
}

export enum Scene {
  Default = 0,
  Explore = 1,
  BotStore = 2,
  CozeHome = 3,
  Playground = 4,
  /** 評測平臺 */
  Evaluation = 5,
  AgentAPP = 6,
  /** prompt優化 */
  PromptOptimize = 7,
  /** createbot的nl2bot功能 */
  GenerateAgentInfo = 8,
}

export enum SearchStrategy {
  /** 語義搜索 */
  SemanticSearch = 0,
  /** 混合搜索 */
  HybirdSearch = 1,
  /** 全文搜索 */
  FullTextSearch = 20,
}

export enum SocietyVisibility {
  /** 對所有人可見 */
  Public = 1,
  /** 僅對host可見 */
  Anonymous = 2,
  /** 自定義 */
  Custom = 3,
}

export enum SuggestedQuestionsShowMode {
  Random = 0,
  All = 1,
}

export enum SuggestReplyMode {
  System = 0,
  Custom = 1,
  Disable = 2,
  /** agent專用，複用源Bot配置 */
  OriBot = 3,
}

export enum TimeCapsuleMode {
  /** 關 */
  Off = 0,
  /** 開 */
  On = 1,
}

export enum WorkflowMode {
  Workflow = 0,
  Imageflow = 1,
  SceneFlow = 2,
  ChatFlow = 3,
  All = 100,
}

export interface ActionIcon {
  /** 自定義的按鈕 type 不用傳 */
  type?: string;
  /** 默認狀態 */
  default_url?: string;
  /** 按下按鈕的狀態 */
  active_url?: string;
  /** 默認狀態 */
  default_uri?: string;
  /** 按下按鈕的狀態 */
  active_uri?: string;
}

export interface Agent {
  agent_id?: string;
  agent_name?: string;
  /** prompt 信息 */
  prompt_info?: PromptInfo;
  /** plugin列表 */
  plugin_info_list?: Array<PluginInfo>;
  /** 數據集 */
  knowledge?: Knowledge;
  /** Workflow 列表 */
  workflow_info_list?: Array<WorkflowInfo>;
  /** 模型配置 */
  model_info?: ModelInfo;
  /** 意圖信息 */
  intents?: Array<Intent>;
  agent_type?: AgentType;
  /** 是否是rootagent */
  root_agent?: boolean;
  reference_id?: string;
  first_version?: string;
  last_version?: string;
  agent_position?: AgentPosition;
  icon_uri?: string;
  jump_config?: JumpConfig;
  suggest_reply_info?: SuggestReplyInfo;
  description?: string;
  /** multi_agent版本兼容字段 */
  version_compat?: AgentVersionCompat;
  hook_info?: HookInfo;
  /** 子bot當前版本 */
  current_version?: string;
  /** 1:有可用更新 2:被刪除 */
  reference_info_status?: ReferenceInfoStatus;
  /** 子bot更新類型 */
  update_type?: ReferenceUpdateType;
}

export interface AgentForUpdate {
  /** agw字段名做了特殊映射 注意 */
  id?: string;
  /** agw字段名做了特殊映射 注意 */
  name?: string;
  /** prompt 信息 */
  prompt_info?: PromptInfo;
  /** plugin列表 */
  plugin_info_list?: Array<PluginInfo>;
  /** 數據集 */
  knowledge?: Knowledge;
  /** Workflow 列表 */
  workflow_info_list?: Array<WorkflowInfo>;
  /** 模型配置 */
  model_info?: ModelInfo;
  /** 意圖信息 */
  intents?: Array<Intent>;
  agent_type?: AgentType;
  /** 是否是rootagent */
  root_agent?: boolean;
  reference_id?: string;
  first_version?: string;
  last_version?: string;
  agent_position?: AgentPosition;
  icon_uri?: string;
  jump_config?: JumpConfig;
  suggest_reply_info?: SuggestReplyInfo;
  description?: string;
  /** multi_agent版本兼容字段 */
  version_compat?: AgentVersionCompat;
  hook_info?: HookInfo;
}

export interface AgentPosition {
  x?: number;
  y?: number;
}

export interface AgentVersionCompatInfo {
  version_compat?: AgentVersionCompat;
  version?: string;
}

export interface AnswerActionConfig {
  /** 預製的只需要傳key */
  key?: string;
  /** 默認 */
  name?: string;
  /** 下發uri */
  icon?: ActionIcon;
  /** 存儲用戶i18的name */
  name_i18n?: Record<string, string>;
  /** Direct 沒有值； WebView 包含 webview_url和 webview_callback_psm兩個key；SendMessage 包含send_message_prompt */
  trigger_rule?: AnswerActionTriggerRule;
  /** 位置 */
  position?: number;
}

export interface AnswerActions {
  answer_actions_mode?: AnswerActionsMode;
  answer_action_configs?: Array<AnswerActionConfig>;
}

export interface AnswerActionTriggerRule {
  type?: AnswerActionTriggerType;
  need_preloading?: boolean;
  /** 根據 AnswerActionTriggerType決定 */
  trigger_data?: Record<string, string>;
}

export interface BackgroundImageDetail {
  /** 原始圖片 */
  origin_image_uri?: string;
  origin_image_url?: string;
  /** 實際使用圖片 */
  image_uri?: string;
  image_url?: string;
  theme_color?: string;
  /** 漸變位置 */
  gradient_position?: GradientPosition;
  /** 裁剪畫布位置 */
  canvas_position?: CanvasPosition;
}

export interface BackgroundImageInfo {
  /** web端背景圖 */
  web_background_image?: BackgroundImageDetail;
  /** 移動端背景圖 */
  mobile_background_image?: BackgroundImageDetail;
}

/** bot ext */
export interface BotExtInfo {
  answer_actions?: AnswerActions;
  card_ids?: Array<number>;
  prompt_id?: number;
  bot_template_name?: string;
  use_ugc_voice?: boolean;
  app_id?: number;
  /** 是否綁定小程序標識 */
  binding_mp?: boolean;
}

/** bot信息 */
export interface BotInfo {
  /** bot id */
  bot_id?: string;
  /** bot名稱 */
  name?: string;
  /** bot描述 */
  description?: string;
  /** bot 圖標uri */
  icon_uri?: string;
  /** bot 圖標url */
  icon_url?: string;
  /** 創建人id */
  creator_id?: string;
  /** 創建時間 */
  create_time?: string;
  /** 更新時間 */
  update_time?: string;
  /** 業務線 */
  connector_id?: string;
  /** 版本，毫秒 */
  version?: string;
  /** 模型配置 */
  model_info?: ModelInfo;
  /** prompt 信息 */
  prompt_info?: PromptInfo;
  /** plugin列表 */
  plugin_info_list?: Array<PluginInfo>;
  /** Workflow 列表 */
  workflow_info_list?: Array<WorkflowInfo>;
  /** 開場白 */
  onboarding_info?: OnboardingInfo;
  /** 數據集 */
  knowledge?: Knowledge;
  /** kv存儲 */
  variable_list?: Array<Variable>;
  /** 任務管理/預設任務 */
  task_info?: TaskInfo;
  /** 數據表 */
  database_list?: Array<Database>;
  /** 推薦問題 */
  suggest_reply_info?: SuggestReplyInfo;
  /** 音色配置 */
  voices_info?: VoicesInfo;
  /** 額外信息，擴展字段 */
  bot_ext_info?: BotExtInfo;
  /** bot 類型，single agent or multi agent */
  bot_mode?: BotMode;
  /** multi agent mode agent信息 */
  agents?: Array<Agent>;
  /** Bot種類 */
  bot_species?: BotSpecies;
  /** bot tag 信息，用戶新增字段 */
  bot_tag_info?: BotTagInfo;
  /** filebox 信息 */
  filebox_info?: FileboxInfo;
  /** multi_agent結構體 */
  multi_agent_info?: MultiAgentInfo;
  /** 背景圖列表結構體 */
  background_image_info_list?: Array<BackgroundImageInfo>;
  shortcut_sort?: Array<string>;
  /** bot狀態 */
  status?: BotStatus;
  /** hook信息 */
  hook_info?: HookInfo;
  /** 用戶query收集配置 */
  user_query_collect_conf?: UserQueryCollectConf;
  /** workflow模式的編排信息 */
  layout_info?: LayoutInfo;
  business_type?: BusinessType;
}

/** bot信息 for 更新 */
export interface BotInfoForUpdate {
  /** bot id */
  bot_id?: string;
  /** bot名稱 */
  name?: string;
  /** bot描述 */
  description?: string;
  /** bot 圖標uri */
  icon_uri?: string;
  /** bot 圖標url */
  icon_url?: string;
  /** 創建人id */
  creator_id?: string;
  /** 創建時間 */
  create_time?: string;
  /** 更新時間 */
  update_time?: string;
  /** 業務線 */
  connector_id?: string;
  /** 版本，毫秒 */
  version?: string;
  /** 模型配置 */
  model_info?: ModelInfo;
  /** prompt 信息 */
  prompt_info?: PromptInfo;
  /** plugin列表 */
  plugin_info_list?: Array<PluginInfo>;
  /** Workflow 列表 */
  workflow_info_list?: Array<WorkflowInfo>;
  /** 開場白 */
  onboarding_info?: OnboardingInfo;
  /** 數據集 */
  knowledge?: Knowledge;
  /** kv存儲 */
  variable_list?: Array<Variable>;
  /** 任務管理/預設任務 */
  task_info?: TaskInfo;
  /** 數據表 */
  database_list?: Array<Database>;
  /** 推薦問題 */
  suggest_reply_info?: SuggestReplyInfo;
  /** 音色配置 */
  voices_info?: VoicesInfo;
  /** 額外信息，擴展字段 */
  bot_ext_info?: BotExtInfo;
  /** bot 類型，single agent or multi agent */
  bot_mode?: BotMode;
  /** multi agent mode agent信息 */
  agents?: Array<AgentForUpdate>;
  /** Bot種類 */
  bot_species?: BotSpecies;
  /** bot tag 信息，用戶新增字段 */
  bot_tag_info?: BotTagInfo;
  /** filebox 信息 */
  filebox_info?: FileboxInfo;
  /** multi_agent結構體 */
  multi_agent_info?: MultiAgentInfo;
  /** 背景圖列表結構體 */
  background_image_info_list?: Array<BackgroundImageInfo>;
  shortcut_sort?: Array<string>;
  hook_info?: HookInfo;
  /** 用戶query收集配置 */
  user_query_collect_conf?: UserQueryCollectConf;
  /** workflow模式的編排信息 */
  layout_info?: LayoutInfo;
}

export interface BotTagInfo {
  /** 時間膠囊信息 tag key : time_capsule */
  time_capsule_info?: TimeCapsuleInfo;
}

export interface CanvasPosition {
  width?: number;
  height?: number;
  left?: number;
  top?: number;
}

export interface ChatV3ChatDetail {
  id: string;
  conversation_id: string;
  bot_id: string;
  created_at?: number;
  completed_at?: number;
  failed_at?: number;
  meta_data?: Record<string, string>;
  last_error?: LastError;
  status: string;
  usage?: Usage;
  required_action?: RequiredAction;
  section_id?: string;
}

export interface ChatV3MessageDetail {
  id: string;
  conversation_id: string;
  bot_id: string;
  role: string;
  type: string;
  content: string;
  content_type: string;
  meta_data?: Record<string, string>;
  chat_id: string;
  section_id?: string;
  created_at?: Int64;
  updated_at?: Int64;
  reasoning_content?: string;
}

export interface CompletionUsage {
  reasoning_tokens?: number;
}

export interface Database {
  /** table id */
  table_id?: string;
  /** table名稱 */
  table_name?: string;
  /** table簡介 */
  table_desc?: string;
  /** table字段信息 */
  field_list?: Array<FieldItem>;
  /** 是否支持在Prompt中調用 默認支持 */
  prompt_disabled?: boolean;
  rw_mode?: BotTableRWMode;
}

export interface DraftBotInfoV2 {
  BotInfo?: BotInfo;
  CanvasData?: string;
  BaseCommitVersion?: Int64;
  CommitVersion?: Int64;
  /** TableInfo */
  TableInfo?: Record<string, TableDetail>;
  /** taskInfo */
  TaskInfo?: Record<string, TaskInfoDetail>;
}

export interface FieldItem {
  /** 字段名稱 */
  name?: string;
  /** 字段描述 */
  desc?: string;
  /** 字段類型 */
  type?: FieldItemType;
  /** 是否必填 */
  must_required?: boolean;
  /** 字段Id 新增爲0 */
  id?: string;
  /** 字段類型 str */
  type_str?: string;
  /** 字段類型 str */
  alterId?: Int64;
}

export interface FileboxInfo {
  Mode?: FileboxInfoMode;
}

export interface GradientPosition {
  left?: number;
  right?: number;
}

export interface HookInfo {
  /** pre agent跳轉hook */
  pre_agent_jump_hook?: Array<HookItem>;
  /** post agent跳轉hook */
  post_agent_jump_hook?: Array<HookItem>;
  /** 流程hook */
  flow_hook?: Array<HookItem>;
  /** 原子能力hook */
  atomic_hook?: Array<HookItem>;
  /** 模型調用hook */
  llm_call_hook?: Array<HookItem>;
  /** 對話結果hook */
  res_parsing_hook?: Array<HookItem>;
  /** suggesion hook */
  suggestion_hook?: Array<HookItem>;
}

export interface HookItem {
  uri?: string;
  filter_rules?: Array<string>;
  strong_dep?: boolean;
  timeout_ms?: Int64;
}

export interface IndependentModeConfig {
  /** 判斷時機 */
  judge_timing?: IndependentTiming;
  history_round?: number;
  model_type?: IndependentRecognitionModelType;
  model_id?: string;
  prompt?: string;
}

export interface Intent {
  intent_id?: string;
  prompt?: string;
  next_agent_id?: string;
  session_type?: MultiAgentSessionType;
}

export interface InterruptFunction {
  name?: string;
  arguments?: string;
}

export interface InterruptPlugin {
  id?: string;
  type?: string;
  function?: InterruptFunction;
  require_info?: InterruptRequireInfo;
}

export interface InterruptRequireInfo {
  infos?: Array<string>;
}

export interface JumpConfig {
  backtrack?: BacktrackMode;
  recognition?: RecognitionMode;
  independent_conf?: IndependentModeConfig;
}

export interface Knowledge {
  /** 知識庫信息 */
  knowledge_info?: Array<KnowledgeInfo>;
  /** 召回最大數據量 */
  top_k?: Int64;
  /** 最小匹配度 */
  min_score?: number;
  /** 自動召回 */
  auto?: boolean;
  /** 搜索策略 */
  search_strategy?: SearchStrategy;
  /** 是否展示來源 */
  show_source?: boolean;
  /** 無召回回覆mode，默認0 */
  no_recall_reply_mode?: KnowledgeNoRecallReplyMode;
  /** 無召回回覆時自定義prompt，當NoRecallReplyMode=1時生效 */
  no_recall_reply_customize_prompt?: string;
  /** 來源展示方式 默認值0 卡片列表方式 */
  show_source_mode?: KnowledgeShowSourceMode;
  /** 召回策略, 默認值爲true */
  recall_strategy?: RecallStrategy;
  /** 當前agent下綁定的知識庫類型,multiagent無效 */
  knowledge_type_mode?: KnowledgeTypeMode;
}

export interface KnowledgeInfo {
  /** 知識庫id */
  id?: string;
  /** 知識庫名稱 */
  name?: string;
  /** coze or 火山知識庫 */
  type?: KnowledgeType;
  /** 火山側知識服務信息 */
  volcano_dataset_service_info?: VolcanoDatasetService;
}

export interface LastError {
  code: number;
  msg: string;
}

export interface LayoutInfo {
  /** workflowId */
  workflow_id?: string;
  /** PluginId */
  plugin_id?: string;
}

export interface MessageFeedback {
  /** 反饋類型 */
  feedback_type?: MessageFeedbackType;
  /** 細分類型 */
  detail_types?: Array<MessageFeedbackDetailType>;
  /** 負反饋自定義內容，對應用戶選擇Others */
  detail_content?: string;
}

export interface ModelInfo {
  /** 模型id */
  model_id?: string;
  /** 溫度，模型輸出隨機性，值越大越隨機，越小越保守(0-1] */
  temperature?: number;
  /** 回覆最大Token數 */
  max_tokens?: number;
  /** 另一種模型的輸出隨機性，值越大越隨機[0,1] */
  top_p?: number;
  /** 頻率懲罰，調整生成內容中的單詞頻率，正值單詞越少見[-1.0,1.0] */
  frequency_penalty?: number;
  /** 存在懲罰，調整生成內容中新詞語頻率，正值避免重複單詞，用新詞[-1.0,1.0] */
  presence_penalty?: number;
  /** 上下文策略 */
  short_memory_policy?: ShortMemoryPolicy;
  /** 生成時，採樣候選集的大小 */
  top_k?: number;
  /** 模型回覆內容格式 */
  response_format?: ModelResponseFormat;
  /** 用戶選擇的模型風格 */
  model_style?: ModelStyle;
  /** 緩存配置 */
  cache_type?: CacheType;
  /** sp拼接當前時間 */
  sp_current_time?: boolean;
  /** sp拼接防泄露指令 */
  sp_anti_leak?: boolean;
  /** sp拼接聲紋信息 */
  sp_voice_info?: boolean;
  /** 個性化配置參數 */
  parameters?: Record<string, string>;
}

export interface MultiAgentInfo {
  /** multi_agent會話接管方式 */
  session_type?: MultiAgentSessionType;
  /** multi_agent版本兼容字段 前端用 */
  version_compat_info?: AgentVersionCompatInfo;
  /** multi_agent連線類型 前端用 */
  connector_type?: MultiAgentConnectorType;
}

export interface OnboardingInfo {
  /** 對應 Coze Opening Dialog
開場白 */
  prologue?: string;
  /** 建議問題 */
  suggested_questions?: Array<string>;
  /** 開場白模型 */
  onboarding_mode?: OnboardingMode;
  /** LLM生成，用戶自定義 Prompt */
  customized_onboarding_prompt?: string;
  /** 開場白預設問題展示方式 默認0 隨機展示 */
  suggested_questions_show_mode?: SuggestedQuestionsShowMode;
}

export interface PluginInfo {
  /** 插件id */
  plugin_id?: string;
  /** api Id */
  api_id?: string;
  /** api name O項目用 */
  api_name?: string;
}

export interface PluginParameter {
  name?: string;
  desc?: string;
  required?: boolean;
  type?: string;
  sub_parameters?: Array<PluginParameter>;
  /** 如果Type是數組，則有subtype */
  sub_type?: string;
}

export interface PrefixPromptInfo {
  /** 前綴提示詞 */
  prefix_prompt?: string;
  /** 不支持前綴提示詞部分 */
  dynamic_prompt?: string;
}

export interface PromptInfo {
  /** 文本prompt */
  prompt?: string;
  /** 提示詞模式 */
  prompt_mode?: PromptMode;
  /** 前綴提示詞模式下的prompt內容 */
  prefix_prompt_info?: PrefixPromptInfo;
}

export interface PromptUsage {
  cached_tokens?: number;
}

export interface RecallStrategy {
  use_rerank?: boolean;
  use_rewrite?: boolean;
  use_nl2sql?: boolean;
}

export interface RequiredAction {
  type?: string;
  submit_tool_outputs?: SubmitToolOutputs;
}

export interface ShortMemoryPolicy {
  /** 上下文允許傳輸的類型 */
  context_mode?: ContextMode;
  /** 上下文帶的輪數 */
  history_round?: number;
}

export interface SocietyVisibiltyConfig {
  /** 社會場景中可見性: Public = 1,Anonymous = 2 */
  visibility_type?: SocietyVisibility;
  /** 可見角色列表 */
  visibility_roles?: Array<string>;
}

export interface SubmitToolOutputs {
  tool_calls?: Array<InterruptPlugin>;
}

/** suggest */
export interface SuggestReplyInfo {
  /** 對應 Coze Auto-Suggestion
建議問題模型 */
  suggest_reply_mode?: SuggestReplyMode;
  /** 用戶自定義建議問題 */
  customized_suggest_prompt?: string;
  /** 運行Prompt的ChainTask名稱 */
  chain_task_name?: string;
}

export interface TableDetail {
  /** table id */
  TableId?: string;
  /** table名稱 */
  TableName?: string;
  /** table簡介 */
  TableDesc?: string;
  /** table字段信息 */
  FieldList?: Array<FieldItem>;
  /** 是否支持在Prompt中調用 默認支持 */
  prompt_disabled?: boolean;
}

export interface TaskInfo {
  /** coze 上的 Scheduled Tasks
用戶開啓task任務 */
  user_task_allowed?: boolean;
  /** 允許預設任務 */
  enable_preset_task?: Int64;
}

export interface TaskInfoDetail {
  /** Tasks Detail
任務唯一標識 */
  TaskId?: string;
  /** 定時器觸發時執行的 query，例如：提醒我喝水. 二期：TriggerType == "Time" */
  UserQuestion?: string;
  /** 定時任務創建時間 */
  CreateTime?: string;
  /** 定時任務下次執行的時間點 */
  NextTime?: string;
  /** 任務狀態：有效/無效 */
  Status?: Int64;
  /** 1-草稿，2-線上 */
  PresetType?: number;
  /** 定時任務的 crontab 表達式 */
  CronExpr?: string;
  /** 處理過後的 UserQuestion，例如：喝水 */
  TaskContent?: string;
  /** 時區 */
  TimeZone?: string;
  /** 任務名稱 */
  TaskName?: string;
  /** "Time", "Event" */
  TriggerType?: string;
  /** "Bot query", "Plugin", "Workflow" */
  Action?: string;
  /** Action == "Bot query" 時的輸入 */
  BotQuery?: string;
  /** plugin 和 workflow 都用這個字段 */
  PluginName?: string;
  /** plugin 和 workflow 都用這個字段 */
  PluginInput?: TaskPluginInput;
  /** TriggerType == "Event" */
  WebhookUrl?: string;
  /** TriggerType == "Event" */
  WebhookBearerToken?: string;
  /** TriggerType == "Event" */
  WebhookOutput?: TaskWebhookOutput;
  /** 溯源 ID。創建時生成，更新/發佈不變 */
  OriginId?: string;
}

export interface TaskPluginInput {
  Params?: Array<TaskPluginInputField>;
}

export interface TaskPluginInputField {
  Name?: string;
  /** "Input", "Reference" */
  Type?: string;
  Value?: string;
}

export interface TaskWebhookField {
  Name?: string;
  Type?: string;
  Description?: string;
  Children?: Array<TaskWebhookField>;
}

export interface TaskWebhookOutput {
  Params?: Array<TaskWebhookField>;
}

/** 時間膠囊信息 */
export interface TimeCapsuleInfo {
  time_capsule_mode?: TimeCapsuleMode;
  disable_prompt_calling?: DisablePromptCalling;
  /** 時間膠囊過期時間，單位天（0表示永久有效） */
  time_capsule_time_to_live?: string;
}

export interface Usage {
  token_count?: number;
  output_count?: number;
  input_count?: number;
  input_tokens_details?: PromptUsage;
  output_tokens_details?: CompletionUsage;
}

export interface UserLabel {
  label_id?: string;
  label_name?: string;
  icon_uri?: string;
  icon_url?: string;
  jump_link?: string;
}

export interface UserQueryCollectConf {
  /** 是否開啓收集開關 */
  is_collected?: boolean;
  /** 隱私協議鏈接 */
  private_policy?: string;
}

export interface Variable {
  /** key, Field */
  key?: string;
  /** 描述 */
  description?: string;
  /** 默認值 */
  default_value?: string;
  /** 是否系統值系統值 */
  is_system?: boolean;
  /** 是否支持在Prompt中調用 默認支持 */
  prompt_disabled?: boolean;
  /** 社會場景中可見性: Public = 1,Anonymous = 2 */
  society_visibility_config?: SocietyVisibiltyConfig;
  /** 是否禁用，默認爲false代表啓用 */
  is_disabled?: boolean;
}

export interface VideoCallConfig {
  /** 是否關閉 */
  video_call?: boolean;
  /** 每秒抽取幀數(範圍1～24) */
  frames_per_second?: number;
  /** 開始說話前抽取秒數(範圍0～10s) */
  pre_speech_seconds?: number;
}

export interface VoiceprintRecognitionConfig {
  /** 是否關閉聲紋識別 */
  close_voice_print_recognition?: boolean;
  /** 命中閾值 */
  hit_threshold?: number;
  /** 空值時是否沿用歷史開關 */
  use_history_if_empty?: boolean;
}

/** tts Voices */
export interface VoicesInfo {
  /** 對應 Coze Voices
是否開啓聲音 true:禁用  false:開啓 */
  muted?: boolean;
  /** 多語音音色配置 */
  i18n_lang_voice?: Record<string, Int64>;
  /** 是否自動播放 */
  autoplay?: boolean;
  /** 自動播放的音色 */
  autoplay_voice?: Record<string, Int64>;
  /** 是否關閉語音通話，true:關閉 false:開啓  默認爲false */
  voice_call?: boolean;
  /** 默認用戶輸入類型 */
  default_user_input_type?: DefaultUserInputType;
  /** 多語音音色配置, string類型 */
  i18n_lang_voice_str?: Record<string, string>;
  video_call_config?: VideoCallConfig;
  voiceprint_recognition_config?: VoiceprintRecognitionConfig;
}

export interface VolcanoDatasetService {
  /** 火山側知識服務id 字符串 */
  id?: string;
  /** 名稱 */
  name?: string;
}

export interface WorkflowInfo {
  /** WorkflowId */
  workflow_id?: string;
  /** 插件id */
  plugin_id?: string;
  /** api Id */
  api_id?: string;
  /** workflow or imageflow, 默認爲workflow */
  flow_mode?: WorkflowMode;
  /** workflow name */
  workflow_name?: string;
  desc?: string;
  parameters?: Array<PluginParameter>;
  plugin_icon?: string;
}
/* eslint-enable */
