/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ActionKey {
  /** 複製 */
  Copy = 1,
  /** 刪除 */
  Delete = 2,
  /** 啓用/禁用 */
  EnableSwitch = 3,
  /** 編輯 */
  Edit = 4,
  /** 切換成funcflow */
  SwitchToFuncflow = 8,
  /** 切換成chatflow */
  SwitchToChatflow = 9,
  /** 跨空間複製 */
  CrossSpaceCopy = 10,
}

export enum AgentBizUniversalMethod {
  Unknown = 0,
  Get = 1,
  Post = 2,
}

export enum AgentTriggerAPIType {
  Unknown = 0,
  Workflow = 1,
  Chat = 2,
  ChatV3 = 3,
}

export enum AIGenerateCardStatus {
  /** AI Schema 生成且格式符合預期 */
  Init = 0,
  /** AI Schema 轉 Card 成功 */
  Success = 1,
  /** 格式與預期不符 */
  Invalid = 2,
  /** 格式符合預期但轉卡片失敗 */
  Failed = 3,
  /** 手動終止，部分成功 */
  Interrupt = 4,
}

export enum AISchemaTransferStatus {
  Success = 1,
  Failed = 2,
  Interrupt = 3,
}

export enum AuditStatus {
  /** 鏈接內容不通過 */
  LinkRejected = -60,
  /** 視頻內容不通過 */
  VideoRejected = -50,
  /** 音頻內容不通過 */
  AudioRejected = -40,
  /** 圖片內容不通過 */
  ImageRejected = -30,
  /** 文本內容不通過 */
  TextRejected = -20,
  /** 審覈不通過(原因見詳情) */
  Rejected = -1,
  /** 審覈通過 */
  Approved = 1,
  /** 待審覈 */
  Pending = 100,
}

export enum CardCategory {
  /** 模版卡片 */
  Template = 1,
  /** 自定義卡片 */
  Custom = 2,
}

export enum CardDisplayType {
  /** 基礎 */
  Basic = 1,
  /** 列表 */
  List = 2,
  /** 自定義卡片 */
  Custom = 3,
  /** 橫向列表 */
  Slide = 4,
}

export enum CardStatus {
  Draft = 0,
  Published = 1,
  UnPublish = 2,
}

export enum CardThumbnailStatus {
  /** 未定義 */
  Default = 0,
  /** 空卡片 */
  Empty = 1,
  /** 待生成 */
  NeedGenerate = 2,
  /** 生成中 */
  Generating = 3,
  /** 生成失敗 */
  Failed = 4,
  /** 生成成功 */
  Success = 5,
  /** 已發佈卡片編輯過待重新發布 */
  NeedPublish = 6,
}

export enum ChannelType {
  Default = 0,
  Doubao = 100,
  CiCi = 101,
  Feishu = 200,
  WhatsApp = 300,
  Discord = 301,
  Twitter = 302,
  Telegram = 303,
  Messenger = 304,
  LINE = 305,
  Instagram = 306,
  Slack = 307,
  Reddit = 308,
}

export enum CopyStatus {
  Succeed = 0,
  Fail = 1,
}

export enum DocumentType {
  /** 上傳中 */
  Processing = 0,
  /** 生效 */
  Enable = 1,
  /** 失效 */
  Disable = 2,
  /** 刪除 */
  Deleted = 3,
  /** 失敗 */
  Failed = 9,
}

export enum PublishStatus {
  /** 未發佈 */
  UnPublished = 1,
  /** 已發佈 */
  Published = 2,
}

export enum Scene {
  /** 卡片，實際對應文件類型是圖片 */
  Card = 0,
  /** agent，實際對應文件類型是PDF */
  Agent = 1,
  /** 音頻 */
  Audio = 2,
  /** 縮略圖 */
  Thumbnail = 3,
  /** 視頻 */
  Video = 4,
}

export enum SliceStatus {
  /** 未向量化 */
  PendingVectoring = 0,
  /** 已向量化 */
  FinishVectoring = 1,
  /** 禁用 */
  Deactive = 9,
}

export enum SortField {
  Default = 0,
  /** 更新時間 */
  UpdateTime = 1,
  /** 發佈時間 */
  PublishTime = 2,
}

export enum SortOrderType {
  /** 降序 */
  Desc = 0,
  /** 升序 */
  Asc = 1,
}

export enum Stage {
  Copy = 1,
  Replace = 2,
  RollBack = 3,
}

export enum TccServiceID {
  Card = 0,
  CardBuilder = 1,
}

/** -------------- 運營平臺接口 end -------------- */
export enum ToolType {
  Plugin = 1,
  Workflow = 2,
  Widget = 3,
}

export interface CardMetaInfo {
  dsl_content?: string;
  lynx_url?: string;
  thumbnail?: string;
  channel_type?: ChannelType;
  version_num?: string;
  /** 審覈狀態 */
  audit_status?: AuditStatus;
  /** 審覈不通過詳情 */
  audit_failure_details?: Array<number>;
}
/* eslint-enable */
