/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as principal from './principal';

export type Int64 = string | number;

export enum RoleCode {
  BotEditor = 1,
  BotDeveloper = 2,
  BotOperator = 3,
  WorkflowEditor = 4,
  ProjectEditor = 5,
}

export enum RoleType {
  /** 預定義角色 */
  Predefined = 1,
  /** 自定義角色 */
  Custom = 2,
}

export interface CollaboratorExistInfo {
  /** 當前principla是否爲協作者 */
  principal_is_collaborator: boolean;
  /** 當前資源上是否有協作者 */
  resource_has_collaborator: boolean;
}

export interface RoleAttachment {
  /** 角色Code */
  code: string;
  /** 主體 */
  principal: principal.PrincipalIdentifier;
  /** 創建時間 */
  create_time: Int64;
  enum_code: RoleCode;
}

export interface UpgradeInfo {
  /** 是否能升級 */
  can_upgrade: boolean;
  /** 當前計劃的協作者人數限制 */
  current_collaborator_limit: number;
}
/* eslint-enable */
