#!/bin/bash
if [ "$SKIP_COMMIT_MSG_HOOK" = "true" ]; then
  exit 0
fi

# rebase 過程中分支名格式爲 (no branch, rebasing chore/replace-rushtool)
# 正常提交時分支名格式爲 chore/replace-rushtool
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
# 如果匹配到 rebase 格式的輸出，認爲是在rebase ，則跳過自動推送
if [[ "X${BRANCH_NAME}" == "X(no branch"* ]]; then
  exit
else
  node common/scripts/install-run-rush.js change-x -a || exit 1
fi
