/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as bot_operation_common from './bot_operation_common';
import * as common from './common';
import * as fulfill_common from './fulfill_common';

export type Int64 = string | number;

/** 發放獎勵任務的狀態 */
export enum DistRewardTaskStatus {
  Unknown = 0,
  /** 審覈中 */
  InReview = 1,
  /** 已拒絕 */
  Rejected = 2,
  /** 已通過 */
  Approved = 3,
  /** 已撤回 */
  Canceled = 4,
}

export enum DistRewardType {
  Unknonw = 0,
  /** 需傳遞 AddMessageCreditsRewardStruct 結構體 */
  MessageCredits = 1,
  /** 暫時不支持，後續遷移過來 */
  CozeToken = 2,
  /** 退款申請，複用審批任務 */
  Refund = 3,
}

export interface AddCozeTokenStruct {
  amount: Int64;
}

export interface AddMessageCreditsRewardStruct {
  amount_per_day: Int64;
  active_days: Int64;
}

export interface AdminCancelDistRewardTaskRequest {
  /** 主鍵 */
  id: string;
}

export interface AdminCancelDistRewardTaskResponse {
  code?: number;
  message?: string;
}

export interface AdminCreateDistRewardTaskRequest {
  /** 發放給誰 */
  to_uid_list: Array<string>;
  /** 發放獎勵的類型 */
  dist_reward_type: DistRewardType;
  /** 發放獎勵具體內容 */
  reward_detail: RewardDetail;
  /** 原因 */
  reason: string;
}

export interface AdminCreateDistRewardTaskResponse {
  code?: number;
  message?: string;
  data?: AdminCreateDistRewardTaskResponseData;
}

export interface AdminCreateDistRewardTaskResponseData {
  /** 任務主鍵 id */
  id?: string;
}

export interface AdminListDistRewardTaskFulfillmentRequest {
  /** 任務主鍵 id */
  task_id: string;
}

export interface AdminListDistRewardTaskFulfillmentResponse {
  code?: number;
  message?: string;
  data?: AdminListDistRewardTaskFulfillmentResponseData;
}

export interface AdminListDistRewardTaskFulfillmentResponseData {
  /** 履約單列表 */
  fulfillment_list?: Array<Fulfillment>;
}

export interface AdminListDistRewardTaskRequest {
  /** 頁碼, >=1 */
  page: Int64;
  /** 每頁數量, 1-200 */
  count: Int64;
  /** 狀態 */
  status_in?: Array<DistRewardTaskStatus>;
  /** 創建時間開始，秒時間戳 */
  created_at_begin?: Int64;
  /** 發給哪個 uid 了 */
  uid?: string;
  /** 是否禁用環境隔離 */
  disable_env?: boolean;
  dist_reward_type?: DistRewardType;
}

export interface AdminListDistRewardTaskResponse {
  code?: number;
  message?: string;
  data?: AdminListDistRewardTaskResponseData;
}

export interface AdminListDistRewardTaskResponseData {
  /** 任務列表 */
  task_list?: Array<DistRewardTask>;
  /** 總數 */
  total?: Int64;
}

/** dist Reward task 的實體 */
export interface DistRewardTask {
  /** 主鍵 */
  id?: string;
  /** 誰創建的 */
  op_user?: bot_operation_common.ByteDanceUser;
  /** 誰審批的 */
  approval_user?: bot_operation_common.ByteDanceUser;
  /** 發放獎勵的類型 */
  dist_reward_type?: DistRewardType;
  /** 發放獎勵具體內容 */
  reward_detail?: RewardDetail;
  /** 一共給多少人 */
  user_count?: Int64;
  /** 狀態 */
  status?: DistRewardTaskStatus;
  /** 原因 */
  reason?: string;
  /** 創建時間，秒時間戳 */
  created_at?: Int64;
  /** 審批實例 code */
  approval_instance_code?: string;
  /** 數據所屬環境，爲空表示基準環境，否則爲多環境 */
  env?: string;
  /** uid 的 列表 */
  uid_list?: Array<string>;
}

export interface Fulfillment {
  /** 主鍵 */
  id?: string;
  /** 實體類型 */
  entity_type?: common.EntityType;
  /** 狀態 */
  status?: fulfill_common.FulfillmentStatus;
  /** 創建時間，秒時間戳 */
  created_at?: Int64;
  /** 發送給誰的 */
  to_user?: bot_operation_common.PassportUser;
}

export interface RefundStruct {
  OrderID?: string;
  RefundAmount?: Int64;
  Currency?: string;
  Reason?: string;
  GoodsTypeDisplay?: string;
  OrderType?: bot_operation_common.OrderType;
  RefundSubsExpiryTime?: string;
  IsSkipCheck?: boolean;
}

export interface RewardDetail {
  /** DistRewardType 爲 MessageCredits 需要傳該結構體 */
  add_message_credits_reward_struct?: AddMessageCreditsRewardStruct;
  /** DistRewardType 爲 CozeToken 需要傳該結構體 */
  add_coze_token_struct?: AddCozeTokenStruct;
  RefundStruct?: RefundStruct;
}
/* eslint-enable */
