/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum FulfillmentStatus {
  Unknown = 0,
  /** 初始化 */
  Init = 1,
  /** 運行中 */
  Running = 2,
  /** 待重試 */
  ToRetry = 3,
  /** 已成功 */
  Succeed = 4,
  /** 已失敗 */
  Failed = 5,
}

export enum FulfillmentType {
  /** 未知 */
  Unknown = 0,
  /** 增加實體的可調用量 */
  AddEntityAmount = 1,
  /** 用於發送協議支付請求，接收協議支付回調 */
  AutoChargePayment = 2,
  /** 協議支付回調 */
  AutoChargeCallback = 3,
  /** 增加 message credits */
  AddMessageCredits = 4,
}

export enum SourceType {
  /** 未知 */
  Unknown = 0,
  /** bot 運營平臺,  */
  BotOperationPlatform = 1,
  /** 支付系統 */
  Trade = 2,
  /** 內部調用 */
  Inner = 3,
}
/* eslint-enable */
