/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as common from './common';
import * as uniexam from './uniexam';
import * as origin from './origin';

export type Int64 = string | number;

export interface AnswerMyPaperExamQuestionReq {
  paper_exam_id?: Int64;
  question_answers?: Record<Int64, Array<Int64>>;
  base?: base.Base;
}

export interface AnswerMyPaperExamQuestionResp {
  paper_exam_answers?: Array<common.PaperExamAnswer>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface BatchCreateUserPaperExaminationReq {
  /** 考試名單列表 */
  paper_exams: Array<common.CreatePaperExamParams>;
  base?: base.Base;
}

export interface BatchCreateUserPaperExaminationResp {
  /** 成功列表 */
  success_list?: Array<common.PaperExam>;
  /** 失敗列表 */
  fail_list?: Array<string>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CheckAdminPermissionReq {
  base?: base.Base;
}

export interface CheckAdminPermissionResp {
  is_admin?: boolean;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CheckAlphaTestPermissionReq {
  base?: base.Base;
}

export interface CheckAlphaTestPermissionResp {
  is_alpha?: boolean;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ConfirmUniExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  /** 聽力試卷等級 */
  listening_paper_level?: uniexam.GeneralLevel;
  /** 聽力得分 */
  listening_score?: number;
  /** 聽力等級 */
  listening_level?: uniexam.DetailLevel;
  /** 口語得分 */
  oral_score?: number;
  /** 口語等級 */
  oral_level?: uniexam.DetailLevel;
  /** 最終定級(不傳最終定級僅保存分數，狀態不變，傳最終定級會確定提交批改，狀態變爲已完成) */
  final_level?: uniexam.DetailLevel;
  /** 確認類型(0:未知 1:確認 2:保存) */
  confirm_type?: uniexam.ConfirmUniExamType;
  base?: base.Base;
}

export interface ConfirmUniExamRecordResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreatePaperReq {
  /** 試卷名稱 */
  name: string;
  /** 試卷難度 */
  level: common.PaperLevel;
  base?: base.Base;
}

export interface CreatePaperResp {
  paper?: common.Paper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateQuestionGroupReq {
  /** 試卷ID */
  paper_id: Int64;
  /** 題幹 */
  content: string;
  /** 關聯音頻 */
  audio_id?: string;
  /** 關聯圖片 */
  picture?: string;
  /** 題目列表 */
  questions?: Array<common.CreatePaperQuestionParams>;
  base?: base.Base;
}

export interface CreateQuestionGroupResp {
  question_group?: common.PaperQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateQuestionOptionReq {
  /** 題目ID */
  paper_question_id: Int64;
  /** 選項內容 */
  content: string;
  /** 是否正確 */
  is_correct: common.QuestionOptionCorrectStatus;
  base?: base.Base;
}

export interface CreateQuestionOptionResp {
  question_option?: common.PaperQuestionOption;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateQuestionReq {
  /** 題目組ID */
  paper_question_group_id: Int64;
  /** 題幹 */
  content: string;
  /** 選項列表 */
  question_options?: Array<common.CreatePaperQuestionOptionParams>;
  base?: base.Base;
}

export interface CreateQuestionResp {
  question?: common.PaperQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateTeamExamTestReq {
  /** 測試名稱 */
  name?: string;
  /** 批改類型 4人工批改 5機器批改 */
  check_type?: common.TeamExamCheckType;
  /** 開始時間(秒級時間戳) */
  start_at?: Int64;
  /** 結束時間(秒級時間戳) */
  end_at?: Int64;
  /** 用戶篩選條件 */
  filter?: uniexam.TeamExamTestFilter;
  /** 郵箱篩選條件 */
  email?: uniexam.TeamExamTestEmail;
  base?: base.Base;
}

export interface CreateTeamExamTestResp {
  /** 測試ID */
  id?: Int64;
  /** 配置不成功用戶列表(正在其他測試中) */
  test_conflict_users?: Array<uniexam.User>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateUniExamPaperReq {
  /** 試卷名稱 */
  name: string;
  /** 試卷難度 */
  level: uniexam.GeneralLevel;
  base?: base.Base;
}

export interface CreateUniExamPaperResp {
  paper?: uniexam.UniExamListeningPaper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateUniExamQuestionGroupNFNReq {
  /** 試卷ID */
  paper_id?: Int64;
  /** 題目組ID，傳空爲創建，否則爲更新 */
  question_group_id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 圖片URI */
  image_uri?: string;
  /** 選項內容列表 */
  option_contents?: Array<string>;
  /** 題目列表 */
  questions?: Array<uniexam.UniExamQuestionCreateNFNParams>;
  base?: base.Base;
}

export interface CreateUniExamQuestionGroupNFNResp {
  question_group?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateUniExamQuestionGroupReq {
  /** 試卷ID */
  paper_id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 圖片URI */
  image_uri?: string;
  /** 題目列表 */
  questions?: Array<uniexam.UniExamQuestionCreateParams>;
  base?: base.Base;
}

export interface CreateUniExamQuestionGroupResp {
  question_group?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface CreateUniExamQuestionReq {
  /** 題目組ID */
  question_group_id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 圖片URI */
  image_uri?: string;
  /** 口語題部分 */
  oral_part?: uniexam.QuestionOralPart;
  base?: base.Base;
}

export interface CreateUniExamQuestionResp {
  question?: uniexam.UniExamQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteOriginLibraryQuestionReq {
  /** 題目ID */
  id: Int64;
  base?: base.Base;
}

export interface DeleteOriginLibraryQuestionResp {
  question?: origin.LibraryQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeletePaperReq {
  /** 試卷ID */
  id: number;
  base?: base.Base;
}

export interface DeletePaperResp {
  paper?: common.Paper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteQuestionGroupReq {
  /** 題目組ID */
  id: Int64;
  base?: base.Base;
}

export interface DeleteQuestionGroupResp {
  question_group?: common.PaperQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteTeamExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface DeleteTeamExamRecordResp {
  team_exam?: uniexam.TeamExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteTeamExamRemindReq {
  /** robot_message_id */
  id?: Int64;
  base?: base.Base;
}

export interface DeleteTeamExamRemindResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteUniExamPaperReq {
  /** 試卷ID */
  id: number;
  base?: base.Base;
}

export interface DeleteUniExamPaperResp {
  paper?: uniexam.UniExamListeningPaper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteUniExamQuestionGroupReq {
  /** 題目組ID */
  id?: Int64;
  base?: base.Base;
}

export interface DeleteUniExamQuestionGroupResp {
  question_group?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteUniExamQuestionReq {
  /** 題目ID */
  id?: Int64;
  base?: base.Base;
}

export interface DeleteUniExamQuestionResp {
  question?: uniexam.UniExamQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteUniExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface DeleteUniExamRecordResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface DeleteUserPaperExaminationReq {
  /** ID */
  id: Int64;
  base?: base.Base;
}

export interface DeleteUserPaperExaminationResp {
  paper_exam?: common.PaperExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ExportConflictUsersReq {
  team_exam_id?: Int64;
  /** 用戶篩選條件 */
  filter?: uniexam.TeamExamTestFilter;
  /** 郵箱篩選條件 */
  email?: uniexam.TeamExamTestEmail;
  base?: base.Base;
}

export interface ExportConflictUsersResp {
  /** 文件URL */
  file_url?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ExportTeamExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface ExportTeamExamRecordResp {
  /** 文件URL */
  file_url?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ExportUniExamRecordReq {
  /** 過濾條件 */
  filter?: UniExamRecordFilter;
  base?: base.Base;
}

export interface ExportUniExamRecordResp {
  /** 文件URL */
  file_url?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ExportUserPaperExaminationReq {
  base?: base.Base;
}

export interface ExportUserPaperExaminationResp {
  /** 導出結果 tos 文件 */
  excel_id?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface FinishUniExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface FinishUniExamRecordResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetMyPaperExamReq {
  base?: base.Base;
}

export interface GetMyPaperExamResp {
  exams?: Array<common.PaperExam>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetOralAnswerCheckReq {
  /** 口語回答音頻URI */
  audio_uri: string;
  base?: base.Base;
}

export interface GetOralAnswerCheckResp {
  /** 用戶錄音轉文本 */
  asr_text?: string;
  /** gpt對文本的批改結果 */
  gpt_check_result?: string;
  /** 語音批改任務ID */
  task_id?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetOralAnswerCheckTaskResultReq {
  /** 任務ID */
  task_id: string;
  base?: base.Base;
}

export interface GetOralAnswerCheckTaskResultResp {
  /** 用戶錄音轉文本 */
  asr_text?: string;
  /** gpt對文本的批改結果 */
  gpt_check_result?: string;
  /** 任務詳情 */
  task?: uniexam.OralCheckTaskResult;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetOriginExamCertReq {
  base?: base.Base;
}

export interface GetOriginExamCertResp {
  exam_cert?: origin.TeamExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetOriginExamNextRoundReq {
  /** 考試ID */
  grade_exam_id?: Int64;
  /** 團隊考試ID */
  team_exam_id?: Int64;
  /** 當前輪次ID */
  current_round_id?: number;
  base?: base.Base;
}

export interface GetOriginExamNextRoundResp {
  /** 題目列表 */
  questions?: Array<origin.GradeExamLibraryQuestion>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetPlayVideoInfoReq {
  vids: Array<string>;
  base?: base.Base;
}

export interface GetPlayVideoInfoResp {
  play_info_map?: Record<string, common.PlayInfo>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetSessionUserInfoReq {
  'x-innovation-token'?: string;
  base?: base.Base;
}

export interface GetSessionUserInfoResp {
  id?: Int64;
  lark_name?: string;
  lark_email?: string;
  lark_union_id?: string;
  lark_open_id?: string;
  lark_user_id?: string;
  user_type?: uniexam.UserType;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetTeamExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface GetTeamExamRecordResp {
  team_exam?: uniexam.TeamExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetUniExamCertReq {
  base?: base.Base;
}

export interface GetUniExamCertResp {
  team_exam?: uniexam.TeamExam;
  /** 考試資格狀態 */
  cert_status?: uniexam.CertStatus;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetUniExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  base?: base.Base;
}

export interface GetUniExamRecordResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface GetUploadVideoTokenReq {
  base?: base.Base;
}

export interface GetUploadVideoTokenResp {
  access_key_id?: string;
  secret_access_key?: string;
  session_token?: string;
  expired_time?: string;
  current_time?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListCreateTeamExamTestOptionsReq {
  base?: base.Base;
}

export interface ListCreateTeamExamTestOptionsResp {
  /** 英語分組 */
  english_group?: Array<string>;
  /** 員工角色 */
  role?: Array<string>;
  /** 歷史最高成績 */
  highest_score?: Array<string>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListOriginExamResultReq {
  base?: base.Base;
}

export interface ListOriginExamResultResp {
  grade_exams?: Array<origin.GradeExam>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListOriginLibraryQuestionReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  /** 關鍵詞 */
  keyword?: string;
  /** 等級 */
  level?: string;
  /** 類型 */
  type?: origin.LibraryQuestionType;
  /** 狀態 */
  status?: origin.LibraryQuestionStatus;
  /** 新口語題 - 部分 */
  part?: origin.LibraryQuestionPart;
  base?: base.Base;
}

export interface ListOriginLibraryQuestionResp {
  questions?: Array<origin.LibraryQuestion>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListPaperForExamReq {
  /** 考試ID */
  paper_exam_id: Int64;
  base?: base.Base;
}

export interface ListPaperForExamResp {
  papers?: Array<common.Paper>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListPaperReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  /** 試卷狀態 */
  status?: common.PaperStatus;
  /** 試卷難度 */
  level?: common.PaperLevel;
  base?: base.Base;
}

export interface ListPaperResp {
  papers?: Array<common.Paper>;
  total?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListQuestionGroupReq {
  /** 試卷ID */
  paper_id: Int64;
  base?: base.Base;
}

export interface ListQuestionGroupResp {
  question_groups?: Array<common.PaperQuestionGroup>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListTeamExamRecordReq {
  /** 頁碼(默認爲1) */
  page?: number;
  /** 每頁數量(默認爲100) */
  page_size?: number;
  /** 測試名稱 */
  name?: string;
  /** 郵箱 */
  user_email?: string;
  base?: base.Base;
}

export interface ListTeamExamRecordResp {
  team_exams?: Array<uniexam.TeamExam>;
  total?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListTeamExamRemindReq {
  /** 團隊考試ID */
  team_exam_id?: Int64;
  base?: base.Base;
}

export interface ListTeamExamRemindResp {
  robot_messages?: Array<uniexam.RobotMessage>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListTeamReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  /** 團隊名稱 */
  name?: string;
  base?: base.Base;
}

export interface ListTeamResp {
  teams?: Array<uniexam.Team>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamPaperReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  /** 試卷狀態 */
  status?: uniexam.OnlineStatus;
  /** 試卷難度 */
  level?: uniexam.GeneralLevel;
  base?: base.Base;
}

export interface ListUniExamPaperResp {
  papers?: Array<uniexam.UniExamListeningPaper>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamQuestionGroupReq {
  /** 試卷ID */
  paper_id?: Int64;
  base?: base.Base;
}

export interface ListUniExamQuestionGroupResp {
  question_groups?: Array<uniexam.UniExamQuestionGroup>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamQuestionReq {
  /** 題目類型 */
  part?: uniexam.QuestionOralPart;
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  base?: base.Base;
}

export interface ListUniExamQuestionResp {
  questions?: Array<uniexam.UniExamQuestion>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamRecordFilterOptionsReq {
  base?: base.Base;
}

export interface ListUniExamRecordFilterOptionsResp {
  team_exams?: Array<uniexam.TeamExam>;
  check_types?: Array<common.TeamExamCheckType>;
  status?: Array<uniexam.UniExamStatus>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamRecordReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  /** 過濾條件 */
  filter?: UniExamRecordFilter;
  base?: base.Base;
}

export interface ListUniExamRecordResp {
  uni_exams?: Array<uniexam.UniExam>;
  total?: number;
  page?: number;
  page_size?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniExamResultReq {
  base?: base.Base;
}

export interface ListUniExamResultResp {
  uni_exams?: Array<uniexam.UniExam>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUniexamScoreHistoryReq {
  /** 考試記錄ID */
  exam_id?: Int64;
  base?: base.Base;
}

export interface ListUniexamScoreHistoryResp {
  scores?: Array<uniexam.UniExamScoreRecord>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ListUserPaperExaminationReq {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  page_size?: number;
  base?: base.Base;
}

export interface ListUserPaperExaminationResp {
  paper_exams?: Array<common.PaperExam>;
  total?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface LoginByJwtReq {
  authorization: string;
  base?: base.Base;
}

export interface LoginByJwtResp {
  base_resp?: base.BaseResp;
}

export interface LoginReq {
  code?: string;
  state?: string;
  session_id?: string;
  base?: base.Base;
}

export interface LoginResp {
  base_resp?: base.BaseResp;
}

export interface MagicCheckReq {
  /** 內容 */
  content?: string;
  base?: base.Base;
}

export interface MagicCheckResp {
  /** 分數 */
  score?: Int64;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface MCreateOriginLibraryQuestionReq {
  questions?: Array<origin.CreateLibraryQuestion>;
  base?: base.Base;
}

export interface MCreateOriginLibraryQuestionResp {
  questions?: Array<origin.LibraryQuestion>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ParseUserPaperExaminationReq {
  /** 名單表格文件 tos 文件 */
  excel_id: string;
  base?: base.Base;
}

export interface ParseUserPaperExaminationResp {
  results?: Array<common.PaperExamParseResult>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface PushUniExamRecordReq {
  /** 考試記錄ID */
  id?: Int64;
  /** 推送類型 */
  check_type?: common.TeamExamCheckType;
  base?: base.Base;
}

export interface PushUniExamRecordResp {
  team_exam?: uniexam.TeamExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface RemindTeamExamReq {
  /** 考試記錄ID */
  id?: Int64;
  /** 推送內容 */
  content?: string;
  /** 推送時間 */
  timestamp?: Int64;
  base?: base.Base;
}

export interface RemindTeamExamResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface RemindTestReq {
  /** 消息ID */
  id?: Int64;
  base?: base.Base;
}

export interface RemindTestResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ReportLeaveScreenReq {
  paper_exam_id?: Int64;
  base?: base.Base;
}

export interface ReportLeaveScreenResp {
  leave_count?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ReportOriginExamLeaveReq {
  /** 考試記錄id */
  grade_exam_id?: Int64;
  base?: base.Base;
}

export interface ReportOriginExamLeaveResp {
  leave_count?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface ReportUniExamLeaveReq {
  /** 統一考試ID */
  uni_exam_id?: Int64;
  base?: base.Base;
}

export interface ReportUniExamLeaveResp {
  leave_count?: number;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SaveVideoChunkReq {
  /** 統一考試ID */
  uni_exam_id?: Int64;
  /** 視頻URI */
  video_uri?: string;
  base?: base.Base;
}

export interface SaveVideoChunkResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SearchUserReq {
  /** 關鍵詞 */
  keyword?: string;
  base?: base.Base;
}

export interface SearchUserResp {
  users?: Array<uniexam.User>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface StartMyPaperExamReq {
  base?: base.Base;
}

export interface StartMyPaperExamResp {
  paper_exam?: common.PaperExam;
  question_groups?: Array<common.PaperQuestionGroup>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface StartOriginExamReq {
  /** 團隊考試ID */
  team_exam_id?: Int64;
  base?: base.Base;
}

export interface StartOriginExamResp {
  /** 考試記錄 */
  grade_exam?: origin.GradeExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface StartUniExamReq {
  /** 團隊考試ID */
  team_exam_id?: Int64;
  /** 考試類型(1正式考試 2模擬考試 3口語刷題) */
  category?: uniexam.ExamCategory;
  base?: base.Base;
}

export interface StartUniExamResp {
  /** 開始的考試記錄 */
  uni_exam?: uniexam.UniExam;
  /** 下一道口語題 */
  oral_question?: uniexam.UniExamQuestion;
  /** 下一道聽力題 */
  listening_question?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SubmitMyPaperExamReq {
  paper_exam_id?: Int64;
  video_id?: string;
  force_submit?: boolean;
  base?: base.Base;
}

export interface SubmitMyPaperExamResp {
  paper_exam?: common.PaperExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SubmitOriginExamAnswerReq {
  /** 考試ID */
  grade_exam_id?: Int64;
  /** 題庫題目ID */
  library_question_id?: Int64;
  /** 用戶答案 */
  user_answer?: string;
  base?: base.Base;
}

export interface SubmitOriginExamAnswerResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SubmitOriginExamReq {
  /** 考試id */
  grade_exam_id?: Int64;
  /** 視頻id */
  video_id?: string;
  /** 是否強制提交 */
  force_submit?: boolean;
  base?: base.Base;
}

export interface SubmitOriginExamResp {
  grade_exam?: origin.GradeExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SubmitUniExamAnswerReq {
  /** 統一考試ID */
  uni_exam_id?: Int64;
  /** 用戶答案列表 */
  uni_exam_answers?: Array<uniexam.UniExamAnswerUpdateParams>;
  base?: base.Base;
}

export interface SubmitUniExamAnswerResp {
  /** 是否需要提交考試 */
  need_submit_exam?: boolean;
  /** 下一道口語題 */
  oral_question?: uniexam.UniExamQuestion;
  /** 下一道聽力題 */
  listening_question?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface SubmitUniExamReq {
  /** 統一考試ID */
  uni_exam_id?: Int64;
  /** 視頻URI */
  video_uri?: string;
  /** 是否強制提交 */
  force_submit?: boolean;
  base?: base.Base;
}

export interface SubmitUniExamResp {
  uni_exam?: uniexam.UniExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface TextToSpeechReq {
  text?: string;
  base?: base.Base;
}

export interface TextToSpeechResp {
  content?: string;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UniExamRecordFilter {
  /** 考試狀態列表 */
  status?: Array<uniexam.UniExamStatus>;
  /** 用戶ID */
  user_id?: Int64;
  /** 飛書姓名 */
  user_name?: string;
  /** 飛書郵箱 */
  user_email?: string;
  /** 1正式考試 2 模擬考試 3口語刷題 */
  categories?: Array<uniexam.ExamCategory>;
  /** 考試ID或外部id */
  exam_id?: string;
  /** 4人工批改 5機器批改 */
  check_types?: Array<common.TeamExamCheckType>;
  /** 測試ID列表 */
  test_ids?: Array<Int64>;
}

export interface UpdateOriginLibraryQuestionReq {
  question?: origin.UpdateLibraryQuestion;
  base?: base.Base;
}

export interface UpdateOriginLibraryQuestionResp {
  question?: origin.LibraryQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdatePaperReq {
  /** 試卷ID */
  id?: Int64;
  /** 試卷名稱 */
  name?: string;
  /** 試卷難度 */
  level?: common.PaperLevel;
  /** 試卷狀態 */
  status?: common.PaperStatus;
  base?: base.Base;
}

export interface UpdatePaperResp {
  paper?: common.Paper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateQuestionGroupReq {
  /** 試題組ID */
  id: Int64;
  /** 題幹 */
  content?: string;
  /** 關聯音頻 */
  audio_id?: string;
  /** 關聯圖片 */
  picture?: string;
  /** 題目列表 */
  questions?: Array<common.UpdatePaperQuestionParams>;
  base?: base.Base;
}

export interface UpdateQuestionGroupResp {
  question_group?: common.PaperQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateTeamExamTestReq {
  /** 測試ID */
  id?: Int64;
  /** 新增人員郵箱 */
  email?: uniexam.TeamExamTestEmail;
  /** 操作類型 1:新增 2:覆蓋 3:刪除 */
  operation?: uniexam.EmailOperation;
  base?: base.Base;
}

export interface UpdateTeamExamTestResp {
  /** 刪除失敗的用戶列表 */
  delete_failed_users?: Array<uniexam.User>;
  /** 配置不成功用戶列表(正在其他測試中) */
  test_conflict_users?: Array<uniexam.User>;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateTeamExamUserReq {
  /** 測試ID */
  team_exam_id?: Int64;
  /** 配置不成功用戶列表(正在其他測試中) */
  test_conflict_users?: Array<uniexam.User>;
  base?: base.Base;
}

export interface UpdateTeamExamUserResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateUniExamAnswerReq {
  /** 統一考試ID */
  uni_exam_id?: Int64;
  /** 統一考試題目ID */
  uni_exam_question_id?: Int64;
  /** 用戶答案 */
  user_answer?: string;
  base?: base.Base;
}

export interface UpdateUniExamAnswerResp {
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateUniExamPaperReq {
  /** 試卷ID */
  id?: Int64;
  /** 試卷名稱 */
  name?: string;
  /** 0 下線 1 上線 */
  status?: uniexam.OnlineStatus;
  /** 0 正式題 1 模擬題 */
  is_simulated?: uniexam.SimulationStatus;
  base?: base.Base;
}

export interface UpdateUniExamPaperResp {
  paper?: uniexam.UniExamListeningPaper;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateUniExamQuestionGroupReq {
  /** 題目組ID */
  id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 圖片URI */
  image_uri?: string;
  /** 題目列表 */
  questions?: Array<uniexam.UniExamQuestionUpdateParams>;
  base?: base.Base;
}

export interface UpdateUniExamQuestionGroupResp {
  question_group?: uniexam.UniExamQuestionGroup;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateUniExamQuestionReq {
  /** 題目ID */
  id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 圖片URI */
  image_uri?: string;
  /** 0 下線 1 上線 */
  status?: uniexam.OnlineStatus;
  /** 0 正式題 1 模擬題 */
  is_simulated?: uniexam.SimulationStatus;
  base?: base.Base;
}

export interface UpdateUniExamQuestionResp {
  question?: uniexam.UniExamQuestion;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}

export interface UpdateUserPaperExaminationReq {
  /** ID */
  id: Int64;
  /** 試卷難度 */
  level?: common.PaperLevel;
  /** 試卷 */
  paper_id?: Int64;
  base?: base.Base;
}

export interface UpdateUserPaperExaminationResp {
  paper_exam?: common.PaperExam;
  code?: number;
  message?: string;
  base_resp?: base.BaseResp;
}
/* eslint-enable */
