/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export enum GradeExamClientType {
  /** 小程序 */
  MiniProgram = 0,
  /** 網頁端 */
  Web = 1,
}

/** 原味考試
 ======================= 枚舉 ======================= */
export enum GradeExamStatus {
  /** 進行中 */
  InProgress = 0,
  /** 已完成 */
  Finished = 1,
  /** 待批改 */
  ToBeChecked = 3,
}

export enum GradeExamSyncType {
  /** 不同步 */
  NotSync = 0,
  /** 同步 */
  Sync = 1,
}

export enum GradeExamType {
  /** 定級 */
  Rank = 0,
  /** 單元 */
  Unit = 1,
  /** 新定級人工 */
  NewRankManual = 2,
  /** 新定級機改 */
  NewRankMachine = 3,
}

export enum LibraryQuestionPart {
  /** Part 1 */
  One = 1,
  /** Part 2 */
  Two = 2,
  /** Part 3 */
  Three = 3,
  /** Part 4 */
  Four = 4,
}

export enum LibraryQuestionStatus {
  /** 下線 */
  Offline = 0,
  /** 上線 */
  Online = 1,
}

export enum LibraryQuestionType {
  /** 詞彙 */
  Word = 0,
  /** 語法 */
  Grammar = 1,
  /** 聽力 */
  Listening = 2,
  /** 口語 */
  Speaking = 3,
  /** 新口語題 */
  NewSpeaking = 4,
}

export interface CreateLibraryQuestion {
  content?: string;
  options?: Array<string>;
  answer?: number;
  type?: LibraryQuestionType;
  level?: string;
  /** 音頻 */
  audio_uri?: string;
  /** 新口語題 - 部分 */
  part?: LibraryQuestionPart;
  /** 新口語題 - 圖片 */
  image_uri?: string;
}

export interface GradeExam {
  id?: Int64;
  /** 用戶ID */
  user_id?: Int64;
  /** 團隊考試ID */
  team_exam_id?: Int64;
  /** 等級 */
  level?: string;
  /** 年級 */
  grade?: string;
  /** 開始時間 */
  start_duration?: number;
  /** 客戶端類型 */
  client_type?: GradeExamClientType;
  /** 狀態 */
  status?: GradeExamStatus;
  /** 類型 */
  type?: GradeExamType;
  /** 同步apaas */
  sync_type?: GradeExamSyncType;
  /** 題目列表 */
  questions?: Array<GradeExamLibraryQuestion>;
  /** 創建時間 */
  created_at?: Int64;
}

export interface GradeExamLibraryQuestion {
  id?: Int64;
  /** 考試ID */
  grade_exam_id?: Int64;
  /** 題庫題目ID */
  library_question_id?: Int64;
  /** 輪次ID */
  round_id?: Int64;
  /** 用戶答案 */
  user_answer?: string;
  /** 題庫題目 */
  library_question?: LibraryQuestion;
}

export interface LibraryQuestion {
  id?: Int64;
  /** 題幹 */
  content?: string;
  /** 選項 */
  options?: string;
  /** 舊tos音頻 */
  audio?: string;
  /** imageX音頻 */
  audio_uri?: string;
  /** 答案 */
  answer?: number;
  /** 等級 */
  level?: string;
  /** 類型 */
  type?: LibraryQuestionType;
  /** 狀態 */
  status?: LibraryQuestionStatus;
  /** 新口語題 - 部分 */
  part?: LibraryQuestionPart;
  /** 新口語題 - 題幹音頻 */
  content_audio_uri?: string;
  /** 新口語題 - 圖片 */
  image_uri?: string;
  /** imageX音頻Url */
  audio_url?: string;
  /** 新口語題 - 題幹音頻Url */
  content_audio_url?: string;
  /** 新口語題 - 圖片Url */
  image_url?: string;
}

/** ======================= 響應模型 ======================= */
export interface Team {
  id?: Int64;
  /** 團隊名稱 */
  name?: string;
  /** 團隊頭像 */
  avatar?: string;
}

export interface TeamExam {
  id?: Int64;
  /** 團隊ID */
  team_id?: Int64;
  /** 批改類型 */
  check_type?: common.TeamExamCheckType;
  /** 狀態 */
  status?: common.TeamExamStatus;
  /** 團隊 */
  team?: Team;
  /** 用戶考試記錄 */
  user_team_exam?: UserTeamExam;
}

export interface UpdateLibraryQuestion {
  /** 題目ID */
  id?: Int64;
  /** 題幹 */
  content?: string;
  /** 選項 */
  options?: Array<string>;
  /** 答案 */
  answer?: number;
  /** 狀態 */
  status?: LibraryQuestionStatus;
  /** tos音頻 */
  audio?: string;
  /** 音頻 */
  audio_uri?: string;
  /** 新口語題 - 圖片 */
  image_uri?: string;
}

export interface UserTeamExam {
  id?: Int64;
  /** 用戶ID */
  user_id?: Int64;
  /** 團隊考試ID */
  team_exam_id?: Int64;
  /** 等級考試ID */
  grade_exam_id?: Int64;
}
/* eslint-enable */
