/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

/** 考試資格 */
export enum CertStatus {
  /** 未知 */
  Unknown = 0,
  /** 有效 */
  Valid = 1,
  /** 無效 */
  Invalid = 2,
  /** 無可用試題(口語試卷或聽力試題) */
  OutOfQuestions = 3,
}

export enum ConfirmUniExamType {
  /** 未知 */
  Unknown = 0,
  /** 確認 */
  Confirm = 1,
  /** 保存 */
  Save = 2,
  /** 定時確認 */
  ConfirmByCron = 3,
}

export enum DetailLevel {
  /** 未知 */
  Unknown = 0,
  /** A1.1 */
  A1_1 = 1,
  /** A1.2 */
  A1_2 = 2,
  /** A2.1 */
  A2_1 = 3,
  /** A2.2 */
  A2_2 = 4,
  /** B1.1 */
  B1_1 = 5,
  /** B1.2 */
  B1_2 = 6,
  /** B2.1 */
  B2_1 = 7,
  /** B2.2 */
  B2_2 = 8,
  /** C1.1 */
  C1_1 = 9,
  /** C1.2 */
  C1_2 = 10,
  /** C2 */
  C2 = 11,
}

export enum EmailOperation {
  /** 未知 */
  Unknown = 0,
  /** 新增 */
  Create = 1,
  /** 覆蓋 */
  Update = 2,
  /** 刪除 */
  Delete = 3,
}

export enum ExamCategory {
  /** 未知 */
  Unknown = 0,
  /** 正式考試 */
  Formal = 1,
  /** 模擬考試 */
  Simulation = 2,
  /** 口語刷題 */
  OralPractice = 3,
}

export enum GeneralLevel {
  /** 未知 */
  Unknown = 0,
  /** A2 */
  A2 = 1,
  /** B1 */
  B1 = 2,
  /** B2 */
  B2 = 3,
  /** C1 */
  C1 = 4,
}

/** 刪除狀態 */
export enum IsDeleted {
  /** 否 */
  No = 0,
  /** 是 */
  Yes = 1,
}

/** 統一考試
 ======================= 枚舉 =======================
 在線狀態 */
export enum OnlineStatus {
  /** 下線 */
  Offline = 0,
  /** 上線 */
  Online = 1,
}

export enum PracticeStatus {
  /** 否 */
  No = 0,
  /** 是 */
  Yes = 1,
}

/** 題目批改狀態 */
export enum QuestionCheckStatus {
  /** 未批改 */
  NotChecked = 0,
  /** ASR成功 */
  AsrSuccess = 1,
  /** ASR失敗 */
  AsrFailed = 2,
  /** 批改成功 */
  CheckSuccess = 3,
  /** 批改失敗 */
  CheckFailed = 4,
}

export enum QuestionGroupCategory {
  /** 未知 */
  Unknown = 0,
  /** 長短聽力 */
  ShortLong = 1,
  /** n選n */
  NFromN = 2,
}

/** 口語題part標識 */
export enum QuestionOralPart {
  /** Part 1 */
  One = 1,
  /** Part 2 */
  Two = 2,
  /** Part 3 */
  Three = 3,
  /** Part 4 */
  Four = 4,
}

export enum RobotMessageStatus {
  /** 待推送 */
  Pending = 0,
  /** 推送中 */
  Sending = 1,
  /** 推送成功 */
  Success = 2,
  /** 推送失敗 */
  Failed = 3,
}

export enum RobotMessageType {
  /** 團隊學習提醒 */
  TeamStudy = 0,
  /** 團隊測試提醒 */
  DeprecatedTeamExam = 1,
  /** 飛書羣組活動通知 */
  FeishuGroupActivity = 2,
  /** 統一考試提醒 */
  UniExamRemind = 3,
}

/** 模擬考試 */
export enum SimulationStatus {
  /** 否 */
  No = 0,
  /** 是 */
  Yes = 1,
}

export enum TeamExamConfigurationType {
  /** 基於篩選 */
  Filter = 0,
  /** 基於郵箱 */
  Email = 1,
}

export enum TeamExamUserStatus {
  /** 未知 */
  Unknown = 0,
  /** 配置成功 */
  Success = 1,
  /** 配置失敗 */
  Failure = 2,
}

/** 用戶考試狀態 */
export enum UniExamStatus {
  /** 進行中 */
  InProgress = 0,
  /** 已完成 */
  Finished = 1,
  /** 待複覈 */
  ToBeReviewed = 2,
  /** 待批改 */
  ToBeChecked = 3,
  /** 待加試 */
  ToBeAdditional = 4,
  /** 加試進行中 */
  AdditionInProgress = 5,
  /** 已退出 */
  Exited = 6,
  /** 強制退出 */
  ForcedExit = 7,
}

export enum UserType {
  /** 未知 */
  Unknown = 0,
  /** 飛書用戶 */
  Lark = 1,
  /** 外部用戶 */
  External = 2,
}

export interface OralCheckTaskResult {
  /** 任務ID */
  task_id?: string;
  /** "pending", "completed", "failed" */
  status?: string;
  /** 音頻URI */
  audio_uri?: string;
  /** 用戶錄音轉文本 */
  asr_text?: string;
  /** gpt對文本的批改結果 */
  gpt_check_result?: string;
  /** 錯誤信息 */
  error?: string;
  /** 更新時間 */
  updated_at?: Int64;
  /** 創建時間 */
  created_at?: Int64;
}

export interface RobotMessage {
  /** 消息ID */
  id?: Int64;
  /** 消息內容 */
  payload?: string;
  /** 推送時間 */
  push_time?: Int64;
  /** 消息類型 */
  type?: RobotMessageType;
  /** 消息狀態 */
  status?: RobotMessageStatus;
  /** 關聯 ID，與 RobotMessageType 對應 */
  rid?: Int64;
  /** 推送記錄 */
  schedule_records?: Array<ScheduleRecord>;
}

export interface ScheduleRecord {
  /** 記錄ID */
  id?: Int64;
  /** 機器人消息ID */
  robot_message_id?: Int64;
  /** 推送結果 */
  schedule_result?: string;
  /** 推送用戶 */
  schedule_users?: string;
}

/** ======================= 響應模型 ======================= */
export interface Team {
  id?: Int64;
  /** 團隊名稱 */
  name?: string;
  /** 團隊頭像 */
  avatar?: string;
  /** 最新團隊考試 */
  latest_team_exam?: TeamExam;
  /** 團隊考試列表 */
  team_exams?: Array<TeamExam>;
}

export interface TeamExam {
  id?: Int64;
  /** 測試名稱 */
  name?: string;
  /** 團隊ID */
  team_id?: Int64;
  /** 批改類型 0未知狀態 4人工批改 5機器批改 */
  check_type?: common.TeamExamCheckType;
  /** 狀態 0進行中 1未開始 2已完成 */
  status?: common.TeamExamStatus;
  /** 開始時間 */
  begin_at?: Int64;
  /** 結束時間 */
  end_at?: Int64;
  /** 考試資格過濾條件 */
  filter?: TeamExamTestFilter;
  /** 類型 0測試 1團隊考試(歷史數據) */
  category?: common.TeamExamCategory;
  /** 團隊 */
  team?: Team;
  /** 我的考試記錄 */
  my_uni_exam?: UniExam;
  /** 參與團隊考試的用戶考試列表(最大100條) */
  uni_exams?: Array<UniExam>;
  /** 參與團隊考試的用戶考試列表總數 */
  uni_exams_total?: Int64;
  /** 未完成考試的用戶列表(最大100條) */
  unfinished_users?: Array<User>;
  /** 未完成考試的用戶列表總數 */
  unfinished_users_total?: Int64;
  /** 創建時間 */
  created_at?: Int64;
}

export interface TeamExamTestEmail {
  /** 郵箱列表 */
  emails?: Array<string>;
  /** 郵箱excel文件URL */
  file_url?: string;
}

export interface TeamExamTestFilter {
  /** 英語分組 */
  english_group?: Array<string>;
  /** 員工角色 */
  role?: Array<string>;
  /** 歷史最高成績 */
  highest_score?: Array<string>;
  /** 是否有非中下屬 */
  has_overseas_subordinate?: boolean;
}

export interface UniExam {
  id?: Int64;
  /** 用戶ID */
  user_id?: Int64;
  /** 團隊考試ID */
  team_exam_id?: Int64;
  /** 聽力考試ID */
  uni_exam_listening_paper_id?: Int64;
  /** 聽力第一次加試 ID */
  uni_exam_listening_paper_plus_one_id?: Int64;
  /** 聽力第二次加試 ID */
  uni_exam_listening_paper_plus_two_id?: Int64;
  /** 口語題1 */
  uniexam_oral_question_one_id?: Int64;
  /** 口語題2 */
  uniexam_oral_question_two_id?: Int64;
  /** 口語題3 */
  uniexam_oral_question_three_id?: Int64;
  /** 口語題4 */
  uniexam_oral_question_four_id?: Int64;
  /** 視頻地址, 廢棄,改爲視頻會議列表 */
  video_uri?: string;
  /** 離開次數 */
  leave_count?: number;
  /** 狀態 */
  status?: UniExamStatus;
  /** 聽力考試等級 */
  listening_paper_level?: GeneralLevel;
  /** 聽力考試得分 */
  listening_score?: number;
  /** 聽力定級 (A/B/C1.1/2) */
  listening_level?: DetailLevel;
  /** 口語得分 */
  oral_score?: number;
  /** 口語定級 (A/B/C1.1/2) */
  oral_level?: DetailLevel;
  /** 最終定級 (A/B/C1.1/2) */
  final_level?: DetailLevel;
  /** 0 正式 1 模擬考試 */
  is_simulated?: SimulationStatus;
  /** 同步到外部的表記錄id */
  apaas_english_grade_id?: Int64;
  /** 用戶信息 */
  user?: User;
  /** 團隊信息 */
  team?: Team;
  /** 考試類型 1 正式考試 2 模擬考試 3 口語刷題 */
  category?: ExamCategory;
  /** 類型 4新版定級[人工] 5新版定級[機改] */
  check_type?: common.TeamExamCheckType;
  /** 團隊考試信息 */
  team_exam?: TeamExam;
  /** 視頻地址列表 */
  video_uri_list?: Array<string>;
  /** 視頻地址列表 */
  video_url_list?: Array<string>;
  /** 口語題目列表 */
  oral_questions?: Array<UniExamQuestion>;
  /** 答案列表 */
  answers?: Array<UniExamAnswer>;
  /** 聽力試卷列表 */
  listening_papers?: Array<UniExamListeningPaper>;
  /** 視頻URL，廢棄 */
  video_url?: string;
  /** 外部展示ID */
  external_id?: string;
  /** 更新時間 */
  updated_at?: Int64;
  /** 創建時間 */
  created_at?: Int64;
}

export interface UniExamAnswer {
  id?: Int64;
  /** 用戶id */
  user_id?: Int64;
  /** 考試記錄id */
  uni_exam_id?: Int64;
  /** 試卷id */
  uniexam_listening_paper_id?: Int64;
  /** 試題id */
  uniexam_question_id?: Int64;
  /** 試題選項id */
  uniexam_question_option_id?: Int64;
  /** 錄音內容 */
  audio_uri?: string;
  /** 口語批改記錄 */
  question_check?: UniExamQuestionCheck;
  /** 錄音URL */
  audio_url?: string;
  /** 更新時間 */
  updated_at?: Int64;
  /** 創建時間 */
  created_at?: Int64;
}

export interface UniExamAnswerUpdateParams {
  /** 試題id */
  uniexam_question_id?: Int64;
  /** 選項ID(聽力回答) */
  uni_exam_question_option_id?: Int64;
  /** 錄音uri(口語回答) */
  audio_uri?: string;
}

export interface UniExamListeningPaper {
  /** 試卷ID */
  id?: Int64;
  /** 試卷名稱 */
  name?: string;
  /** 試卷等級 */
  level?: GeneralLevel;
  /** 試卷狀態 */
  status?: OnlineStatus;
  /** 是否模擬試卷 */
  is_simulated?: SimulationStatus;
  /** 題目組列表 */
  question_groups?: Array<UniExamQuestionGroup>;
}

export interface UniExamQuestion {
  id?: Int64;
  /** 題目組id */
  uniexam_question_group_id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻 */
  audio_uri?: string;
  /** 圖片 */
  image_uri?: string;
  /** 口語題 part 1|2|3|4 */
  oral_part?: QuestionOralPart;
  /** 0 下線 1 上線 */
  status?: OnlineStatus;
  /** 0 正式題 1 模擬題 */
  is_simulated?: SimulationStatus;
  /** 音頻URL */
  audio_url?: string;
  /** 圖片URL */
  picture_url?: string;
  /** 選項列表 */
  options?: Array<UniExamQuestionOption>;
}

export interface UniExamQuestionCheck {
  id?: Int64;
  /** 試題id */
  uniexam_question_id?: Int64;
  /** 回答id */
  uniexam_answer_id?: Int64;
  /** 批改狀態 */
  status?: QuestionCheckStatus;
  /** 用戶錄音轉文本 */
  asr_text?: string;
  /** gpt對文本的批改結果 */
  gpt_check_result?: string;
  /** CEFR等級 */
  cefr_level?: DetailLevel;
  /** 更新時間 */
  updated_at?: Int64;
  /** 創建時間 */
  created_at?: Int64;
}

export interface UniExamQuestionCreateNFNParams {
  /** 題目ID，傳空爲創建，否則爲更新 */
  question_id?: Int64;
  /** 題目組ID */
  uni_exam_question_group_id?: Int64;
  /** 題目 */
  content?: string;
  /** 關聯音頻 */
  audio_uri?: string;
  /** 關聯圖片 */
  image_uri?: string;
  /** 選項內容 */
  option_content?: string;
}

export interface UniExamQuestionCreateParams {
  /** 題目組ID */
  uni_exam_question_group_id?: Int64;
  /** 題目 */
  content?: string;
  /** 關聯音頻 */
  audio_uri?: string;
  /** 關聯圖片 */
  image_uri?: string;
  /** 選項列表 */
  options?: Array<UniExamQuestionOptionCreateParams>;
}

export interface UniExamQuestionGroup {
  id?: Int64;
  /** 試卷id */
  uniexam_listening_paper_id?: Int64;
  /** 題幹 */
  content?: string;
  /** 音頻 */
  audio_uri?: string;
  /** 圖片 */
  image_uri?: string;
  /** 題目組類型 */
  category?: QuestionGroupCategory;
  /** 選項內容列表 */
  option_contents?: Array<string>;
  /** 音頻URL */
  audio_url?: string;
  /** 圖片URL */
  picture_url?: string;
  /** 題目列表 */
  questions?: Array<UniExamQuestion>;
}

export interface UniExamQuestionOption {
  id?: Int64;
  /** 題目ID */
  uni_exam_question_id?: Int64;
  /** 選項內容 */
  content?: string;
  /** 選項正確性 */
  is_correct?: common.QuestionOptionCorrectStatus;
}

export interface UniExamQuestionOptionCreateParams {
  /** 題目ID */
  uni_exam_question_id?: Int64;
  /** 選項內容 */
  content?: string;
  /** 選項正確性 */
  is_correct?: common.QuestionOptionCorrectStatus;
}

export interface UniExamQuestionOptionUpdateParams {
  /** 選項ID */
  id?: Int64;
  /** 題目ID */
  uni_exam_question_id?: Int64;
  /** 選項內容 */
  content?: string;
  /** 選項正確性 */
  is_correct?: common.QuestionOptionCorrectStatus;
  /** 標記爲刪除的選項 */
  mark_as_delete?: boolean;
}

export interface UniExamQuestionUpdateParams {
  /** 題目ID */
  id?: Int64;
  /** 題目組ID */
  uni_exam_question_group_id?: Int64;
  /** 題目 */
  content?: string;
  /** 關聯音頻 */
  audio_uri?: string;
  /** 關聯圖片 */
  image_uri?: string;
  /** 選項列表 */
  options?: Array<UniExamQuestionOptionUpdateParams>;
  /** 標記爲刪除的題目 */
  mark_as_delete?: boolean;
}

export interface UniExamScoreRecord {
  /** 聽力考試等級 */
  listening_paper_level?: GeneralLevel;
  /** 聽力考試得分 */
  listening_score?: number;
  /** 聽力定級 (A/B/C1.1/2) */
  listening_level?: DetailLevel;
  /** 口語得分 */
  oral_score?: number;
  /** 口語定級 (A/B/C1.1/2) */
  oral_level?: DetailLevel;
  /** 最終定級 (A/B/C1.1/2) */
  final_level?: DetailLevel;
  /** 創建時間 */
  created_at?: Int64;
  /** 統一考試ID */
  exam_id?: Int64;
}

export interface User {
  id?: Int64;
  /** 用戶名 */
  name?: string;
  /** 頭像 */
  avatar?: string;
  /** 郵箱 */
  email?: string;
  /** 測試ID */
  test_id?: Int64;
  /** 測試名稱 */
  test_name?: string;
  /** 統一考試ID */
  exam_id?: Int64;
}
/* eslint-enable */
