/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';

export type Int64 = string | number;

export interface ComponentMeta {
  /** component 跨空間的唯一標識。自定義組件可能是組件作者自己確定的。可讀。 */
  type: string;
  /** 組件所屬的分組，如 ChatModel, Prompt, Retriever 等。可讀。 */
  group: string;
  /** 一個 Group 對應一個 interface name，決定是否可以進入特定的 slot。可讀。 */
  interface_name: string;
  /** Group 決定了這個組件能否進入編排，還是隻能作爲 slot 配置。true 則可以進入編排，可以作爲 passthrough 節點的上游 */
  is_composable: boolean;
  definition: Definition;
  /** 除了上面的 interface name 之外，這個組件還可以用作哪些 interface，從而可以進入對應的 Slot */
  assignable_to?: Array<string>;
}

export interface Definition {
  info: Info;
  /** 前端框架用的，服務端不感知內容 */
  meta?: string;
  slots?: Array<Slot>;
  /** 如果一個組件，只能作爲配置進入 slot，此字段爲空 */
  input?: TypeMeta;
  /** 如果一個組件，只能作爲配置進入 slot，此字段爲空 */
  output?: TypeMeta;
  /** 裏面的字段都展開爲基本類型，直接在頁面上寫。如果 Config 中某個字段是嵌套的 Object，那個 Object 也不應該是 Component，否則應該進入 slot，而不是 config */
  config?: TypeSchema;
}

export interface Doc {
  name: string;
  link: string;
}

export interface Info {
  name: string;
  icon?: string;
  description?: string;
  docs?: Array<Doc>;
}

export interface ListComponentsRequest {
  'FlowDevops-Agw-UserId'?: string;
  space_id: string;
  base?: base.Base;
}

export interface ListComponentsResponse {
  /** key 是 group */
  official_components?: Record<string, Array<ComponentMeta>>;
  /** key 是 group */
  custom_components?: Record<string, Array<ComponentMeta>>;
  base_resp?: base.BaseResp;
}

export interface Option {
  label: string;
  /** JSON 序列化的結果 */
  value: string;
}

export interface OptionEnum {
  ode?: string;
  options?: Array<Option>;
}

export interface Slot {
  /** 可讀 */
  slot_name: string;
  /** 這個 slot 接受的類型，一般是個接口定義，可讀 */
  interface_name: string;
  required?: boolean;
  /** 數組類型的 slot */
  multiple?: boolean;
}

export interface TypeMeta {
  /** input 或 output 的類型枚舉，數字 */
  type_id: string;
  /** 對一個結構體的 schema 描述，可以是 input、output、config，或者裏面的某個字段 */
  schema: TypeSchema;
  /** 可讀 */
  type_name?: string;
}

export interface TypeSchema {
  /** 可讀 */
  type: string;
  /** 當類型爲數組時，有值，代表數組中元素的 schema */
  items?: TypeSchema;
  /** 當類型爲 object 時，有值，key 爲字段名稱，value 爲字段的 schema */
  properties?: Record<string, TypeSchema>;
  /** 當類型爲 object 時，有值，數組元素爲字段的 schema */
  property_list?: Array<TypeSchema>;
  name?: string;
  title?: string;
  description?: string;
  /** JSON 序列化的結果 */
  default_value?: string;
  hidden?: boolean;
  read_only?: boolean;
  required?: boolean;
  option_enum?: OptionEnum;
  /** 前端需要的定製信息，服務端不感知 */
  style_meta?: string;
}
/* eslint-enable */
