/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';

export type Int64 = string | number;

export enum ComponentCreateStatus {
  Undefined = 0,
  /** 創建中 */
  Creating = 1,
  /** 創建成功 */
  CreateSuccess = 2,
  /** 創建失敗 */
  CreateFailed = 3,
}

export enum ComponentLanguage {
  Undefined = 0,
  Go = 1,
}

export enum ComponentReleaseStatus {
  Undefined = 0,
  /** 發佈中 */
  InRelease = 1,
  /** 發佈成功 */
  ReleaseSuccess = 2,
  /** 發佈失敗 */
  ReleaseFailed = 3,
}

/** 組件類型枚舉 */
export enum ComponentType {
  Undefined = 0,
  ChatModel = 1,
  ToolAgent = 2,
}

export interface ComponentTemplateInfo {
  /** 模板名稱 */
  name?: string;
  /** 模板描述 */
  description?: string;
  /** 組件類型 */
  type?: ComponentType;
  /** 模板語言 */
  language?: ComponentLanguage;
}

export interface CreateCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  space_id: Int64;
  /** 組件信息 */
  component?: CustomComponent;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface CreateCustomComponentResponse {
  component_id: Int64;
  base_resp?: base.BaseResp;
}

export interface CustomComponent {
  /** Component ID */
  id?: Int64;
  /** 唯一標識 */
  component_key?: string;
  /** Component名稱 */
  display_name?: string;
  /** Component描述 */
  description?: string;
  /** Component類型 */
  component_type?: ComponentType;
  /** 創建者ID */
  creator_id?: Int64;
  /** 創建時間 */
  create_tsms?: Int64;
  /** 更新時間 */
  update_tsms?: Int64;
  /** 狀態 */
  status?: ComponentCreateStatus;
  /** 版本 */
  version?: string;
  /** 組件實現語言 */
  language?: ComponentLanguage;
  /** 組件圖標 */
  icon?: Icon;
  /** 組件倉庫地址 */
  repo?: string;
  /** 組件Cloud IDE Workspace信息 */
  workspace_info?: WorkspaceInfo;
}

export interface CustomComponentReleaseRecord {
  /** Component Release ID */
  release_id?: Int64;
  /** Component ID */
  component_id?: Int64;
  /** 組件版本 */
  component_version?: string;
  /** 組件版本對應的codebase Tag */
  tag?: string;
  /** 版本描述 */
  description?: string;
  /** 發佈人 */
  creator_id?: Int64;
  /** 創建時間 */
  create_tsms?: Int64;
  /** 更新時間 */
  update_tsms?: Int64;
  /** 版本發佈狀態 */
  status?: ComponentReleaseStatus;
  /** 錯誤信息 */
  err_info?: ErrInfo;
}

export interface DeleteCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface DeleteCustomComponentResponse {
  base_resp?: base.BaseResp;
}

export interface ErrInfo {
  /** 錯誤碼 */
  code?: number;
  /** 錯誤信息 */
  message?: string;
  log_id?: string;
}

export interface GetCustomComponentReleaseRecordRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  release_id: Int64;
  base?: base.Base;
}

export interface GetCustomComponentReleaseRecordResponse {
  /** 組件版本發佈信息 */
  release_record?: CustomComponentReleaseRecord;
  base_resp?: base.BaseResp;
}

export interface GetCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  base?: base.Base;
}

export interface GetCustomComponentResponse {
  /** 組件信息 */
  component?: CustomComponent;
  base_resp?: base.BaseResp;
}

export interface Icon {
  /** frontend -> backend */
  uri?: string;
  /** backend -> frontend */
  url?: string;
}

export interface IDELaunchRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  'X-Jwt-Token': string;
  base?: base.Base;
}

export interface IDELaunchResponse {
  /** 組件Cloud IDE Workspace信息 */
  workspace_info?: WorkspaceInfo;
  /** 是否有cloud ide權限 */
  has_auth?: boolean;
  base_resp?: base.BaseResp;
}

export interface IsComponentKeyValidRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** 組件標識 */
  component_key: string;
  base?: base.Base;
}

export interface IsComponentKeyValidResponse {
  /** component_key是否有效 */
  is_valid?: boolean;
  base_resp?: base.BaseResp;
}

export interface ListComponentTemplateInfoRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  base?: base.Base;
}

export interface ListComponentTemplateInfoResponse {
  /** 組件模板信息 */
  component_templates?: Array<ComponentTemplateInfo>;
  base_resp?: base.BaseResp;
}

export interface ListCustomComponentReleaseRecordRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  page?: Int64;
  page_size?: Int64;
  base?: base.Base;
}

export interface ListCustomComponentReleaseRecordResponse {
  component_release_records?: Array<CustomComponentReleaseRecord>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ListCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  page?: Int64;
  page_size?: Int64;
  /** 模糊搜索
name/key模糊匹配 */
  key_word?: string;
  /** 創建者ID */
  creator_i_d?: Int64;
  base?: base.Base;
}

export interface ListCustomComponentResponse {
  /** 組件信息 */
  components?: Array<CustomComponent>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ListSupportComponentTypeRequest {
  'FlowDevops-Agw-UserId'?: string;
  space_id: Int64;
  page?: Int64;
  page_size?: Int64;
  base?: base.Base;
}

export interface ListSupportComponentTypeResponse {
  /** 組件類型 */
  component_types?: Array<ComponentType>;
  total?: Int64;
  base_resp?: base.BaseResp;
}

export interface ReleaseCustomComponentRequest {
  /** Component ID */
  component_id: Int64;
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** 組件版本發佈信息 */
  component_release?: CustomComponentReleaseRecord;
  'X-Jwt-Token'?: string;
  base?: base.Base;
}

export interface ReleaseCustomComponentResponse {
  release_id: Int64;
  base_resp?: base.BaseResp;
}

export interface UpdateCustomComponentRequest {
  'FlowDevops-Agw-UserId'?: string;
  /** 空間ID */
  space_id: Int64;
  /** Component ID */
  component_id: Int64;
  component?: CustomComponent;
  base?: base.Base;
}

export interface UpdateCustomComponentResponse {
  base_resp?: base.BaseResp;
}

export interface WorkspaceInfo {
  /** cloudide workspace id */
  workspace_id?: string;
  /** cloudide workspace url */
  workspace_url?: string;
  /** workspace 登陸狀態 */
  workspace_launched?: boolean;
}
/* eslint-enable */
