/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_evaluation_entity from './flow_devops_evaluation_entity';
import * as flow_devops_evaluation_object from './flow_devops_evaluation_object';

export type Int64 = string | number;

export enum AppClientEnvType {
  Undefined = 0,
  AllEnv = 1,
  /** 返回PPE和Online的client */
  PPEAndOnline = 2,
  /** 僅返回BOE Client */
  BOEOnly = 3,
}

export enum AppClientType {
  Undefined = 0,
  TCE = 1,
}

export enum AppType {
  Undefined = 0,
  TCE = 1,
  CozeBot = 2,
}

export enum AppV2Type {
  Undefined = 0,
  PSM = 1,
  FullCodeFlow = 2,
}

export interface App {
  id?: string;
  spaceID?: string;
  /** 應用類型, 如 TCE */
  type?: AppType;
  /** 空間內唯一.對於 TCE 類型的app，其 uid 爲 psm；對於 coze_bot 類型的 app，其 uid 爲 BotID */
  uid?: string;
  /** TCE 類型的應用默認爲 PSM, 可修改；CozeBot 類型的不可修改 */
  name?: string;
  description?: string;
  ownerIDs?: Array<string>;
  /** 頭像，當前僅 cozeBot 展示使用 */
  iconURL?: string;
  /** 創建人 */
  createdBy?: string;
  /** 更新人 */
  updatedBy?: string;
  /** 創建時間 */
  createdAt?: string;
  /** 更新時間 */
  updatedAt?: string;
}

/** AppClient 表示訪問該應用數據的客戶端, 一般爲一個使用了 FornaxSDK 的 TCE 服務. */
export interface AppClient {
  id?: Int64;
  spaceID?: Int64;
  appID?: Int64;
  /** TCE 類型的 client, 其值爲 PSM */
  appUID?: string;
  /** 泳道env */
  env?: string;
  /** cluster */
  cluster?: string;
  /** TCE 類型的 client, 其值爲 ${PSM}:${env}:${cluster} */
  identity?: string;
  labels?: Record<string, string>;
  /** 創建人 */
  createdBy?: string;
  /** 創建時間 */
  createdAt?: Int64;
  /** 更新時間 */
  updatedAt?: Int64;
}

export interface AppEvaluationInfo {
  callbackType: flow_devops_evaluation_entity.CallbackType;
  rpcCallbackObjectParams?: flow_devops_evaluation_object.RPCCallbackObjectParams;
  faasCallbackObjectParams?: flow_devops_evaluation_object.FaasCallbackObjectParams;
}

export interface AppV2 {
  id?: string;
  spaceID?: string;
  type?: AppV2Type;
  entityID?: string;
  name?: string;
  description?: string;
  version?: string;
  psm?: string;
  regions?: Array<string>;
  appEvaluationInfo?: AppEvaluationInfo;
  /** 創建人 */
  createdBy?: string;
  /** 更新人 */
  updatedBy?: string;
  /** 創建時間 */
  createdAt?: string;
  /** 更新時間 */
  updatedAt?: string;
}

/** ClientEvaluationSetting 客戶端的評測配置 */
export interface ClientEvaluationSetting {
  /** 是否寫入數據集 (默認開啓) */
  enableWriteToDataSet: boolean;
  /** 數據集ID */
  dataSetID?: string;
  /** 採樣率 */
  samplingRate?: number;
  /** 採樣上限 */
  samplingLimit?: string;
  /** 採樣開始時間 */
  fromMillis?: string;
  /** 採樣結束時間 */
  toMillis?: string;
}
/* eslint-enable */
