/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ByteTreeNodeResourceProvider {
  TCE = 1,
  TCC = 2,
  Bernard = 3,
}

export enum DataImportMode {
  Undefined = 0,
  /** 追加 */
  Append = 1,
  /** 覆蓋 */
  Overwrite = 2,
}

export enum DataSourceType {
  Undefined = 0,
  TOS = 1,
}

export enum Family {
  Undefined = 0,
  GPT = 1,
  Seed = 2,
  Gemini = 3,
  Claude = 4,
  Ernie = 5,
  Baichuan = 6,
  Qwen = 7,
  GLM = 8,
  SkyLark = 9,
  Moonshot = 10,
  Minimax = 11,
  Doubao = 12,
  Baichuan2 = 13,
  DeepSeekV2 = 14,
  DeepSeekCoderV2 = 15,
  DeepseekCoder = 16,
  InternLM2_5 = 17,
  Qwen2 = 18,
  Qwen2_5 = 19,
  Qwen2_5_Coder = 20,
  MiniCPM = 21,
  MiniCPM3 = 22,
  ChatGLM3 = 23,
  Mistral = 24,
  Gemma = 25,
  Gemma2 = 26,
  InternVL2 = 27,
  InternVL2_5 = 28,
  DeepSeekV3 = 29,
  DeepSeekR1 = 30,
}

export enum IDC {
  HL = 1,
  LF = 2,
  LQ = 3,
  YG = 4,
  GL = 5,
  MALIVA = 101,
  SG1 = 201,
  MY = 202,
  MY2 = 203,
  MYCISB = 204,
}

export enum MerlinFramework {
  LLMServerPublic = 1,
  Laplace = 2,
  /** 電商團隊專用協議，詳見  */
  Mixinfer = 3,
}

export enum MerlinLLMInterface {
  MatxInference = 1,
}

export enum MerlinQuotaPoolType {
  /** 穩定資源 */
  Default = 0,
  /** 潮汐資源 */
  Hybrid = 1,
  /** 常混資源 */
  HybridShare = 2,
  /** 第三方資源ali */
  ALI = 3,
  /** 第三方資源hw */
  HW = 4,
  /** hw arm */
  HWARM = 5,
  /** 彈性售賣資源，隨時可能被搶佔 */
  Spot = 6,
  /** 可搶佔的穩定資源 */
  Preemptible = 20,
}

export enum ModelFilterKey {
  ModelType = 1,
  ModelUserRight = 2,
  ModelFeature = 3,
  ModelFunction = 4,
  ModelScenario = 5,
  Custom = 20,
}

export enum ModelParamType {
  Unknown = 0,
  Float = 1,
  Int = 2,
  Boolean = 3,
  String = 4,
}

export enum ModelStatus {
  Undefined = 0,
  /** 健康可用 */
  Available = 1,
  /** 部署中 */
  Deploying = 2,
  /** 不可用（已下線） */
  Unavailable = 3,
  /** 下線中 */
  Offlining = 4,
}

export enum Provider {
  /** GPT OpenAPI平臺 */
  GPTOpenAPI = 1,
  /** 火山方舟 */
  Maas = 2,
  /** 暫時特指seed從bot_engine接入 */
  BotEngine = 3,
  /** merlin平臺 */
  Merlin = 4,
  /** merlin-seed平臺 */
  MerlinSeed = 5,
}

export enum ProviderAccountType {
  AKSK = 1,
  APIKey = 2,
}

export enum Region {
  CN = 1,
  SG = 2,
  US = 3,
}

export enum RuntimeCustomParamType {
  Unknown = 0,
  StringList = 1,
  IntList = 2,
  FloatList = 3,
  String = 4,
  Int = 5,
  Float = 6,
  Bool = 7,
}

export enum RuntimeHookType {
  Unknown = 0,
  MsgPreHook = 1,
}

export enum SftTaskBaseModelType {
  Foundation = 0,
  Custom = 1,
}

export enum SftTaskErrCode {
  Default = 0,
  /** 前2位代表錯誤分類，後4位代表具體錯誤
10 通用錯誤 */
  InternalErr = 100000,
  /** 訓練集上傳到平臺方時出錯 */
  TrainingSetUploadedErr = 100001,
  /** 在平臺方創建精調任務出錯 */
  CreateProviderSftTaskErr = 100002,
  /** 20 Merlin任務實例整體報錯 */
  MerlinTaskInternalError = 200000,
  /** gpu cpu mem 套餐配比錯誤 */
  MerlinGpuCpuMemRatioBad = 200001,
  /** 21 Merlin訓練腳本主動上報的錯誤 */
  MerlinReportedInternalErr = 210000,
  MerlinOOM = 210001,
  /** 沒找到模型訓練產物 */
  MerlinNoModelGenerated = 210002,
  /** 30 火山方舟任務失敗
方舟通用錯誤 */
  MaaSInternalErr = 300000,
  /** 驗證集比例分割異常 */
  MaaSValidationSetSplitErr = 300001,
  /** 訓練數據格式不符合預期 */
  MaaSTrainingSetNoValid = 300002,
  /** 業務方的火山賬號沒有開通模型服務 */
  MaaSAccountModelServiceIsNotActivated = 300003,
  /** 缺少必要的請求參數。請確認請求參數後重試。 */
  MaaSRequiredParamMissing = 300004,
  /** 請求參數值不合法。請檢查參數值的正確性後重試。 */
  MaaSRequestParamInvalid = 300005,
  /** 對象的標籤存在重複Key */
  MaaSDuplicateTags = 300006,
  /** 無法同時上傳驗證集和設置訓練集取樣爲驗證集百分比，不支持該操作 */
  MaaSNotSupportedToConfigureValidationSetAndPercentage = 300007,
  /** 您沒有權限訪問基礎模型的配置，不支持該操作 */
  MaaSNotPermittedToAccessModel = 300008,
  /** 模型不支持該訓練方法，不支持該操作 */
  MaaSModelNotSupportTheTrainingMethod = 300009,
  /** 基礎模型的版本不支持該訓練方法，不支持該操作 */
  MaaSFoundationModelNotSupportTheTrainingMethod = 300010,
  /** 您的賬單已逾期，不支持該操作。請前往火山費用中心充值 */
  MaaSAccountBalanceOverdue = 300011,
  /** 未知錯誤，請稍後重試。如果多次嘗試仍失敗，請提交工單 */
  MaaSUnknownErr = 300012,
}

export enum SftTaskHyperParamType {
  Int = 1,
  Float = 2,
  String = 3,
  Bool = 4,
  Percentage = 5,
}

export enum SftTaskOutputExportType {
  /** 導出到新模型 */
  NewModel = 1,
  /** 導出到已有模型 */
  ExistModel = 2,
}

export enum SftTaskOutputStatus {
  /** 未導出 */
  Available = 1,
  /** 已導出 */
  Exported = 2,
  /** 已過期 */
  Expired = 3,
  /** 導出中 */
  Exporting = 4,
  /** 導出失敗 */
  ExportFailed = 5,
}

export enum SftTaskResourceMerlinVersion {
  RemoveAnyGPU = 1,
}

export enum SftTaskRunEventType {
  Undefined = 0,
  ErrorOccured = 1,
  UploadCkpt = 2,
  ReportMetricsURL = 3,
  ReportProgress = 5,
  ReportTrainingStart = 6,
  ReportTrainingFinished = 7,
}

export enum SftTaskStatusPhase {
  Preprocessing = 0,
  Queued = 1,
  Deploying = 2,
  Running = 3,
  Completing = 4,
  Completed = 5,
  Terminating = 6,
  Terminated = 7,
  Failed = 8,
}

export enum SftTaskTrainingMethod {
  LoRA = 1,
  Full = 2,
}

export enum SftTaskTrainingType {
  SftFineTuning = 1,
}

export enum SftTaskValidationSetType {
  SplitFromTrainingSet = 1,
}

export enum TaskStatus {
  Undefined = 0,
  /** 正在初始化 */
  Initializing = 1,
  /** 正在運行 */
  Running = 2,
  /** 成功完成 */
  Done = 3,
  /** 失敗 */
  Failed = 4,
  /** 手動終止 */
  Terminated = 5,
  /** 成功完成，但有錯誤 */
  DoneWithError = 6,
}

export enum TrainingDataFileType {
  Undefined = 0,
  JSONL = 1,
}

export enum TrainingDatasetType {
  Undefined = 0,
  SFTChat = 1,
  SFTFunctionCall = 2,
  SFTMultiModalUnderstanding = 3,
}

export enum TrainingFileOpType {
  Undefined = 0,
  Get = 1,
  Put = 2,
}

export enum UsageScenario {
  /** 默認場景 */
  Default = 1,
  /** 評測場景 */
  Evaluation = 2,
  /** Prompt as a Service調用 */
  PromptAsAService = 3,
  /** AI打標 */
  AIAnnotate = 4,
  /** 質量分 */
  AIScore = 5,
  /** 數據標籤 */
  AITag = 6,
}

export enum ValidateStatus {
  Pass = 1,
  Failed = 2,
  Skip = 3,
}

export enum VisibleMode {
  /** 默認（僅模型所屬空間可見） */
  Default = 1,
  /** 指定空間可見 */
  Specified = 2,
  /** 所有空間可見 */
  All = 3,
}

export interface Ability {
  /** 最大上下文長度 */
  maxContextTokens?: Int64;
  /** 最大輸入長度 */
  maxInputTokens?: Int64;
  /** 最大輸出長度 */
  maxOutputTokens?: Int64;
  /** 是否支持函數調用 */
  functionCallEnabled?: boolean;
  /** 是否支持JSON模式 */
  jsonModeEnabled?: boolean;
  /** 是否支持多模態(模型輸入) */
  multiModalEnabled?: boolean;
  /** 多模態能力配置(模型輸入) */
  multiModalAbility?: MultiModalAbility;
  /** 消息預處理hook */
  messagePreHandleHook?: RuntimeHook;
  /** 模型可用的參數配置，優先級高於原有的maxContextTokens/maxInputTokens/maxOutputTokens */
  modelParams?: Array<ModelParam>;
  /** 是否支持思考能力開關 */
  thinkingSwitchEnabled?: boolean;
  /** 思考能力配置 */
  thinkingAbility?: ThinkingAbility;
  /** 是否支持多模態(模型輸出) */
  multiModalOutputEnabled?: boolean;
}

export interface Account {
  /** 賬號id */
  id?: Int64;
  /** 是否爲公共賬號 */
  isPublic?: boolean;
  /** 所屬模型id */
  modelID?: Int64;
  /** 所屬空間id */
  spaceID?: Int64;
  /** 區域 */
  region?: Region;
  /** 使用場景 */
  usageScenario?: UsageScenario;
  /** 授權認證信息 */
  authorization?: Authorization;
  /** 限流信息 */
  quota?: Quota;
  /** 創建人 */
  createdBy?: string;
  /** 更新人 */
  updatedBy?: string;
  /** 創建時間 */
  createdAt?: Int64;
  /** 更新時間 */
  updatedAt?: Int64;
  /** 編輯版本（用於解決多人同時更新問題） */
  editVersion?: Int64;
  /** 模型平臺賬號 id, 引用託管在平臺的賬號時提供， 直接添加 AKSK/Key 時爲空。 */
  modelProviderAccountID?: Int64;
}

export interface Authorization {
  gptOpenAPI?: GPTOpenAPIAuth;
  maas?: MaasAuth;
  botEngine?: BotEngineAuth;
}

export interface BotEngineAuth {
  connectorID?: Int64;
}

/** notice: 此處僅包含部分信息 */
export interface ByteTreeNode {
  id?: string;
  name?: string;
  i18nName?: string;
  type?: string;
  path?: string;
  i18nPath?: string;
  levelID?: Int64;
  isLeaf?: boolean;
}

export interface DataSource {
  type?: DataSourceType;
  tosFile?: TOSFile;
}

export interface DeployQuota {
  nodeID?: string;
  nodePath?: string;
  type?: string;
  displayType?: string;
  region?: string;
  zone?: string;
  /** 可用量 */
  available?: Int64;
}

export interface GPTOpenAPIAuth {
  ak?: string;
}

export interface GPTOpenAPIInfo {
  apiBaseURL?: string;
  apiVersion?: string;
}

export interface IDCDeployDetail {
  deployID?: string;
  /** 資源對應服務樹節點 id */
  byteNodeID?: string;
  region?: string;
  deviceType?: string;
  deviceDisplayName?: string;
  instance?: string;
}

export interface InstanceResourceOption {
  cpus?: string;
  /** 單位 GB */
  mem?: string;
  gpus?: string;
}

export interface InvalidDataSet {
  datasetID?: string;
  datasetName?: string;
  invalidReason?: string;
}

export interface MaaSAccountValidate {
  akValidate?: ProviderValidateDetail;
  kmsValidate?: ProviderValidateDetail;
  tosValidate?: ProviderValidateDetail;
}

export interface MaasAuth {
  /** 使用多雲代理時，ak 可以不傳 */
  ak?: string;
  sk?: string;
  /** 2.0控制面鑑權方式 */
  apiKey?: string;
  usedForSFT?: boolean;
  projects?: Array<string>;
  /** 使用多雲代理 */
  useMultiCloud?: boolean;
  /** 服務賬號名稱，使用多雲代理時必填 */
  serviceAccountName?: string;
  /** 是否需要遷移至字節雲方舟 */
  needMigArk?: boolean;
}

export interface MaasInfo {
  host?: string;
  region?: string;
  /** v3 sdk */
  baseURL?: string;
  /** 精調模型任務的 ID */
  customizationJobsID?: string;
}

export interface MaaSRegionConfig {
  region?: string;
  host?: string;
}

export interface MerlinInfo {
  psm?: string;
  cluster?: string;
  idcs?: Array<IDC>;
  framework?: MerlinFramework;
  instanceResourceOption?: InstanceResourceOption;
  /** 資源配置 */
  deployDetailM?: Partial<Record<IDC, IDCDeployDetail>>;
  /** 服務節點id */
  byteTreeNodeID?: Int64;
  /** 服務樹路徑 */
  byteTreeNodePath?: string;
  /** 服務詳情鏈接 */
  serviceDetailURL?: string;
  /** LLM 接口信息 */
  llmInterface?: MerlinLLMInterface;
  /** 是否開啓 vllm */
  useVLLMServe?: boolean;
  /** 調用 vllm 的 API 路徑，僅開啓 vllm 時使用 */
  vllmAPIPath?: string;
}

export interface MerlinResourceCluster {
  type?: MerlinQuotaPoolType;
  /** 是否爲可佔用資源 */
  preemptible?: boolean;
  /** merlin用戶組id */
  groupID?: Int64;
  /** merlin用戶組名稱 */
  groupName?: string;
  /** merlin集羣id */
  clusterID?: string;
  /** merlin集羣名稱 */
  clusterName?: string;
  /** key爲可選的gpuv型號，value爲該型號剩餘的gpu數量 */
  availableGpuvs?: Record<string, Int64>;
  /** 剩餘cpu數量 */
  cpuNum?: string;
  /** 剩餘內存數量，單位是MB */
  memory?: string;
  /** 機房 */
  dc?: string;
  /** 描述 */
  desc?: string;
  /** key爲可選的gpuv型號，value爲該型號推薦的套餐 */
  gpuvSets?: Record<string, MerlinResourceGpuSet>;
}

export interface MerlinResourceGpuSet {
  /** gpu個數 */
  gpu?: number;
  /** cpu個數 */
  cpu?: number;
  /** 內存，單位是GB */
  memory?: number;
}

export interface Model {
  /** 模型id, 在saas場景下可爲空，如果爲空則用identification+provider直接調用模型 */
  id?: Int64;
  /** 模型標識（name，endpoint，與各提供方對齊） */
  identification?: string;
  /** 展示名稱 */
  displayName?: string;
  /** 模型描述 */
  description?: string;
  /** 模型家族 */
  family?: Family;
  /** 提供方 */
  provider?: Provider;
  /** 提供方信息 */
  providerInfo?: ProviderInfo;
  /** 是否爲公共模型 */
  isPublic?: boolean;
  /** 可見性 */
  visibility?: Visibility;
  /** 所屬空間id */
  spaceID?: Int64;
  /** 模型能力 */
  ability?: Ability;
  /** 默認運行時參數 */
  defaultRuntimeParam?: RuntimeParam;
  /** 創建人 */
  createdBy?: string;
  /** 更新人 */
  updatedBy?: string;
  /** 創建時間 */
  createdAt?: Int64;
  /** 更新時間 */
  updatedAt?: Int64;
  /** 編輯版本（用於解決多人同時更新問題） */
  editVersion?: Int64;
  modelStatus?: ModelStatus;
  /** 模型提供方側的 model id */
  externalModelID?: string;
  /** 從精調模型任務的產出中新建推理點產生的模型 */
  sftTaskID?: Int64;
  /** 模型版本 */
  modelVersion?: string;
  /** 模型頭像 */
  modelIcon?: string;
  /** 模型公司 */
  modelVendor?: string;
  /** 模型真實名稱（展示在vendor右側，可能是豆包endpoint或其他廠商的模型名稱） */
  actualName?: string;
  /** 模型標籤 */
  modelTags?: Array<string>;
}

export interface ModelParam {
  name?: string;
  label?: string;
  desc?: string;
  /** 類型： bool/int/float等 */
  modelParamType?: ModelParamType;
  min?: string;
  max?: string;
  defaultVal?: string;
  /** 枚舉 */
  modelParamOptions?: Array<ModelParamOption>;
}

export interface ModelParamOption {
  /** 展示值 */
  label?: string;
  /** 實際值 */
  value?: string;
}

export interface MultiModalAbility {
  /** [1, 99] 圖片配置
是否支持圖片 */
  imageEnabled?: boolean;
  /** 是否支持二進制圖片 */
  binaryImageEnabled?: boolean;
  /** 單張圖片大小限制, 範圍 [0, 20]MB */
  maxImageSizeInMB?: number;
  /** 最大圖片數量, 範圍 [-1, 100], -1 表示無限制 */
  maxImageCount?: number;
}

export interface OnlyReadable {
  /** 是否只讀態 */
  onlyReadable?: boolean;
  /** 只讀態原因 */
  desc?: string;
}

/** 託管的模型平臺賬號信息 */
export interface ProviderAccount {
  id?: string;
  spaceID?: string;
  provider?: Provider;
  type?: ProviderAccountType;
  name?: string;
  providerRegion?: string;
  maasAccount?: MaasAuth;
  updatedAt?: string;
  createdAt?: string;
  updatedBy?: string;
  createdBy?: string;
}

export interface ProviderAccountRelatedResources {
  sftTaskCount?: string;
  sftTaskIDs?: Array<string>;
  modelCount?: string;
  modelIDs?: Array<string>;
}

export interface ProviderInfo {
  gptOpenAPI?: GPTOpenAPIInfo;
  maas?: MaasInfo;
  merlin?: MerlinInfo;
}

export interface ProviderValidateDetail {
  status?: ValidateStatus;
  invalidatedReason?: string;
  /** 校驗不通過時，用戶可通過此處的 url 前往指定平臺處理 */
  providerURL?: string;
}

export interface Quota {
  qpm?: Int64;
  tpm?: Int64;
}

export interface RuntimeCustomParam {
  name?: string;
  type?: RuntimeCustomParamType;
  value?: string;
}

export interface RuntimeHook {
  type?: RuntimeHookType;
  url?: string;
}

export interface RuntimeParam {
  /** 最大輸出長度 */
  maxTokens?: Int64;
  temperature?: number;
  topP?: number;
  topK?: Int64;
  jsonMode?: boolean;
  /** 停止詞, 值必須是json序列化後的字符串數組 */
  stopWords?: string;
  /** 運行時自定義參數 */
  runtimeCustomParams?: Array<RuntimeCustomParam>;
  /** 是否默認支持思考能力 */
  thinkingEnabled?: boolean;
  /** 當thinkingEnabled==true時有效，含義爲默認thinking max token */
  thinkingBudgetTokens?: Int64;
}

export interface SftTask {
  id?: string;
  name?: string;
  spaceID?: string;
  provider?: Provider;
  accountID?: string;
  accountName?: string;
  createdBy?: string;
  updatedBy?: string;
  createTimeInMS?: string;
  updateTimeInMS?: string;
  trainingType?: SftTaskTrainingType;
  trainingMethod?: SftTaskTrainingMethod;
  /** 選擇的模型 */
  sftBasedModel?: SftTaskBaseModel;
  /** 設置的超參 */
  hyperParams?: Array<SftTaskHyperParam>;
  /** 選擇的數據集 */
  dataset?: SftTaskDataset;
  /** 輸出模型數量上限 */
  modelOutputLimit?: number;
  /** 任務完成時輸出的模型 */
  outputs?: Array<SftTaskOutput>;
  /** 任務的狀態 */
  status?: SftTaskStatus;
  /** 各種外部平臺的鏈接 */
  providerURLInfo?: SftTaskProviderURLInfo;
  /** 描述 */
  description?: string;
  /** 是否關聯了Fornax的模型，如果已關聯，不允許刪除此任務 */
  isRelatedToFrnModels?: boolean;
  /** 資源配置（目前只適用於merlin） */
  resource?: SftTaskResource;
  /** 訓練產物配置（目前只適用於merlin） */
  outputConfig?: SftTaskOutputConfig;
  hyperParamsCategories?: Array<SftTaskHyperParamCategory>;
  /** 是否只讀態 */
  onlyReadable?: OnlyReadable;
}

export interface SftTaskBaseModel {
  /** 定製模型 */
  customModel?: SftTaskCustomModel;
  /** 基礎模型 */
  foundationModel?: SftTaskFoundationModel;
  /** 模型類型 */
  type?: SftTaskBaseModelType;
}

export interface SftTaskCustomModel {
  id?: string;
  name?: string;
  updateTimeInMS?: string;
  /** 訓練此定製模型的任務的超參 */
  hyperParams?: Array<SftTaskHyperParam>;
  /** 此定製模型是通過哪個基礎模型訓練得到 */
  foundationModel?: SftTaskFoundationModel;
  /** merlin模型倉庫版本 */
  version?: string;
  /** merlin模型文件保存的地址 */
  hdfsPath?: string;
}

export interface SftTaskDataset {
  /** 訓練集 */
  trainingSet?: SftTaskTrainingSet;
  /** 驗證集 */
  validationSet?: SftTaskValidationSet;
}

export interface SftTaskFoundationModel {
  name?: string;
  /** 模型來源（廠商） */
  vendor?: string;
  desc?: string;
  /** 展示名稱 */
  displayName?: string;
  version?: string;
  versionUpdateTimeInMS?: string;
  versionDesc?: string;
  versionConfigID?: string;
  /** 系列 */
  family?: Family;
  /** 系列描述 */
  familyName?: string;
  /** 參數量 */
  modelSize?: string;
  /** 上下文長度 */
  contextSize?: string;
  /** 參數量描述 */
  modelFTType?: string;
  /** 模型卡片URL */
  modelCardURL?: string;
  modelTags?: Array<string>;
  ability?: Ability;
  /** 該模型在前端是否不可見（如doubao-embedding模型，因爲訓練集不支持embedding數據，所以也先不展示這個模型） */
  invisible?: boolean;
}

export interface SftTaskHyperParam {
  name?: string;
  value?: string;
  type?: SftTaskHyperParamType;
  min?: string;
  max?: string;
  defaultValue?: string;
  desc?: string;
  options?: Array<string>;
  /** 選擇定製模型進行增量訓練時，此參數是否允許鎖死不允許用戶在創建任務時修改 */
  incrementalLearningLocked?: boolean;
  /** 展示用，如果爲空字符串，就用name做兜底 */
  displayName?: string;
  isRequired?: boolean;
}

export interface SftTaskHyperParamCategory {
  name?: string;
  displayName?: string;
  desc?: string;
  isRequired?: boolean;
  defaultValue?: boolean;
  value?: boolean;
  hyperParams?: Array<SftTaskHyperParam>;
  /** 幫助文檔鏈接 */
  helpDocLink?: string;
}

export interface SftTaskOutput {
  index?: number;
  customModelID?: string;
  customModelCreateTimeInMS?: string;
  createTimeInMS?: string;
  name?: string;
  /** 是否已導出 */
  status?: SftTaskOutputStatus;
  /** 在Fornax註冊的私有模型信息 */
  registeredModel?: Array<SftTaskRegisteredModel>;
  /** 描述 */
  description?: string;
  /** 過期時間 */
  expireTimeInMS?: string;
  /** 版本號，暫時只支持merlin模型 */
  modelVersion?: string;
  /** 模型路徑(暫時只支持merlin模型，爲hdfs地址) */
  modelPath?: string;
  /** 此模型(版本)在模型提供方的URL，暫時只支持merlin模型 */
  modelProviderURL?: string;
  /** 狀態詳情，暫時只有status是導出失敗時纔會有值 */
  statusDetail?: string;
}

export interface SftTaskOutputConfig {
  /** 導出的模型名稱 */
  exportModelName?: string;
  /** 導出方式 */
  exportType?: SftTaskOutputExportType;
}

export interface SftTaskPresetDataset {
  name?: string;
}

export interface SftTaskProgress {
  /** 計劃的epoch */
  plannedEpoch?: Int64;
  /** 當前的epoch */
  currentEpoch?: Int64;
  /** 計劃的step */
  plannedStep?: Int64;
  /** 當前的step */
  currentStep?: Int64;
  /** 預計剩餘時間，秒 */
  eta?: Int64;
  /** 是否訓練完成 */
  isTraningFinished?: boolean;
}

export interface SftTaskProviderURLInfo {
  /** 任務詳情 */
  TaskDetailURL?: string;
  /** 效果指標 */
  MetricsURL?: string;
  /** 日誌 */
  LogURL?: string;
  /** 時間線 */
  TimelineURL?: string;
  /** 模型輸出 */
  OutputURL?: string;
  /** 訓練時測評 */
  EvaluationURL?: string;
  /** 系統指標 */
  SystemMetricsURL?: string;
}

export interface SftTaskRegisteredModel {
  modelID?: string;
  name?: string;
}

export interface SftTaskResource {
  provider?: Provider;
  merlin?: SftTaskResourceMerlin;
}

export interface SftTaskResourceMerlin {
  type?: MerlinQuotaPoolType;
  /** 用戶組id，暫時只支持1個 */
  groupIDs?: Array<string>;
  /** 集羣id */
  clusterID?: string;
  /** 是否使用可佔用資源 */
  preemptible?: boolean;
  /** 角色配置，暫時只支持1個 */
  roles?: Array<SftTaskResourceMerlinRole>;
  /** key是用戶組id，val是用戶組名稱 */
  groupNames?: Record<Int64, string>;
  /** 集羣名稱 */
  clusterName?: string;
  /** merlin資源格式的版本，目前唯一作用：由於資源格式不向前兼容，只有指定版本號的資源才能在複製精調任務時被寫入到新任務中 */
  version?: SftTaskResourceMerlinVersion;
}

export interface SftTaskResourceMerlinRole {
  /** 實例數，必填1 */
  num?: number;
  /** 虛擬gpu型號 */
  gpuv?: string;
  /** gpu數量 */
  gpu?: number;
  /** cpu數量 */
  cpu?: number;
  /** 內存大小，單位是MB */
  memory?: number;
}

export interface SftTaskStatus {
  /** 狀態 */
  phase?: SftTaskStatusPhase;
  /** 到達狀態的時間 */
  phaseTimeInMS?: string;
  /** 狀態是排隊中時的排隊位次 */
  queuePosition?: number;
  /** 對該狀態的詳細說明，如報錯信息 */
  detail?: string;
  /** 狀態碼 */
  code?: number;
}

export interface SftTaskTrainingSet {
  trainingSetID?: string;
  /** 預置數據集 */
  presetDataset?: SftTaskPresetDataset;
  /** 預置數據集佔訓練集的百分比 */
  presetDatasetPercentage?: number;
  /** 支持精調任務使用多個訓練數據集 */
  trainingSetIDs?: Array<string>;
  /** 自定義數據集路徑 */
  trainingSetPath?: string;
}

export interface SftTaskValidationSet {
  type?: SftTaskValidationSetType;
  /** 從訓練集中分割的百分比 */
  splitPercentage?: number;
}

export interface ThinkingAbility {
  /** 是否默認開啓思考能力 */
  switchDefaultEnabled?: boolean;
  /** 思考最大token */
  maxBudgetTokens?: Int64;
  /** 思考最小token，必須大於0 */
  minBudgetTokens?: Int64;
}

export interface TOSFile {
  bucket?: string;
  key?: string;
}

export interface TrainingDataImportTask {
  id?: string;
  datasetID?: string;
  status?: TaskStatus;
  fileType?: TrainingDataFileType;
  dataSource?: DataSource;
  mode?: DataImportMode;
  /** 文件大小，單位：byte */
  totalSize?: number;
  /** 已處理數據大小，單位：byte */
  processedSize?: number;
  /** 已處理的行數 */
  processedLineCount?: number;
  /** 已導入的行數 */
  outputLineCount?: number;
  errLog?: string;
  msg?: string;
  /** Fornax空間ID */
  spaceID?: string;
  /** 創建人ID */
  createdBy?: string;
  /** 創建時間，秒 */
  createdAt?: string;
  /** 更新人ID */
  updatedBy?: string;
  /** 更新時間，秒 */
  updatedAt?: string;
}

export interface Visibility {
  mode?: VisibleMode;
  /** Mode爲Specified有效，配置爲除模型所屬空間外的其他空間 */
  spaceIDs?: Array<Int64>;
}
/* eslint-enable */
