/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as filter from './filter';
import * as flow_devops_prompt_common from './flow_devops_prompt_common';
import * as batch_infer from './batch_infer';

export type Int64 = string | number;

export enum AIAnnotatorCategory {
  /** 在線 */
  Online = 1,
  /** 離線 */
  Offline = 2,
}

export enum AnnotationType {
  /** 大模型打標 */
  AI = 1,
  /** 規則打標 */
  Rule = 2,
  /** 手動打標 */
  Manual = 3,
}

export enum CrowdsourcingAnnotateJobStatus {
  Undefined = 0,
  Sending = 1,
  In_Progress = 2,
  Abnormal = 3,
  Completed = 4,
  Terminated = 5,
}

export enum CrowdsourcingAnnotationPlatform {
  Undefined = 0,
  AIDP = 1,
  AIDP_Lite = 2,
}

export enum DataSelectScope {
  Undefined = 0,
  All = 1,
  Filtered = 2,
  Manually_Selected = 3,
}

export enum RuleAnnotatorCategory {
  /** python */
  Python = 1,
}

export enum ThinkingOutputBehavior {
  UNSPECIFIED = 0,
  WithoutThinking = 1,
  ThinkingToSpecifiedColumn = 2,
}

export interface AIAnnotator {
  /** 該字段和內層的PromptCategory含義不同，代表是否關聯已有評估器，當前沒有用到該字段 */
  category?: AIAnnotatorCategory;
  onlineAIAnnotator?: OnlineAIAnnotator;
  offlineAIAnnotator?: OfflineAIAnnotator;
}

export interface AIDPConfig {
  /** AIDP 用戶 ID */
  userID: string;
  /** AIDP 任務 ID */
  taskID: string;
  /** 任務名稱 */
  taskName: string;
  /** 任務詳情鏈接，返回字段 */
  taskURL?: string;
  answerSchema?: string;
}

export interface AIDPField {
  key?: string;
  name?: string;
}

export interface AIDPFlowNode {
  nodeID?: string;
  name?: string;
}

export interface AIDPTaskFlowConfig {
  nodes?: Array<AIDPFlowNode>;
  requiredFields?: Array<AIDPField>;
}

export interface AIDPTaskSummary {
  /** 任務ID */
  taskID?: string;
  /** 任務名稱 */
  title?: string;
  /** 項目名稱 */
  projectName?: string;
  /** 回調配置 */
  callbackOpts?: CallbackOpts;
  /** 答案模板ID */
  templateID?: string;
  /** 任務鏈接 */
  taskURL?: string;
}

export interface AnnotateStatusDetail {
  /** 總數據量 */
  inputSize?: string;
  /** 已送標數據量 */
  sent?: string;
  /** 已取標數據量 */
  received?: string;
}

export interface AnnotationConfig {
  /** 標註任務類型 */
  annotationType?: AnnotationType;
  /** 大模型打標器配置 */
  aiAnnotator?: AIAnnotator;
  /** 規則打標器配置 */
  ruleAnnotator?: RuleAnnotator;
}

export interface AnnotationJob {
  /** 主鍵ID */
  id?: string;
  appId?: string;
  spaceId?: string;
  /** JobID */
  annotationJobId?: string;
  jobDomain?: string;
  targetID?: string;
  /** 任務的版本，非數據集版本 */
  version?: string;
  /** 狀態：active/inactive */
  status?: string;
  name?: string;
  annotationConfig?: AnnotationConfig;
  targetResourceName?: string;
  extra?: string;
  /** 通用信息 */
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
}

export interface AnnotationJobRunInstance {
  /** 運行後產生的Job實例ID */
  annotationJobRunID?: string;
  /** 總條數 */
  total?: number;
  /** 成功條數 */
  successCnt?: number;
  /** 失敗條數 */
  failedCnt?: number;
  /** 任務狀態,running/success/failed/canceled/partial_success */
  status?: string;
  /** 僅在 GetAnnotationJobProcess 接口返回，用於輪詢查詢輸出列關聯的打標任務 */
  outputFieldKeys?: Array<string>;
  /** JobID非ID */
  jobID?: string;
  job?: AnnotationJob;
  createdBy?: string;
  createdAt?: string;
  endAt?: string;
  runLog?: AnnotationJobRunLog;
}

export interface AnnotationJobRunLog {
  /** 錯誤日誌 */
  errorMsg?: string;
  /** 離線任務的跳轉鏈接 */
  offlineJobProviderUrl?: string;
}

export interface Annotator {
  /** 類型: 手工manual、關聯associated */
  category?: string;
  /** 手工配置 */
  manualAnnotator?: ManualAnnotator;
}

export interface CallbackOpts {
  CallbackType?: string;
}

export interface CrowdsourcingAnnotateInputConfig {
  /** 輸入數據集ID */
  inputDatasetID: string;
  /** 輸入數據集名 */
  inputDatasetName: string;
  /** 輸入數據集版本 */
  inputDatasetVersionNum: string;
  /** 輸入數據集Veriosn主鍵 */
  inputDatasetVersionID: string;
  /** 三段式版本號返回字段 */
  inputDatasetVersion?: string;
  /** 需要標註數據的itemID */
  itemIDs?: Array<Int64>;
  /** 數據篩選條件,待定看標籤的具體實現 */
  filter?: filter.Filter;
  /** 返回字段 */
  fieldMeta?: filter.FieldMetaInfoData;
  /** 返回字段 */
  total?: number;
  /** 發送字段映射配置 */
  inputMappings: Array<InputMapping>;
  /** 數據範圍 */
  dataSelectScope?: DataSelectScope;
}

export interface CrowdsourcingAnnotateJob {
  /** 主鍵 */
  id?: string;
  name?: string;
  description?: string;
  platform?: CrowdsourcingAnnotationPlatform;
  /** AIDP 配置 */
  aidpConfig?: AIDPConfig;
  /** 送標配置 */
  inputConfig?: CrowdsourcingAnnotateInputConfig;
  /** 取標配置 */
  outputConfig?: CrowdsourcingAnnotateOutputConfig;
  /** 數據詳情存儲的數據集ID */
  InternalDatasetID?: string;
  /** 任務狀態 */
  status?: CrowdsourcingAnnotateJobStatus;
  /** 失敗的原因 */
  terminateReason?: string;
  /** 任務進展 */
  statusDetail?: AnnotateStatusDetail;
  /** 創建時間 */
  createdAt?: string;
  /** 更新時間/結束時間 */
  updatedAt?: string;
  /** 創建人 */
  createdBy?: string;
}

export interface CrowdsourcingAnnotateOutputConfig {
  /** 是否自動取標 */
  isAutoFetchRes: boolean;
  /** 是否自動輸出到新數據集 */
  isAutoExportToNewDataset: boolean;
  /** 輸出數據集名稱 */
  outputDatasetName?: string;
  /** 輸出數據集ID 返回字段 */
  outputDatasetID?: string;
  /** 是否拆解標註結果 */
  isParseAnnotateRes: boolean;
  /** 輸出映射 */
  outputMappings?: Array<OutputMapping>;
}

export interface InputMapping {
  /** 輸入類型: 固定值fixed、關聯字段use_column、之前輸入former_model_input、之前輸出former_model_output */
  sourceType?: string;
  /** 輸入值 */
  sourceValue?: string;
  /** 輸出類型: prompt變量名prompt_var_name */
  targetType?: string;
  /** 輸出值 */
  targetValue?: string;
  /** 如果是列這個字段可以存儲name */
  sourceName?: string;
}

export interface ManualAnnotator {
  /** 模型配置 */
  model?: flow_devops_prompt_common.ModelConfig;
  /** prompt類型：手工manual、關聯associated */
  promptCategory?: string;
  /** 手工填入的數據內容 */
  promptContent?: string;
  /** 關聯時 */
  promptID?: string;
  /** 關聯時 */
  promptVersion?: string;
  userPromptColumnName?: string;
  /** 輸入映射 */
  inputMappings?: Array<InputMapping>;
  /** 輸出映射 */
  outputMappings?: Array<OutputMapping>;
  /** thinking輸出映射，當ThinkingOutputBehavior=ThinkingToSpecifiedColumn時使用 */
  thinkingOutputMapping?: OutputMapping;
}

export interface OfflineAIAnnotator {
  /** 批量推理配置
模型來源 */
  batchInferprovider?: batch_infer.Provider;
  /** 模型配置 & 資源配置 */
  batchInferProviderInfo?: batch_infer.ProviderInfo;
  /** 模型參數 */
  batchInferParam?: batch_infer.BatchInferParam;
  /** 任務配置
prompt類型 manual/associated/none */
  promptCategory?: string;
  /** 手工填入的數據內容 */
  promptContent?: string;
  /** 關聯時 */
  promptID?: string;
  /** 關聯時 */
  promptVersion?: string;
  userPromptColumnName?: string;
  /** 輸入映射 */
  inputMappings?: Array<InputMapping>;
  /** 輸出映射 */
  outputMappings?: Array<OutputMapping>;
  /** 僅爲空值打標 */
  onlyForEmpty?: boolean;
  /** 僅爲失敗打標 */
  onlyForFailed?: boolean;
  /** 允許未配置的標籤選項 */
  allowUndefinedTagValues?: boolean;
}

export interface OnlineAIAnnotator {
  /** 標註器配置 */
  annotator?: Annotator;
  /** 推理次數 */
  inferRound?: number;
  /** 批處理數據量 */
  batchSize?: number;
  /** 僅爲空值打標 */
  onlyForEmpty?: boolean;
  /** 僅爲失敗打標 */
  onlyForFailed?: boolean;
  /** 允許未配置的標籤選項 */
  allowUndefinedTagValues?: boolean;
  /** 自動更新 */
  autoUpdate?: boolean;
  /** 打標併發度 */
  executeConcurrency?: number;
  /** 輸出模型thinking過程的策略 */
  thinkingOutputBehavior?: ThinkingOutputBehavior;
}

export interface OutputMapping {
  /** 輸入類型: plain、json_path */
  sourceType?: string;
  /** 輸入值 */
  sourceValue?: string;
  /** 輸出類型: use_column、plain */
  targetType?: string;
  /** 輸出值 */
  targetValue?: string;
  /** targetType是use_column時標識是否是新建列 */
  isNewColumn?: boolean;
  /** 輸入值的標籤/name */
  sourceName?: string;
}

export interface PassKTask {
  /** 推理模型配置 */
  reasoner?: Annotator;
  /** 推理次數 */
  inferenceRound?: number;
  /** 評估器配置 */
  judge?: Annotator;
  /** 正確閾值 */
  positiveThreshold?: number;
}

export interface QualityScoreJob {
  /** 唯一ID，創建時不傳 */
  id?: string;
  /** appID，創建時不傳 */
  appID?: number;
  /** 空間ID，創建時不傳 */
  spaceID?: string;
  /** 數據集ID，創建時不傳 */
  datasetID?: string;
  /** 版本號，創建時不傳 */
  version?: string;
  /** job ID，創建時不傳 */
  jobID?: string;
  /** 任務名字, 可不傳 */
  name?: string;
  /** 任務狀態: active、inactive */
  status?: string;
  /** 標註任務類型: passk */
  category?: string;
  /** passKTask 任務內容 */
  passKTask?: PassKTask;
  /** 是否自動計算新增數據 */
  autoCalculateNewData?: boolean;
  /** 通用信息 */
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
}

export interface QualityScoreJobInstance {
  /** instance唯一id */
  id?: string;
  /** 任務ID */
  jobID?: string;
  /** 總條數 */
  total?: number;
  /** 成功條數 */
  successCnt?: number;
  /** 失敗條數 */
  failedCnt?: number;
  /** 任務狀態 */
  status?: string;
}

export interface RuleAnnotator {
  /** 規則類型 */
  category?: RuleAnnotatorCategory;
  /** 規則內容 */
  content?: string;
  /** 輸入映射 */
  inputMappings?: Array<InputMapping>;
  /** 輸出映射 */
  outputMappings?: Array<OutputMapping>;
  /** 允許未配置的標籤選項 */
  allowUndefinedTagValues?: boolean;
  /** 僅爲空值打標 */
  onlyForEmpty?: boolean;
  /** 僅爲失敗項打標 */
  onlyForFailed?: boolean;
}

export interface SearchConfig {
  /** 數據集ID */
  datasetID?: string;
  /** 搜索的任務名稱 */
  jobName?: string;
  /** 搜索的任務ID */
  jobID?: string;
  /** 搜索的創建人 */
  createdBy?: Array<string>;
}
/* eslint-enable */
