/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as datasetv2 from './datasetv2';

export type Int64 = string | number;

export enum LineageSourceType {
  Manual = 1,
  /** 需要根據 ItemSource.dataset.category 字段區分評測集/數據集/... */
  Dataset = 2,
  /** 需要根據 ItemSource.file.storage 字段區分HDFS/本地上傳/... */
  FileStorage = 3,
  /** 暫無 */
  DataReflow = 4,
  /** 暫無 */
  DataAnnotation = 5,
  /** 暫無 */
  DataProcessing = 6,
  /** 暫無 */
  DataGenerate = 7,
  OpenAPI = 8,
  /** 衆包標註任務 */
  CrowdsourcingAnnotation = 9,
}

export enum TrackedJobType {
  /** 數據導入任務 */
  DatasetIOJob = 1,
  /** 數據迴流任務 */
  DataReflow = 2,
  /** 標註任務 */
  DataAnnotation = 3,
  /** 數據處理任務 */
  DataProcessing = 4,
  /** 數據生成任務 */
  DataGenerate = 5,
  /** 衆包標註任務 */
  CrowdsourcingAnnotation = 6,
}

export interface ItemSource {
  type: LineageSourceType;
  /** 源 item 信息，可以爲空 */
  trackedItem?: TrackedItem;
  /** 任務類型，根據該字段區分數據導入任務/數據迴流任務/... */
  jobType?: TrackedJobType;
  /** item 關聯的任務 id，爲 0 表示無相應任務(例如數據是通過克隆另一數據行產生的) */
  jobID?: string;
  /** type = Dataset 時，從該字段獲取數據集具體信息 */
  dataset?: TrackedDataset;
  /** type = FileStorage 時，從該字段獲取文件信息 */
  file?: TrackedFile;
  createdAt?: string;
}

/** 源數據集信息（數據集 id 從 TrackedItem 中獲取，此處不額外返回） */
export interface TrackedDataset {
  /** 數據集類別，根據該字段區分評測集/數據集/... */
  category?: datasetv2.DatasetCategory;
  datasetName?: string;
}

export interface TrackedFile {
  /** 存儲介質，根據該字段區分 hdfs/本地文件(即 ImageX)/... */
  storage?: datasetv2.StorageProvider;
  /** 用戶上傳文件的原始文件名 */
  originalFileName?: string;
}

export interface TrackedItem {
  spaceID?: string;
  datasetID?: string;
  itemID?: string;
  /** 版本號提交後的版本 id，爲 0 表示爲草稿版本 */
  versionID?: string;
  /** 版本號（三段式） */
  version?: string;
}
/* eslint-enable */
