/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ByteTreeNodeResourceProvider {
  TCE = 1,
  TCC = 2,
  Bernard = 3,
}

export enum CommercialModelStatus {
  Online = 1,
  Offline = 2,
  Deleted = 3,
  FineTuneInQueue = 4,
  FineTuneRunning = 5,
  FineTuneFailed = 6,
  FineTuneTerminated = 7,
}

export enum DataImportMode {
  Undefined = 0,
  /** 追加 */
  Append = 1,
  /** 覆蓋 */
  Overwrite = 2,
}

export enum DataSourceType {
  Undefined = 0,
  TOS = 1,
}

export enum Family {
  Undefined = 0,
  GPT = 1,
  Seed = 2,
  Gemini = 3,
  Claude = 4,
  Ernie = 5,
  Baichuan = 6,
  Qwen = 7,
  GLM = 8,
  SkyLark = 9,
  Moonshot = 10,
  Minimax = 11,
  Doubao = 12,
  Baichuan2 = 13,
  DeepSeekV2 = 14,
  DeepSeekCoderV2 = 15,
  DeepseekCoder = 16,
  InternLM2_5 = 17,
  Qwen2 = 18,
  Qwen2_5 = 19,
  Qwen2_5_Coder = 20,
  MiniCPM = 21,
  MiniCPM3 = 22,
  ChatGLM3 = 23,
  Mistral = 24,
  Gemma = 25,
  Gemma2 = 26,
  InternVL2 = 27,
  InternVL2_5 = 28,
  DeepSeekV3 = 29,
}

export enum IDC {
  HL = 1,
  LF = 2,
  LQ = 3,
  YG = 4,
  GL = 5,
  MALIVA = 101,
  SG1 = 201,
  MY = 202,
  MY2 = 203,
  MYCISB = 204,
}

export enum MerlinFramework {
  LLMServerPublic = 1,
  Laplace = 2,
}

export enum MerlinLLMInterface {
  MatxInference = 1,
}

export enum MerlinQuotaPoolType {
  /** 穩定資源 */
  Default = 0,
  /** 潮汐資源 */
  Hybrid = 1,
  /** 常混資源 */
  HybridShare = 2,
  /** 第三方資源ali */
  ALI = 3,
  /** 第三方資源hw */
  HW = 4,
}

export enum ModelFilterKey {
  ModelType = 1,
  ModelUserRight = 2,
  ModelFeature = 3,
  ModelFunction = 4,
  ModelScenario = 5,
  Custom = 20,
}

export enum ModelFilterScene {
  Default = 0,
  EvalFunctionCall = 1,
}

export enum ModelParamType {
  Unknown = 0,
  Float = 1,
  Int = 2,
  Boolean = 3,
  String = 4,
}

export enum ModelStatus {
  Undefined = 0,
  /** 健康可用 */
  Available = 1,
  /** 部署中 */
  Deploying = 2,
  /** 不可用（已下線） */
  Unavailable = 3,
  /** 下線中 */
  Offlining = 4,
}

export enum Provider {
  /** GPT OpenAPI平臺 */
  GPTOpenAPI = 1,
  /** 火山方舟 */
  Maas = 2,
  /** 暫時特指seed從bot_engine接入 */
  BotEngine = 3,
  /** merlin平臺 */
  Merlin = 4,
  /** merlin-seed平臺 */
  MerlinSeed = 5,
}

export enum ProviderAccountType {
  AKSK = 1,
  APIKey = 2,
}

export enum Region {
  CN = 1,
  SG = 2,
  US = 3,
}

export enum RuntimeCustomParamType {
  Unknown = 0,
  StringList = 1,
  IntList = 2,
  FloatList = 3,
  String = 4,
  Int = 5,
  Float = 6,
  Bool = 7,
}

export enum RuntimeHookType {
  Unknown = 0,
  MsgPreHook = 1,
}

export enum SftTaskBaseModelType {
  Foundation = 0,
  Custom = 1,
}

export enum SftTaskErrCode {
  Default = 0,
  /** 前2位代表錯誤分類，後4位代表具體錯誤
10 通用錯誤 */
  InternalErr = 100000,
  /** 訓練集上傳到平臺方時出錯 */
  TrainingSetUploadedErr = 100001,
  /** 在平臺方創建精調任務出錯 */
  CreateProviderSftTaskErr = 100002,
  /** 20 Merlin任務實例整體報錯 */
  MerlinTaskInternalError = 200000,
  /** gpu cpu mem 套餐配比錯誤 */
  MerlinGpuCpuMemRatioBad = 200001,
  /** 21 Merlin訓練腳本主動上報的錯誤 */
  MerlinReportedInternalErr = 210000,
  MerlinOOM = 210001,
  /** 沒找到模型訓練產物 */
  MerlinNoModelGenerated = 210002,
  /** 30 火山方舟任務失敗
方舟通用錯誤 */
  MaaSInternalErr = 300000,
  /** 驗證集比例分割異常 */
  MaaSValidationSetSplitErr = 300001,
  /** 訓練數據格式不符合預期 */
  MaaSTrainingSetNoValid = 300002,
  /** 業務方的火山賬號沒有開通模型服務 */
  MaaSAccountModelServiceIsNotActivated = 300003,
  /** 缺少必要的請求參數。請確認請求參數後重試。 */
  MaaSRequiredParamMissing = 300004,
  /** 請求參數值不合法。請檢查參數值的正確性後重試。 */
  MaaSRequestParamInvalid = 300005,
  /** 對象的標籤存在重複Key */
  MaaSDuplicateTags = 300006,
  /** 無法同時上傳驗證集和設置訓練集取樣爲驗證集百分比，不支持該操作 */
  MaaSNotSupportedToConfigureValidationSetAndPercentage = 300007,
  /** 您沒有權限訪問基礎模型的配置，不支持該操作 */
  MaaSNotPermittedToAccessModel = 300008,
  /** 模型不支持該訓練方法，不支持該操作 */
  MaaSModelNotSupportTheTrainingMethod = 300009,
  /** 基礎模型的版本不支持該訓練方法，不支持該操作 */
  MaaSFoundationModelNotSupportTheTrainingMethod = 300010,
  /** 您的賬單已逾期，不支持該操作。請前往火山費用中心充值 */
  MaaSAccountBalanceOverdue = 300011,
  /** 未知錯誤，請稍後重試。如果多次嘗試仍失敗，請提交工單 */
  MaaSUnknownErr = 300012,
}

export enum SftTaskHyperParamType {
  Int = 1,
  Float = 2,
  String = 3,
  Bool = 4,
  Percentage = 5,
}

export enum SftTaskOutputExportType {
  /** 導出到新模型 */
  NewModel = 1,
  /** 導出到已有模型 */
  ExistModel = 2,
}

export enum SftTaskOutputStatus {
  /** 未導出 */
  Available = 1,
  /** 已導出 */
  Exported = 2,
  /** 已過期 */
  Expired = 3,
  /** 導出中 */
  Exporting = 4,
  /** 導出失敗 */
  ExportFailed = 5,
}

export enum SftTaskRunEventType {
  Undefined = 0,
  ErrorOccured = 1,
  UploadCkpt = 2,
  ReportMetricsURL = 3,
  ReportProgress = 5,
  ReportTrainingStart = 6,
  ReportTrainingFinished = 7,
}

export enum SftTaskStatusPhase {
  Preprocessing = 0,
  Queued = 1,
  Deploying = 2,
  Running = 3,
  Completing = 4,
  Completed = 5,
  Terminating = 6,
  Terminated = 7,
  Failed = 8,
}

export enum SftTaskTrainingMethod {
  LoRA = 1,
  Full = 2,
}

export enum SftTaskTrainingType {
  SftFineTuning = 1,
}

export enum SftTaskValidationSetType {
  SplitFromTrainingSet = 1,
}

export enum TaskStatus {
  Undefined = 0,
  /** 正在初始化 */
  Initializing = 1,
  /** 正在運行 */
  Running = 2,
  /** 成功完成 */
  Done = 3,
  /** 失敗 */
  Failed = 4,
  /** 手動終止 */
  Terminated = 5,
  /** 成功完成，但有錯誤 */
  DoneWithError = 6,
}

export enum TrainingDataFileType {
  Undefined = 0,
  JSONL = 1,
}

export enum TrainingDatasetType {
  Undefined = 0,
  SFTChat = 1,
  SFTFunctionCall = 2,
  SFTMultiModalUnderstanding = 3,
}

export enum TrainingFileOpType {
  Undefined = 0,
  Get = 1,
  Put = 2,
}

export enum UsageScenario {
  /** 默認場景 */
  Default = 1,
  /** 評測場景 */
  Evaluation = 2,
  /** Prompt as a Service調用 */
  PromptAsAService = 3,
  /** AI打標 */
  AIAnnotate = 4,
}

export enum ValidateStatus {
  Pass = 1,
  Failed = 2,
  Skip = 3,
}

export enum VisibleMode {
  /** 默認（僅模型所屬空間可見） */
  Default = 1,
  /** 指定空間可見 */
  Specified = 2,
  /** 所有空間可見 */
  All = 3,
}

export interface Ability {
  /** 最大上下文長度 */
  maxContextTokens?: Int64;
  /** 最大輸入長度 */
  maxInputTokens?: Int64;
  /** 最大輸出長度 */
  maxOutputTokens?: Int64;
  /** 是否支持函數調用 */
  functionCallEnabled?: boolean;
  /** 是否支持JSON模式 */
  jsonModeEnabled?: boolean;
  /** 是否支持多模態 */
  multiModalEnabled?: boolean;
  /** 多模態能力配置 */
  multiModalAbility?: MultiModalAbility;
  /** 消息預處理hook */
  messagePreHandleHook?: RuntimeHook;
  /** 模型可用的參數配置，優先級高於原有的maxContextTokens/maxInputTokens/maxOutputTokens */
  modelParams?: Array<ModelParam>;
}

export interface CommercialModelSeries {
  iconUrl?: string;
  modelVendor?: string;
  seriesName?: string;
}

export interface CommercialModelStatusDetail {
  isNewModel?: boolean;
  isAdvancedModel?: boolean;
}

export interface GPTOpenAPIInfo {
  apiBaseURL?: string;
  apiVersion?: string;
}

export interface IDCDeployDetail {
  deployID?: string;
  /** 資源對應服務樹節點 id */
  byteNodeID?: string;
  region?: string;
  deviceType?: string;
  deviceDisplayName?: string;
  instance?: string;
}

export interface InstanceResourceOption {
  cpus?: string;
  /** 單位 GB */
  mem?: string;
  gpus?: string;
}

export interface MaasInfo {
  host?: string;
  region?: string;
  /** v3 sdk */
  baseURL?: string;
  /** 精調模型任務的 ID */
  customizationJobsID?: string;
}

export interface MerlinInfo {
  psm?: string;
  cluster?: string;
  idcs?: Array<IDC>;
  framework?: MerlinFramework;
  instanceResourceOption?: InstanceResourceOption;
  /** 資源配置 */
  deployDetailM?: Record<IDC, IDCDeployDetail>;
  /** 服務節點id */
  byteTreeNodeID?: Int64;
  /** 服務樹路徑 */
  byteTreeNodePath?: string;
  /** 服務詳情鏈接 */
  serviceDetailURL?: string;
  /** LLM 接口信息 */
  llmInterface?: MerlinLLMInterface;
  /** 是否開啓 vllm */
  useVLLMServe?: boolean;
  /** 調用 vllm 的 API 路徑，僅開啓 vllm 時使用 */
  vllmAPIPath?: string;
}

export interface Model {
  /** 模型id, 在商業化場景下可爲空，如果爲空則用identification+provider直接調用模型 */
  id?: Int64;
  /** 模型標識（name，endpoint，與各提供方對齊） */
  identification?: string;
  /** 展示名稱 */
  displayName?: string;
  /** 模型描述 */
  description?: string;
  /** 模型家族 */
  family?: Family;
  /** 提供方 */
  provider?: Provider;
  /** 提供方信息 */
  providerInfo?: ProviderInfo;
  /** 是否爲公共模型 */
  isPublic?: boolean;
  /** 可見性 */
  visibility?: Visibility;
  /** 所屬空間id */
  spaceID?: Int64;
  /** 模型能力 */
  ability?: Ability;
  /** 默認運行時參數 */
  defaultRuntimeParam?: RuntimeParam;
  /** 創建人 */
  createdBy?: string;
  /** 更新人 */
  updatedBy?: string;
  /** 創建時間 */
  createdAt?: Int64;
  /** 更新時間 */
  updatedAt?: Int64;
  /** 編輯版本（用於解決多人同時更新問題） */
  editVersion?: Int64;
  modelStatus?: ModelStatus;
  /** 模型提供方側的 model id */
  externalModelID?: string;
  /** 從精調模型任務的產出中新建推理點產生的模型 */
  sftTaskID?: Int64;
  /** 模型版本 */
  modelVersion?: string;
  /** 模型頭像 */
  modelIcon?: string;
  /** 模型公司 */
  modelVendor?: string;
  /** 模型真實名稱（展示在vendor右側，可能是豆包endpoint或其他廠商的模型名稱） */
  actualName?: string;
  /** 模型標籤 */
  modelTags?: Array<string>;
  /** 商業化模型狀態 */
  commercialModelStatus?: CommercialModelStatus;
  /** 商業化模型狀態詳情 */
  commercialModelStatusDetail?: CommercialModelStatusDetail;
  /** 商業化模型系列 */
  commercialModelSeries?: CommercialModelSeries;
}

export interface ModelParam {
  name?: string;
  label?: string;
  desc?: string;
  /** 類型： bool/int/float等 */
  modelParamType?: ModelParamType;
  min?: string;
  max?: string;
  defaultVal?: string;
  /** 枚舉 */
  modelParamOptions?: Array<ModelParamOption>;
}

export interface ModelParamOption {
  /** 展示值 */
  label?: string;
  /** 實際值 */
  value?: string;
}

export interface MultiModalAbility {
  /** [1, 99] 圖片配置
是否支持圖片 */
  imageEnabled?: boolean;
  /** 是否支持二進制圖片 */
  binaryImageEnabled?: boolean;
  /** 單張圖片大小限制, 範圍 [0, 20]MB */
  maxImageSizeInMB?: number;
  /** 最大圖片數量, 範圍 [-1, 100], -1 表示無限制 */
  maxImageCount?: number;
}

export interface ProviderInfo {
  gptOpenAPI?: GPTOpenAPIInfo;
  maas?: MaasInfo;
  merlin?: MerlinInfo;
}

export interface RuntimeCustomParam {
  name?: string;
  type?: RuntimeCustomParamType;
  value?: string;
}

export interface RuntimeHook {
  type?: RuntimeHookType;
  url?: string;
}

export interface RuntimeParam {
  /** 最大輸出長度 */
  maxTokens?: Int64;
  temperature?: number;
  topP?: number;
  topK?: Int64;
  jsonMode?: boolean;
  /** 停止詞, 值必須是json序列化後的字符串數組 */
  stopWords?: string;
  /** 運行時自定義參數 */
  runtimeCustomParams?: Array<RuntimeCustomParam>;
}

export interface Visibility {
  mode?: VisibleMode;
  /** Mode爲Specified有效，配置爲除模型所屬空間外的其他空間 */
  spaceIDs?: Array<Int64>;
}
/* eslint-enable */
