/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** BotVersionOperation 操作類型
 NEXT ID: 5 */
export enum BotVersionOperation {
  Undefined = 0,
  /** 上線 */
  Publish = 1,
  /** 修改內容 */
  Modify = 2,
  /** 下線 */
  Offline = 3,
  /** 回滾 */
  Rollback = 4,
}

export enum GrayFieldType {
  Undefined = 0,
  UID = 1,
  DID = 2,
  CustomKey = 3,
}

/** HistoryVersionStatus 描述版本狀態
 NEXT ID: 3 */
export enum HistoryVersionStatus {
  Undefined = 0,
  Valid = 1,
  InValid = 2,
}

/** HistoryVersionType 版本記錄類型
 NEXT ID: 6 */
export enum HistoryVersionType {
  Undefined = 0,
  /** 提交版本 */
  Commit = 1,
  /** 線上發佈 */
  Online = 2,
  /** 預發佈PPE */
  PrePublish = 3,
  /** 灰度發佈 */
  Gray = 4,
  /** 回滾版本 */
  Rollback = 5,
}

/** PublishVersionType 當前生效版本發佈類型
 NEXT ID: 4 */
export enum PublishVersionType {
  Undefined = 0,
  /** 線上正式版 */
  Online = 1,
  /** 預發佈PPE */
  PrePublish = 2,
  /** 灰度發佈 */
  Gray = 3,
}

export enum RuleStatus {
  UnDefined = 0,
  Online = 1,
  Offline = 2,
}

export enum VersionType {
  UnDefined = 0,
  XTtEnv = 1,
  VersionIdentifier = 2,
  Gray = 3,
}

/** 當前生效的策略 */
export interface ActiveRule {
  /** 策略id */
  rule_id?: string;
  /** 渠道信息 */
  connector_info?: ConnectorInfo;
  /** 創建人名字 */
  creator_name?: string;
  /** 創建時間 */
  create_time?: string;
  /** 版本，commit version */
  version?: string;
  /** pre類型/灰度類型 */
  version_type?: VersionType;
  /** 泳道名，VersionType=XTtEnv時用 */
  x_tt_env?: string;
  /** 版本標識，VersionType=VersionIdentifier時用 */
  version_identifier?: string;
  /** bot version，用來換取commit version */
  bot_version?: string;
  /** [Deprecated]灰度id列表，VersionType=Gray時用(灰度id列表) */
  gray_id_list?: Array<string>;
  /** 規則狀態 */
  status?: RuleStatus;
  /** 下線時間 */
  offline_time?: string;
  /** 操作人名字 */
  operator_name?: string;
  /** 灰度配置，VersionType=Gray時使用(支持黑白名單，灰度比例) */
  gray_config?: GrayConfig;
}

export interface AllowedConnector {
  id?: string;
  has_published?: boolean;
}

/** AllowList
 NEXT ID: 3 */
export interface AllowList {
  /** 比較字段 */
  field?: GrayField;
  /** 比較字段值 */
  values?: Array<string>;
}

/** BlockList
 NEXT ID: 3 */
export interface BlockList {
  /** 比較字段 */
  field?: GrayField;
  /** 比較字段值 */
  values?: Array<string>;
}

/** BotHistoryVersion 版本歷史
 NEXT ID: 14 */
export interface BotHistoryVersion {
  /** 記錄id */
  history_id?: string;
  /** 記錄類型 */
  history_version_type?: HistoryVersionType;
  /** 創建人信息 */
  creator?: Creator;
  /** 創建時間 */
  create_time?: string;
  /** 版本說明 */
  remark?: string;
  /** 渠道信息, 提交版本沒有此項 */
  connector_infos?: Array<ConnectorInfo>;
  /** bot發佈版本號 */
  bot_version?: string;
  /** 版本對應的提交版本號 */
  commit_version?: string;
  /** 當前版本狀態 */
  history_version_status?: HistoryVersionStatus;
  /** 預發佈PPE的env名稱 */
  x_tt_env?: string;
  /** [Deprecated]灰度id列表 */
  gray_id_list?: Array<string>;
  /** 下線時間 */
  offline_time?: string;
  /** 規則ID */
  rule_id?: string;
  /** 發佈時候的id, commit操作沒有 */
  publish_id?: string;
  /** 灰度配置，VersionType=Gray時使用(支持黑白名單，灰度比例) */
  gray_config?: GrayConfig;
}

/** BotOperationHistory 歷史操作
 NEXT ID: 14 */
export interface BotOperationHistory {
  /** 記錄id */
  history_id?: string;
  /** 操作類型 */
  bot_version_operation?: BotVersionOperation;
  /** 記錄類型 */
  history_version_type?: HistoryVersionType;
  /** 操作人信息 */
  creator?: Creator;
  /** 操作時間 */
  create_time?: string;
  /** 版本說明 */
  remark?: string;
  /** 渠道信息, 提交版本沒有此項 */
  connector_infos?: Array<ConnectorInfo>;
  /** bot發佈版本號 */
  bot_version?: string;
  /** 版本對應的提交版本號 */
  commit_version?: string;
  /** 當前生效狀態 */
  history_version_status?: HistoryVersionStatus;
  /** 預發佈PPE的env名稱 */
  x_tt_env?: string;
  /** [Deprecated]灰度id列表 */
  gray_id_list?: Array<string>;
  /** 規則ID */
  rule_id?: string;
  /** 發佈時候的id, commit操作沒有 */
  publish_id?: string;
  /** 灰度配置，VersionType=Gray時使用(支持黑白名單，灰度比例) */
  gray_config?: GrayConfig;
}

/** BotPublishVersion 當前生效發佈版本信息
 NEXT ID: 11 */
export interface BotPublishVersion {
  bot_id?: string;
  /** 渠道信息 */
  connector_info?: ConnectorInfo;
  /** 創建人信息 */
  creator?: Creator;
  /** 創建時間 */
  create_time?: string;
  /** 版本說明 */
  remark?: string;
  /** 發佈版本類型 */
  publish_version_type?: PublishVersionType;
  /** bot發佈版本號 */
  bot_version?: string;
  /** 版本對應的提交版本號 */
  commit_version?: string;
  /** PPE和灰度發佈關聯的規則ID */
  rule_id?: string;
  /** PPE預發佈，表示泳道名字 */
  x_tt_env?: string;
  /** [Deprecated]灰度id列表，VersionType=Gray時用(灰度id列表) */
  gray_id_list?: Array<string>;
  /** 發佈時候的id */
  publish_id?: string;
  /** 是否支持回滾 */
  support_rollback?: boolean;
  /** 灰度配置，VersionType=Gray時使用(支持黑白名單，灰度比例) */
  gray_config?: GrayConfig;
}

export interface ConnectorInfo {
  id?: string;
  /** 渠道名 */
  name?: string;
  /** 渠道圖標 */
  icon?: string;
}

/** Creator 用戶信息
 NEXT ID: 4 */
export interface Creator {
  id?: string;
  name?: string;
  avatar_url?: string;
}

/** GrayBucket 百分比灰度配置
 NEXT ID: 4 */
export interface GrayBucket {
  /** 灰度計算字段 */
  field?: GrayField;
  /** 灰度比例, 取[0, size]的大小 */
  in_gray?: number;
  /** bucket 大小, 默認10000 */
  size?: number;
}

/** GrayConfig 灰度配置
 目前順序爲 BlockList -> AllowList -> Bucket的校驗順序
 NEXT ID: 4 */
export interface GrayConfig {
  /** 在blockList中的表示不命中 */
  block_list?: BlockList;
  /** 在allowList中的表示命中，未命中的走bucket */
  allow_list?: AllowList;
  /** 百分比灰度配置 */
  bucket?: GrayBucket;
}

export interface GrayField {
  /** 灰度字段類型 */
  type: GrayFieldType;
  /** 自定義字段json path */
  custom_field_path?: string;
}
/* eslint-enable */
