/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as resource_common from './resource_common';

export type Int64 = string | number;

export interface LibraryResourceListRequest {
  /** 是否由當前用戶創建，0-不篩選，1-當前用戶 */
  user_filter?: number;
  /** [4,1]   0代表不篩選 */
  res_type_filter?: Array<number>;
  /** 名稱 */
  name?: string;
  /** 發佈狀態，0-不篩選，1-未發佈，2-已發佈 */
  publish_status_filter?: number;
  /** 用戶所在空間ID */
  space_id: string;
  /** 6 : optional i32 page, // 頁數，首頁是1。默認1。
一次讀取的數據條數，默認10，最大100. */
  size?: number;
  /** 8 : optional i32 offset, // 數據記錄偏移，含義是從第(offset+1)條記錄開始讀
遊標，用於分頁，默認0，第一次請求可以不傳，後續請求需要帶上上次返回的cursor */
  cursor?: string;
  /** 用來指定自定義搜索的字段 不填默認只name匹配，eg []string{name,自定} 匹配name和自定義字段full_text */
  search_keys?: Array<string>;
  /** 當res_type_filter爲[2 workflow]時，是否需要返回圖片流 */
  is_get_imageflow?: boolean;
  Base?: base.Base;
}

export interface LibraryResourceListResponse {
  code?: Int64;
  msg?: string;
  resource_list?: Array<resource_common.ResourceInfo>;
  /** 4  : i32 total,
遊標，用於下次請求的cursor */
  cursor?: string;
  /** 是否還有數據待拉取 */
  has_more?: boolean;
  BaseResp: base.BaseResp;
}
/* eslint-enable */
