/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum AuditStatus {
  /** 審覈中 */
  Processing = 0,
  /** 審覈通過 */
  Enable = 1,
  /** 審覈不通過 */
  Disable = 2,
  /** 歷史存量數據 */
  Default = 100,
}

export enum CaptionType {
  /** 智能標註 */
  Auto = 0,
  /** 人工標註 */
  Manual = 1,
}

export enum ChunkType {
  DefaultChunk = 0,
  CustomChunk = 1,
  LevelChunk = 2,
}

export enum ContentSchema {
  DefaultSchema = 0,
  LinkReaderSchema = 1,
}

export enum DataSetStatus {
  DataSetprocessing = 0,
  DataSetReady = 1,
  DataSetFailed = 9,
}

export enum DocumentSource {
  /** 本地文件上傳 */
  Document = 0,
  /** url */
  Web = 1,
  /** 自定義類型 */
  Custom = 2,
  /** 三方 */
  ThirdParty = 3,
  /** 前端抓取 */
  FrontCrawl = 4,
  /** openapi */
  OpenApi = 5,
  Notion = 101,
  GoogleDrive = 102,
  FeishuWeb = 103,
  LarkWeb = 104,
  WeChat = 109,
}

export enum DocumentStatus {
  /** 上傳中 */
  Processing = 0,
  /** 生效 */
  Enable = 1,
  /** 失效 */
  Disable = 2,
  /** 刪除 */
  Deleted = 3,
  /** 重新分片中，前端和上游不感知該狀態 */
  Resegment = 4,
  /** 刷新中（刷新成功後會刪除） */
  Refreshing = 5,
  /** 失敗 */
  Failed = 9,
  /** 機審失敗 */
  AuditFailed = 1000,
}

/** 兼容保留，使用 DocumentStatus 替代 */
export enum DocumentType {
  /** 上傳中 */
  Processing = 0,
  /** 生效 */
  Enable = 1,
  /** 失效 */
  Disable = 2,
  /** 刪除 */
  Deleted = 3,
  /** 失敗 */
  Failed = 9,
}

/** 類型 */
export enum FormatType {
  /** 文本 */
  Text = 0,
  /** 表格 */
  Table = 1,
  /** 圖片 */
  Image = 2,
  /** 數據庫 */
  Database = 3,
  /** 火山結構化 火山知識庫特有 */
  VolcanoStructured = 4,
  /** 火山非結構化 火山知識庫特有 */
  VolcanoUnstructured = 5,
  /** 火山數據庫 */
  VolcanoDatabase = 6,
}

export enum FrequencyType {
  /** 不更新 */
  None = 0,
  /** 每天追加最新 */
  EveryDay = 1,
  /** 每三天追加最新 */
  EveryThreeDay = 2,
  /** 每七天追加最新 */
  EverySevenDay = 3,
}

export enum Operation {
  /** "=" */
  EQUAL = 1,
  /** "<>" 或 "!=" */
  NOT_EQUAL = 2,
  /** ">" */
  GREATER_THAN = 3,
  /** "<" */
  LESS_THAN = 4,
  /** ">=" */
  GREATER_EQUAL = 5,
  /** "<=" */
  LESS_EQUAL = 6,
  /** "IN" */
  IN = 7,
  /** "NOT IN" */
  NOT_IN = 8,
}

/** 排序字段 */
export enum OrderField {
  CreateTime = 1,
  UpdateTime = 2,
}

/** 排序規則 */
export enum OrderType {
  Desc = 1,
  Asc = 2,
}

export enum ParamSource {
  /** 默認用戶輸入 */
  Input = 0,
  /** 引用變量 */
  Variable = 1,
}

export enum ParsingType {
  /** 快速解析 */
  FastParsing = 0,
  /** 精準解析 */
  AccurateParsing = 1,
}

export enum ReviewStatus {
  /** 處理中 */
  Processing = 0,
  /** 已完成 */
  Enable = 1,
  /** 失敗 */
  Failed = 2,
  /** 失敗 */
  ForceStop = 3,
}

export enum StorageLocation {
  Default = 0,
  OpenSearch = 1,
  Douyin = 2,
}

export enum TabType {
  /** list<string> */
  ListString = 1,
  /** string */
  String = 2,
  /** int64 */
  Integer = 3,
  /** float32 */
  Float = 4,
  /** bool */
  Boolean = 5,
}

/** 更新類型 */
export enum UpdateType {
  NoUpdate = 0,
  Cover = 1,
  Append = 2,
}

export enum VolcanoDatasetServiceStatus {
  DatasetServiceValid = 0,
  DatasetServiceInvalid = 1,
}

export enum VolcanoDatasetStatus {
  DatasetValid = 0,
  DatasetInvalid = 1,
}

export enum VolcanoDatasetType {
  /** 標準版 */
  Standard = 1,
  /** 旗艦版 */
  Ultimate = 2,
}

export enum WebStatus {
  /** 處理中 */
  Handling = 0,
  /** 已完成 */
  Finish = 1,
  /** 失敗 */
  Failed = 2,
}

export interface ChunkStrategy {
  separator?: string;
  max_tokens?: Int64;
  remove_extra_spaces?: boolean;
  remove_urls_emails?: boolean;
  /** 如果爲0, 則不使用以上字段的配置 */
  chunk_type?: ChunkType;
  /** 1 鏈接閱讀器 (cici 長文) */
  content_schema?: ContentSchema;
  /** 圖片類型，圖片描述文字的標註方式 */
  caption_type?: CaptionType;
  /** 分段重疊度 */
  overlap?: Int64;
  /** 最大層級數（按層級分段時生效） */
  max_level?: Int64;
  /** 切片保留層級標題（按層級分段時生效） */
  save_title?: boolean;
}

export interface FilterStrategy {
  /** 過濾頁數 */
  filter_page?: Array<number>;
  /** 過濾框位置 */
  filter_box_position?: Array<number>;
}

export interface IndexStrategy {
  /** 是否開啓向量索引（默認爲true） */
  vector_indexing?: boolean;
  /** 是否開啓關鍵詞索引（默認爲true） */
  keyword_indexing?: boolean;
  /** 是否開啓分層索引 */
  hierarchical_indexing?: boolean;
  /** 向量模型 */
  model?: string;
}

export interface OpenSearchConfig {
  region?: string;
  instance_id?: string;
  public_endpoint?: string;
  username?: string;
  password?: string;
  instance_name?: string;
}

export interface ParsingStrategy {
  /** 解析類型 */
  parsing_type?: ParsingType;
  /** 是否開啓圖片元素提取（精準解析時生效） */
  image_extraction?: boolean;
  /** 是否開啓表格元素提取（精準解析時生效） */
  table_extraction?: boolean;
  /** 是否開啓圖片OCR（精準解析時生效） */
  image_ocr?: boolean;
}

export interface SinkStrategy {
  /** 是否檢查索引成功 */
  check_index?: boolean;
}

export interface StorageStrategy {
  storage_location: StorageLocation;
  open_search_config?: OpenSearchConfig;
}

export interface TabValue {
  type?: TabType;
  /** 本地默認值 */
  local_input?: string;
  /** 入參的來源 */
  param_source?: ParamSource;
  /** 引用variable的key */
  variable_ref?: string;
}

export interface VolcanoDataset {
  /** 火山側知識庫id 字符串 */
  id?: string;
  /** 名稱 */
  name?: string;
  /** 類型 結構化 or 非結構化知識庫 */
  format_type?: FormatType;
  /** 火山知識庫詳情鏈接 */
  link?: string;
  /** 火山知識庫狀態 是否已失效 */
  status?: VolcanoDatasetStatus;
  desc?: string;
  /** 火山知識庫版本 */
  version?: VolcanoDatasetType;
  /** 標籤信息（標籤名和標籤信息） */
  tab_info?: Record<string, VolcanoDatasetTabInfo>;
}

export interface VolcanoDatasetProject {
  /** 目前只需要項目名稱 */
  name?: string;
  /** 火山知識庫空間跳轉鏈接 */
  link?: string;
}

export interface VolcanoDatasetService {
  /** 火山側知識服務id 字符串 */
  id?: string;
  /** 名稱 */
  name?: string;
  /** 火山知識服務鏈接 */
  link?: string;
  /** 火山知識庫狀態 是否已失效 */
  status?: VolcanoDatasetServiceStatus;
  desc?: string;
}

export interface VolcanoDatasetTabInfo {
  name?: string;
  type?: TabType;
  /** 枚舉值列表 */
  enumerated_val_list?: Array<string>;
}
/* eslint-enable */
