/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';

export type Int64 = string | number;

export enum DocSourceType {
  DocSourceTypeDrive = 1,
  DocSourceTypeWiki = 2,
  DocSourceTypeWeChat = 3,
}

export enum FileNodeType {
  Folder = 1,
  Document = 2,
  Sheet = 3,
  Space = 4,
}

export enum TimeFilterEnum {
  TimeUnlimited = 0,
  WithinAWeek = 1,
  WithinAMonth = 2,
  WithinAYear = 3,
}

export interface FileNode {
  file_id?: string;
  file_node_type?: FileNodeType;
  file_name?: string;
  has_children_nodes?: boolean;
  children_nodes?: Array<FileNode>;
  icon?: string;
  file_type?: string;
  file_url?: string;
  /** wiki, 知識空間id */
  space_id?: string;
  /** wiki, 表示知識空間類型（團隊空間 或 個人空間） */
  space_type?: string;
  /** wiki, 對應文檔類型的token，可根據 obj_type 判斷屬於哪種文檔類型 */
  obj_token?: string;
  /** wiki, 文檔類型，對於快捷方式，該字段是對應的實體的obj_type */
  obj_type?: string;
  create_time?: Int64;
  update_time?: Int64;
}

export interface GetFileTreeDocListRequest {
  auth_id: string;
  file_type_list: Array<FileNodeType>;
  folder_id?: string;
  page_token?: string;
  space_id?: string;
  doc_source_type: DocSourceType;
  /** 本次新增 */
  time_filter?: TimeFilterEnum;
  search_keywords?: string;
  /** 強制獲取最新，拉增量 */
  force_get_latest?: boolean;
  /** 本次新增 */
  page_size?: Int64;
  Base?: base.Base;
}

export interface GetFileTreeDocListResponse {
  /** 三方數據平臺文件列表 */
  file_tree_doc_list?: Array<FileNode>;
  /** 是否還有下一頁 */
  has_more?: boolean;
  /** 分頁token */
  page_token?: string;
  TotalCount?: Int64;
  code: Int64;
  msg: string;
}

export interface SearchDocumentRequest {
  auth_id: string;
  search_query: string;
  file_type_list: Array<FileNodeType>;
  doc_source_type: DocSourceType;
  page_token?: string;
  offset?: Int64;
  Base?: base.Base;
}

export interface SearchDocumentResponse {
  documents?: Array<FileNode>;
  HasMore?: boolean;
  PageToken?: string;
  OffSet?: Int64;
  BaseResp?: base.BaseResp;
}
/* eslint-enable */
