/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as copilot_common from './copilot_common';

export type Int64 = string | number;

export enum ActionType {
  MarkplaceTopUp = 1,
  ConsumeByRecord = 2,
  IncentiveTopUp = 3,
  OpPlatformTopUp = 4,
  RecordAutoTopUp = 5,
  MarkplaceRefund = 6,
  MarkplaceChargeBack = 7,
  MarkplaceChargeBackReverse = 8,
}

export enum AdminListConfParamType {
  ParamStruct = 1,
  SingleParam = 2,
}

export enum AdminListConfSortType {
  /** 升序 */
  Asc = 1,
  /** 降序 */
  Desc = 2,
}

export enum AgentType {
  Bot = 1,
  Workflow = 2,
}

export enum AggregratedType {
  Daily = 1,
}

export enum BabiBillStatus {
  Open = 1,
  Close = 2,
  ReOpen = 3,
}

export enum CheckConfOpGuardResultType {
  Pass = 1,
  Block = 2,
  Checking = 3,
}

export enum CheckConfOpReleaseTimeResultType {
  Pass = 1,
  Block = 2,
}

export enum CheckResourceResultType {
  Pass = 1,
  Block = 2,
}

export enum Dimension {
  User = 1,
  Model = 2,
  Space = 3,
  Chain = 4,
  Connector = 5,
  VolcAcc = 6,
  APISpace = 7,
  /** 用戶維度限速（指定空間生效，和未指定空間的用戶維度限速互斥，指定空間的優先級更高） */
  UserWithSpace = 101,
}

export enum HitLimitAction {
  Pass = 1,
  Block = 2,
  Downgrade = 3,
}

export enum LimitConfOpStatus {
  /** 處理中 */
  Processing = 0,
  /** 已完成 */
  Completed = 1,
  /** 已駁回 */
  Rejected = 2,
  /** 已取消 */
  Canceled = 3,
  /** 已回滾 */
  Rollback = 4,
}

export enum LimitConfOpType {
  BatchCreate = 1,
  Update = 2,
  BatchUpdate = 3,
  UpdateWithSpace = 4,
  BatchUpdateWithSpace = 5,
}

export enum LimitConfStatus {
  Effective = 0,
  Observe = 1,
}

export enum LimitType {
  QPS = 1,
  QPM = 2,
}

export enum MemberType {
  UnknownMemberType = 0,
  UserName = 1,
  UserId = 2,
}

export enum OwnerType {
  Developer = 1,
  ByteTreeNode = 2,
}

export enum PkgTypeScope {
  AllPkgType = 0,
  /** 內測包 */
  InhouseOrTest = 1,
  /** 正式包 */
  Release = 2,
}

export enum RecordScene {
  /** project入口 */
  ProjectEntrance = 1,
  /** 帶fc的模型節點調用 */
  LLMNodeWithFC = 2,
}

export enum RecordType {
  Query = 1,
  Workflow = 2,
  Token = 3,
  Dataset = 4,
  QueryFinish = 5,
  Model = 6,
  Plugin = 7,
  /** project調試 */
  ProjectTest = 8,
  /** [上報類型][上報場景-3位][上報階段-3位]
如QueryChat=1001001，1-表示query上報，001-表示對話，001-表示對話開始
對話開始請求 */
  ChatQueryStart = 1001001,
}

export enum ReportType {
  TokenReport = 1,
  QueryReport = 2,
}

export enum ResourceBlockType {
  /** 智能體調用按量餘額不足 */
  VolcAgentReqOutOfBalance = 101001,
  /** 智能體調用超出RPM峯值 */
  VolcAgentReqOutOfRPM = 101002,
}

export enum ResourceType {
  CozeToken = 1,
  UserMessage = 2,
}

export enum ResultType {
  Pass = 1,
  ModelBlock = 2,
  UserBlock = 3,
  Downgrade = 4,
  CozeAPIKeyOwnerBlock = 5,
  /** coze token額度不足 */
  OutOfResource = 6,
  /** 空間維度限速 */
  SpaceBlock = 7,
  /** 回覆降速 */
  SlowDown = 8,
  /** chain維度限速 */
  ChainBlock = 9,
  /** chain維度限速 */
  ConnectorBlock = 10,
  /** 火山賬號維度限速（僅國內專業版有） */
  VolcAccBlock = 11,
}

export enum TimeUnit {
  Second = 1,
  Minute = 2,
  Hour = 3,
  Day = 4,
  Month = 5,
  Year = 6,
  TenSecond = 7,
}

export enum TrafficActionType {
  Pass = 1,
  Block = 2,
}

export enum TrafficCfgStatus {
  Deleted = 1,
  Deactivated = 2,
  Observe = 3,
  Effective = 4,
}

export enum TrafficParamKeyFormatType {
  Each = 1,
  All = 2,
}

export enum TrafficParamType {
  Number = 1,
  String = 2,
}

export enum TrafficParamValueConditionType {
  Null = 1,
  NotNull = 2,
  Valid = 3,
  Invalid = 4,
  InList = 5,
  NotInList = 6,
  InNumRange = 7,
  NotInNumRange = 8,
}

export enum TrafficResourceType {
  /** 火山智能體調用（coze專業版） */
  VolcAgentReq = 101,
}

export enum TrafficRuleType {
  CntWithTime = 1,
  CntWithTimeFromVolcAgtReq = 101,
}

export enum TypeOfUpdateConfWithOp {
  /** 配置 */
  ConfigConf = 1,
  /** 回滾 */
  RollbackConf = 2,
}

export enum UserMessageResourceID {
  BotAsAPI = 1,
  WebSDK = 2,
}

export enum WhitelistType {
  UnknownWhitelistType = 0,
  /** coze白名單，如果請求渠道是coze，且用戶在白名單內，跳過所有限速 */
  Coze = 1,
}

export interface Action {
  /** 動作類型 */
  action_type?: ActionType;
  /** 動作對應的ID */
  action_id?: string;
  /** 更新餘額對應的描述 */
  messsage?: string;
  /** 更新餘額對應的starling key，通過starling key拉到對應文案，格式化amount字段 */
  starling_key?: string;
}

export interface AddModelAKReq {
  space_id?: string;
  model_ak?: ModelAK;
  Base?: base.Base;
}

export interface AddModelAKResp {
  code?: Int64;
  msg?: string;
}

export interface AdminCheckConfOpGuardData {
  result_type?: CheckConfOpGuardResultType;
  desc?: string;
}

export interface AdminCheckConfOpGuardReq {
  op_id?: string;
  op_creator?: string;
  'X-Jwt-Token-Acl-Acc'?: string;
  Base?: base.Base;
}

export interface AdminCheckConfOpGuardResp {
  data?: AdminCheckConfOpGuardData;
  code?: string;
  message?: string;
}

export interface AdminCheckConfOpReleaseTimeData {
  result_type?: CheckConfOpReleaseTimeResultType;
  desc?: string;
}

export interface AdminCheckConfOpReleaseTimeReq {
  op_id?: string;
  op_creator?: string;
  'X-Jwt-Token-Acl-Acc'?: string;
  Base?: base.Base;
}

export interface AdminCheckConfOpReleaseTimeResp {
  data?: AdminCheckConfOpReleaseTimeData;
  code?: string;
  message?: string;
}

export interface AdminListConfBpmDetail {
  id?: string;
  op_type?: string;
  op_status?: string;
  bpm?: string;
  op_operator?: string;
  op_reason?: string;
  create_time?: string;
  update_time?: string;
}

export interface AdminListConfDetail {
  id?: string;
  dimension?: string;
  connector?: string;
  model?: string;
  source?: string;
  scene?: string;
  pkg_type_scope?: string;
  limit?: string;
  space?: string;
  action?: string;
  active?: string;
  operator?: string;
  config_reason?: string;
  create_time?: string;
  update_time?: string;
  ori_limitation?: Int64;
  ori_time_unit?: number;
  ori_source?: number;
  ori_scene?: number;
  ori_pkg_type_scope?: number;
  ori_active?: boolean;
  volc_acc_id?: string;
  cfg_status?: string;
  ori_cfg_status?: number;
  lane_type?: string;
}

export interface AdminListConfParam {
  dimension?: Array<Dimension>;
  connector_id?: Array<string>;
  time_unit?: Array<TimeUnit>;
  model_id?: Array<string>;
  source?: Array<copilot_common.SourceType>;
  scene?: Array<copilot_common.LLMScene>;
  space_id?: Array<string>;
  action?: Array<HitLimitAction>;
  active?: boolean;
  pkg_type_scope?: Array<PkgTypeScope>;
  sort_type?: AdminListConfSortType;
  sort_field?: Array<string>;
}

export interface AdminUpdateConfOpReq {
  op_id?: string;
  op_status?: LimitConfOpStatus;
  'X-Jwt-Token-Acl-Acc'?: string;
  Base?: base.Base;
}

export interface AdminUpdateConfOpResp {
  code?: string;
  message?: string;
}

export interface AdminUpdateConfWithOpReq {
  op_id?: string;
  update_type?: TypeOfUpdateConfWithOp;
  'X-Jwt-Token-Acl-Acc'?: string;
  Base?: base.Base;
}

export interface AdminUpdateConfWithOpResp {
  code?: string;
  message?: string;
}

export interface APISpaceLiftInfo {
  connector_id?: Int64;
  pkg?: PkgTypeScope;
  lane_type?: string;
}

export interface CheckResourceResult {
  /** 檢查結果 */
  result_type?: CheckResourceResultType;
  /** 當resulr=Block時，該字段有值 */
  block_info?: ResourceBlockInfo;
}

export interface CozeBalanceDetail {
  /** 資源類型 */
  resource_type?: ResourceType;
  /** 餘額數量 */
  amount?: Int64;
  /** 最近的流水號 */
  last_transaction_id?: Int64;
  /** 最近更新時間戳 */
  updated_at?: Int64;
  /** 資源ID */
  resource_id?: string;
}

export interface CozeBillDetail {
  /** 賬單的時間戳 */
  timestamp?: Int64;
  /** 聚合賬單結束時間戳 */
  end_timestamp?: Int64;
  /** 資源類型 */
  resource_type?: ResourceType;
  /** 變動數量，爲正是增加，爲負是減少 */
  amount?: Int64;
  /** 更新餘額對應的starling key，通過starling key拉到對應文案，格式化amount字段 */
  starling_key?: string;
  /** 更新餘額對應的描述 */
  messsage?: string;
  /** 聚合賬單時返回多個對應的actions，數據過多時不返回，不要取Action中的message和starling key */
  actions?: Array<Action>;
}

export interface DeleteModelAKReq {
  space_id?: string;
  ak_id?: string;
  Base?: base.Base;
}

export interface DeleteModelAKResp {
  code?: Int64;
  msg?: string;
}

export interface GetUserWithSpaceLimitReq {
  space_id?: string;
}

export interface GetUserWithSpaceLimitResp {
  limits?: Array<UserWithSpaceModelLimit>;
  code?: Int64;
  msg?: string;
}

export interface LimitConf {
  limit_type?: LimitType;
  limitation?: string;
}

export interface ListModelAKReq {
  space_id?: string;
  Base?: base.Base;
}

export interface ListModelAKResp {
  model_aks?: Array<ModelAK>;
  code?: Int64;
  msg?: string;
}

export interface MGetSpaceLimitReq {
  space_ids?: Array<string>;
}

export interface MGetSpaceLimitResp {
  limit_map?: Record<Int64, SpaceLimit>;
  code?: Int64;
  msg?: string;
}

export interface ModelAK {
  id?: string;
  model_family?: copilot_common.ModelFamily;
  name?: string;
  ak?: string;
  sk?: string;
  sts?: string;
}

export interface ModelTokenToCozeToken {
  /** 每1k輸入token需要多少coze token */
  input_token_to_coze_token?: Int64;
  /** 每1k輸出token需要多少coze token */
  output_token_to_coze_token?: Int64;
}

export interface NumRange {
  min_num?: string;
  max_num?: string;
}

export interface QueryReportInfo {
  cnt?: Int64;
}

export interface ReportInfo {
  /** 1-Token */
  report_type?: ReportType;
  /** // report_type=Token時，該字段有值 */
  token_info?: TokenReportInfo;
  /** report_type=Query時，該字段有值 */
  query_info?: QueryReportInfo;
}

export interface ResourceAmount {
  /** 資源類型 */
  resource_type?: ResourceType;
  /** 變動數量，爲正是增加，爲負是減少 */
  amount?: Int64;
}

export interface ResourceBlockInfo {
  block_type?: ResourceBlockType;
}

export interface ResourceRevertInfo {
  check_and_update_uuid?: string;
  check_and_update_timestamp?: Int64;
}

export interface SetSpaceLimitReq {
  limit_confs?: Array<LimitConf>;
  space_id?: string;
}

export interface SetSpaceLimitResp {
  code?: Int64;
  msg?: string;
}

export interface SetUserWithSpaceLimitReq {
  space_id?: string;
  limits?: Array<UserWithSpaceModelLimit>;
}

export interface SetUserWithSpaceLimitResp {
  code?: Int64;
  msg?: string;
}

export interface SlowDownConf {
  /** 首Token延長毫秒 */
  FirstTokenDelayMilliSec?: Int64;
  /** 包間距延長毫秒 */
  PacketDelayMilliSec?: Int64;
}

export interface SpaceLimit {
  can_limit?: boolean;
  need_limit?: boolean;
  limit_confs?: Array<LimitConf>;
}

export interface TimestampRange {
  /** 開始時間，毫秒級別時間戳 */
  start_timestamp_ms: Int64;
  /** 結束時間，毫秒級別時間戳 */
  end_timestamp_ms: Int64;
}

export interface TokenReportInfo {
  cnt?: Int64;
  input_cnt?: Int64;
  output_cnt?: Int64;
}

/** 指定空間生效的用戶維度限速 */
export interface UserWithSpaceModelLimit {
  model_id?: string;
  model_name?: string;
  time_unit?: TimeUnit;
  limitation?: string;
  limitation_range?: NumRange;
  default_limitation?: string;
}

export interface WhitelistInfo {
  id?: string;
  whitelist_type?: string;
  member_type?: string;
  member?: string;
  description?: string;
}
/* eslint-enable */
