/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';

export type Int64 = string | number;

export enum CozePunishTaskStatus {
  Success = 0,
  Fail = 1,
}

/** 創建處罰措施 */
export enum PunishMeasureStatus {
  Testing = 0,
  Online = 1,
  Disabled = 2,
}

export enum PunishRecordStatus {
  ongoing = 0,
  end = 1,
  init = 2,
  failed = 3,
}

export enum PunishSource {
  Op = 1,
  System = 2,
}

export enum PunishStatus {
  normal = 1,
  banned = 2,
}

export enum PunishTaskStatus {
  processing = 0,
  success = 1,
  fail = 2,
  partial_success = 3,
}

/** 創建處罰任務 */
export enum PunishTaskType {
  Punish = 1,
  Unpunish = 2,
}

export enum UnPunishAllowConfig {
  Allow = 0,
  ForBid = 1,
}

export interface CozePunishRequest {
  /** 處罰措施id，通過這個id來選擇執行哪個處罰 */
  PunishMeasureID: Int64;
  /** 處罰對象id列表 */
  ObjectIDs: Array<string>;
  /** 處罰人uid */
  OperatorUID?: Int64;
  /** 處罰人郵箱 */
  OperatorEmail?: string;
  /** 處罰源 */
  Source?: string;
  /** 處罰持續時間 */
  Duration?: Int64;
  /** 處罰原因 */
  Remark?: string;
  /** 處罰任務ID */
  PunishTaskID?: Int64;
  Base?: base.Base;
}

export interface CozePunishResponse {
  /** 處罰系統無法感知和校驗處罰對象id，需要接入方返回處罰結果
key:對象id；value:處罰結果 */
  PunishResultMap: Record<string, CozePunishTaskResult>;
  BaseResp?: base.BaseResp;
}

export interface CozePunishTaskResult {
  status: CozePunishTaskStatus;
}

export interface CozeUnPunishRequest {
  PunishMeasureID: Int64;
  ObjectIDs: Array<string>;
  OperatorUID?: Int64;
  OperatorEmail?: string;
  Source?: string;
  Remark?: string;
  /** 解除處罰任務ID */
  PunishTaskID?: Int64;
  Base?: base.Base;
}

export interface CozeUnPunishResponse {
  UnPunishResultMap: Record<string, CozePunishTaskResult>;
  BaseResp?: base.BaseResp;
}

export interface CreatePunishMeasureData {
  punish_measure_id: string;
}

export interface CreatePunishMeasureRequest {
  /** 處罰主體 */
  punish_entity: string;
  /** 處罰效果 */
  punish_effect: string;
  /** 是否允許手動解除處罰 */
  allow_unpunish: UnPunishAllowConfig;
  /** 處罰持續時間 */
  punish_duration: Int64;
  /** 接入psm */
  psm: string;
  /** IDL分支 */
  idl_branch?: string;
  /** 處罰措施名稱 */
  punish_name: string;
}

export interface CreatePunishMeasureResponse {
  data: CreatePunishMeasureData;
  code: Int64;
  msg: string;
}

export interface CreatePunishTaskRequest {
  /** 處罰主體 */
  punish_entity: string;
  /** 處罰措施 */
  punish_messure_id: string;
  /** 處罰任務類型 */
  type: PunishTaskType;
  /** 處罰時長，不傳則使用處罰措施默認時長;-1代表永久 */
  punish_duration?: Int64;
  /** 處罰對象列表 */
  punish_object_ids: Array<string>;
  /** 處罰原因 */
  remark: string;
  /** 處罰來源 */
  punish_source: PunishSource;
}

export interface CreatePunishTaskResponse {
  code: Int64;
  msg: string;
}

export interface GetPunishMeasureData {
  /** 總條數 */
  total: Int64;
  /** 處罰措施列表 */
  punish_measures: Array<PunishMeasure>;
}

/** 獲取處罰措施 */
export interface GetPunishMeasureRequest {
  /** 根據主體類型篩選處罰措施（給處罰執行頁面用的） */
  punish_entity?: string;
  /** 分頁 */
  page?: number;
  /** 分頁大小 */
  size?: number;
}

export interface GetPunishMeasureResponse {
  data: GetPunishMeasureData;
  code: Int64;
  msg: string;
}

/** 獲取處罰元信息 */
export interface GetPunishMetaInfoRequest {}

export interface GetPunishMetaInfoResponse {
  data: PunishMetaInfo;
  code: Int64;
  msg: string;
}

export interface GetPunishRecordData {
  /** 總條數 */
  total: Int64;
  /** 處罰數據列表 */
  punish_records: Array<PunishRecord>;
}

/** 查詢處罰數據 */
export interface GetPunishRecordRequest {
  punish_entity?: string;
  object_ids?: Array<string>;
  status?: PunishRecordStatus;
  /** 分頁 */
  page?: number;
  /** 分頁大小 */
  size?: number;
}

export interface GetPunishRecordResponse {
  data?: GetPunishRecordData;
  code: Int64;
  msg: string;
}

export interface GetPunishTaskData {
  /** 總條數 */
  total: Int64;
  /** 處罰措施列表 */
  punish_tasks: Array<PunishTask>;
}

/** 查看處罰任務 */
export interface GetPunishTaskRequest {
  punish_entity?: string;
  punish_type?: PunishTaskType;
  /** 前綴匹配 */
  operator_email?: string;
  /** 分頁 */
  page?: number;
  /** 分頁大小 */
  size?: number;
}

export interface GetPunishTaskResponse {
  data?: GetPunishTaskData;
  code: Int64;
  msg: string;
}

export interface MGetEntityPunishStatusRequest {
  /** 處罰實體枚舉 */
  EntityNum: Int64;
  /** 對應處罰措施 */
  PunishMeasureID: Int64;
  /** 處罰對象列表 */
  ObjectIDs: Array<string>;
  Base?: base.Base;
}

export interface MGetEntityPunishStatusResponse {
  PunishStatusMap: Record<string, PunishStatusInfo>;
  BaseResp: base.BaseResp;
}

export interface PunishMeasure {
  /** 處罰措施id */
  punish_measure_id?: string;
  /** 處罰措施名稱 */
  punish_name?: string;
  /** 處罰主體 */
  punish_entity?: string;
  /** 處罰效果 */
  punish_effect?: string;
  /** 是否允許手動解除處罰 */
  allow_unpunish?: UnPunishAllowConfig;
  /** 創建人郵箱 */
  creator?: string;
  /** 處罰持續時間 */
  punish_duration?: Int64;
  /** 接入psm */
  psm?: string;
  /** IDL分支 */
  idl_branch?: string;
  /** 處罰措施狀態 */
  status?: PunishMeasureStatus;
  /** 創建時間 */
  create_time?: Int64;
  /** 更新時間 */
  update_time?: Int64;
}

export interface PunishMetaInfo {
  /** 處罰主體 */
  punish_entity_list: Array<string>;
  /** 可選處罰持續時間 */
  avaliable_punish_durations: Array<Int64>;
}

export interface PunishRecord {
  /** 任務id */
  task_id?: string;
  /** 處罰措施id */
  punish_measure_id?: string;
  /** 處罰措施名稱 */
  punish_messure_name?: string;
  /** 處罰主體 */
  punish_entity?: string;
  /** 處罰對象 */
  object_id?: string;
  /** 創建人郵箱 */
  punisher?: string;
  /** 處罰持續時間 */
  punish_duration?: Int64;
  /** 處罰解除人郵箱 */
  unpunisher?: string;
  /** 處罰原因 */
  remark?: string;
  /** 處罰狀態 */
  status?: PunishRecordStatus;
  /** 處罰執行時間 */
  create_time?: Int64;
  /** 處罰到期時間 */
  expire_time?: Int64;
}

export interface PunishScanRequest {
  Base?: base.Base;
}

export interface PunishScanResponse {
  BaseResp: base.BaseResp;
}

export interface PunishStatusInfo {
  ObjectID: string;
  Status: PunishStatus;
  /** 處罰開始時間，秒級時間戳 */
  BanStartTime?: Int64;
  /** 處罰到期時間，秒級時間戳 */
  BanExpireTime?: Int64;
}

export interface PunishTask {
  /** 任務id */
  task_id?: string;
  /** 處罰措施id */
  punish_measure_id?: string;
  /** 處罰主體 */
  punish_entity?: string;
  /** 創建人郵箱 */
  operator?: string;
  /** 處罰持續時間 */
  punish_duration?: Int64;
  /** 任務類別 */
  type?: PunishTaskType;
  /** 處罰任務執行狀態 */
  status?: PunishTaskStatus;
  /** 處罰對象個數 */
  object_num?: Int64;
  /** 處罰來源 */
  punish_source?: PunishSource;
  /** 處罰原因 */
  remark?: string;
  /** 創建時間 */
  create_time?: Int64;
  /** 更新時間 */
  update_time?: Int64;
}

/** 更新處罰措施 */
export interface UpdatePunishMeasureRequest {
  punish_measure_id: string;
  psm?: string;
  idl_branch?: string;
  /** 處罰措施狀態 */
  status?: PunishMeasureStatus;
  /** 處罰名稱 */
  punish_name?: string;
  /** 持續時間 */
  punish_duration?: Int64;
}

export interface UpdatePunishMeasureResponse {
  code: Int64;
  msg: string;
}
/* eslint-enable */
