/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface DuplicateTemplateData {
  /** 複製後的實體ID，如果複製的是智能體模板，對應複製後的智能體ID */
  entity_id?: string;
  /** 枚舉類型，目前只有 agent（智能體） */
  entity_type?: string;
}

export interface DuplicateTemplateRequest {
  /** 模板ID（目前僅支持複製智能體） */
  template_id?: string;
  /** 工作空間ID（預期將模板複製該空間） */
  workspace_id?: string;
  /** 複製後的實體名稱（對於複製智能體來說，未指定則默認用複製的智能體的名稱） */
  name?: string;
}

export interface DuplicateTemplateResponse {
  code?: number;
  msg?: string;
  data?: DuplicateTemplateData;
}
/* eslint-enable */
