/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** *************************** audit ********************************* */
export enum AuditStatus {
  /** 審覈中 */
  Auditing = 0,
  /** 審覈通過 */
  Success = 1,
  /** 審覈失敗 */
  Failed = 2,
}

/** *************************** publish ********************************* */
export enum ConnectorDynamicStatus {
  Normal = 0,
  Offline = 1,
  TokenDisconnect = 2,
}

export enum FolderType {
  /** 項目/智能體文件夾 */
  App = 1,
  /** 資源文件夾 */
  Resource = 2,
}

export enum OrderByType {
  Asc = 1,
  Desc = 2,
}

export enum PermissionType {
  /** 不能查看詳情 */
  NoDetail = 1,
  /** 可以查看詳情 */
  Detail = 2,
  /** 可以查看和操作 */
  Operate = 3,
}

export enum ResourceType {
  Plugin = 1,
  Workflow = 2,
  Imageflow = 3,
  Knowledge = 4,
  UI = 5,
  Prompt = 6,
  Database = 7,
  Variable = 8,
}

export enum SpaceStatus {
  Valid = 1,
  Invalid = 2,
}

/** 審覈結果 */
export interface AuditData {
  /** true：機審校驗不通過 */
  check_not_pass?: boolean;
  /** 機審校驗不通過文案 */
  check_not_pass_msg?: string;
}

export interface AuditInfo {
  audit_status?: AuditStatus;
  publish_id?: string;
  commit_version?: string;
}

export interface ConnectorInfo {
  id?: string;
  name?: string;
  icon?: string;
  connector_status?: ConnectorDynamicStatus;
  share_link?: string;
}

export interface FolderBasicInfo {
  id?: string;
  /** 父文件夾id */
  parent_id?: string;
  /** 文件夾類型 */
  folder_type?: FolderType;
  name?: string;
  description?: string;
  space_id?: string;
  creator_id?: string;
  /** 創建時間，秒級時間戳 */
  create_time?: string;
  /** 更新時間，秒級時間戳 */
  update_time?: string;
  /** 是否刪除 */
  is_deleted?: boolean;
}

export interface FolderInfo {
  folder_basic_info?: FolderBasicInfo;
  /** 子文件夾列表，只有tree接口才返回 */
  children_list?: Array<FolderInfo>;
  /** 父級文件夾路徑，不包含本文件夾 */
  parent_path?: Array<FolderBasicInfo>;
  /** 父級文件夾路徑，包含本文件夾 */
  full_path?: Array<FolderBasicInfo>;
  /** 文件夾創建者信息 */
  folder_creator_info?: User;
}

export interface Space {
  id?: Int64;
  owner_id?: Int64;
  status?: SpaceStatus;
  name?: string;
}

export interface User {
  user_id?: string;
  /** 用戶暱稱 */
  nickname?: string;
  /** 用戶頭像 */
  avatar_url?: string;
  /** 用戶名 */
  user_unique_name?: string;
  /** 用戶標籤 */
  user_label?: UserLabel;
}

/** *************************** user ********************************* */
export interface UserLabel {
  label_id?: string;
  label_name?: string;
  icon_uri?: string;
  icon_url?: string;
  jump_link?: string;
}

export interface Variable {
  /** 變量名 */
  keyword?: string;
  /** 默認值 */
  default_value?: string;
  /** 變量類型 */
  variable_type?: string;
  /** 變量來源 */
  channel?: string;
  /** 變量描述 */
  description?: string;
  /** 是否啓用 */
  enable?: boolean;
  /** 變量默認支持在Prompt中訪問，取消勾選後將不支持在Prompt中訪問（僅能在Workflow中訪問 */
  prompt_enable?: boolean;
}
/* eslint-enable */
