/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum TaskStatus {
  TaskStatusDoing = 1,
  TaskStatusSuccess = 2,
  TaskStatusFail = 3,
  TaskStatusCancel = 4,
}

/** 這是intelligence自己定義的任務類型，在intelligence中轉成task任務類型，最好廢棄，直接使用task任務類型 */
export enum TaskType {
  /** 草稿 --> 草稿 */
  TaskTypeProjectCopy = 1,
  /** TaskTypeBotCopy = 2
從模板來的  線上版本 --> 草稿 */
  TaskTypeCopyTemplateToProject = 3,
  /** 發佈成線上 */
  TaskTypePublishProject = 4,
  /** 發佈成模板 */
  TaskTypePublishTemplate = 5,
  /** 模板上架複製模板 */
  TaskTypeLaunchProjectTemplate = 6,
  /** 存檔 */
  TaskTypeArchiveProject = 7,
  /** 回滾 */
  TaskTypeRollbackProject = 8,
  /** Project跨空間複製 */
  TaskTypeCrossSpaceCopyProject = 9,
  /** Resource跨空間複製 */
  TaskTypeCrossSpaceCopyResource = 10,
}
/* eslint-enable */
