/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ConnectorAuditStatus {
  /** 未知、無審覈 */
  Unknown = 0,
  /** 審覈中 */
  Progress = 1,
  /** 審覈通過 */
  Audited = 2,
  /** 審覈拒絕 */
  Reject = 3,
}

export enum ConnectorBindStatus {
  Invalid = 0,
  Valid = 1,
  SaveNotPublish = 2,
  /** Token發生變化 */
  Disconnected = 3,
  /** 目前的配置不合法，需要重新配置。目前僅飛書多維表格使用 */
  NeedReconfigure = 4,
}

export enum ConnectorBindType {
  /** 無需綁定 */
  NoBindRequired = 1,
  /** Auth綁定 */
  AuthBind = 2,
  /** Kv綁定 */
  KvBind = 3,
  /** Kv並Auth授權 */
  KvAuthBind = 4,
  /** api渠道綁定 */
  ApiBind = 5,
  /** WebSDK綁定 */
  WebSDKBind = 6,
  /** 商店綁定 */
  StoreBind = 7,
  /** 授權和配置各一個按鈕 */
  AuthAndConfig = 8,
  /** 模板渠道綁定 */
  TemplateBind = 9,
}

export enum ConnectorClassification {
  /** api或sdk */
  APIOrSDK = 1,
  /** 社交平臺 */
  SocialPlatform = 2,
  /** Coze商店/模板 */
  Coze = 3,
  /** 小程序 */
  MiniProgram = 4,
  /** MCP擴展庫 */
  CozeSpaceExtensionLibrary = 5,
}

export enum ConnectorStatus {
  /** 正常 */
  Normal = 0,
  /** 審覈中 */
  InReview = 1,
  /** 已下線 */
  Offline = 2,
}
/* eslint-enable */
