/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum PublishResult {
  /** 未發佈 */
  Default = 0,
  /** 審覈中 */
  Auditing = 1,
  /** 發佈成功 */
  Successful = 2,
  /** 發佈失敗 */
  Failed = 3,
}

export enum PublishStatus {
  /** 打包中 */
  Packing = 0,
  /** 打包失敗 */
  PackFailed = 1,
  /** 審覈中 */
  Auditing = 2,
  /** 審覈未通過 */
  AuditNotPass = 3,
  /** 渠道發佈中 */
  ConnectorPublishing = 4,
  /** 發佈完成 */
  PublishDone = 5,
}
/* eslint-enable */
