/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_fornaxob_common from './flow_devops_fornaxob_common';
import * as annotation from './annotation';
import * as base from './base';
import * as eval_set from './eval_set';
import * as task from './task';
import * as datasetv2 from './datasetv2';
import * as flow_devops_fornaxob_fieldfilter from './flow_devops_fornaxob_fieldfilter';
import * as flow_devops_fornaxob_fieldfilterv2 from './flow_devops_fornaxob_fieldfilterv2';
import * as span from './span';

export type Int64 = string | number;

export enum ExportType {
  AppendData = 1,
  OverwriteData = 2,
}

export enum ItemStatus {
  Success = 0,
  Error = 1,
}

export enum SearchTraceType {
  LogID = 1,
  TraceID = 2,
  MessageID = 3,
  UID = 4,
}

export enum SearchTraceV3Type {
  LogID = 1,
  TraceID = 2,
}

export interface AnnotationEvaluator {
  evaluator_version_id: Int64;
  evaluator_name: string;
  evaluator_version: string;
}

export interface BatchGetTracesAdvanceInfoData {
  traces_advance_info: Array<TraceAdvanceInfo>;
}

export interface BatchGetTracesAdvanceInfoRequest {
  space_id: string;
  traces: Array<TraceQueryParams>;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
}

export interface BatchGetTracesAdvanceInfoResponse {
  data: BatchGetTracesAdvanceInfoData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface ChangeEvaluatorScoreRequest {
  workspace_id: Int64;
  evaluator_record_id: Int64;
  span_id: string;
  start_time: Int64;
  correction: annotation.Correction;
  Base?: base.Base;
}

export interface ChangeEvaluatorScoreResponse {
  annotation: annotation.Annotation;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface EvaluationSetConfig {
  /** 是否是新增評測集 */
  is_new_evaluation_set: boolean;
  /** 評測集id，新增評測集時可爲空 */
  evaluation_set_id?: Int64;
  /** 評測集名稱，選擇已有評測集時可爲空 */
  evaluation_set_name?: string;
  /** 評測集列數據schema */
  evaluation_set_schema?: eval_set.EvaluationSetSchema;
}

export interface ExportTracesToEvaluationRequest {
  space_id: string;
  spans: Array<string>;
  datasets: Array<string>;
  start_time?: string;
  end_time?: string;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** 平臺類型，不填默認是fornax */
  span_list_type?: flow_devops_fornaxob_common.SpanListType;
}

export interface ExportTracesToEvaluationResponse {
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface ExportTracesToEvaluationSetRequest {
  workspace_id: Int64;
  span_ids: Array<string>;
  evaluation_set: EvaluationSetConfig;
  start_time?: Int64;
  end_time?: Int64;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** 導入方式，不填默認爲追加 */
  export_type?: ExportType;
  field_mappings?: Array<task.FieldMapping>;
}

export interface ExportTracesToEvaluationSetResponse {
  /** 成功導入的數量 */
  success_count?: number;
  /** 錯誤信息 */
  errors?: Array<datasetv2.ItemErrorGroup>;
  /** 評測集id */
  evaluation_set_id?: Int64;
  /** 評測集名稱 */
  evaluation_set_name?: string;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

/** 後續需要遷移到 threadservice.FieldMeta */
export interface FieldMeta {
  /** 字段類型 */
  value_type: flow_devops_fornaxob_common.ValueType;
  /** 支持的操作類型 */
  filter_types: Array<flow_devops_fornaxob_fieldfilter.FieldFilterType>;
  /** 支持的可選項 */
  field_options?: flow_devops_fornaxob_fieldfilter.FieldOptions;
  /** 支持自定義填寫 */
  support_customizable_option?: boolean;
  /** 支持的操作類型 v2 */
  filter_types_v2?: Array<flow_devops_fornaxob_fieldfilterv2.FieldFilterType>;
}

export interface GetSpanInfoRequest {
  /** space id */
  space_id: string;
  trace_id: string;
  span_id: Array<string>;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
}

export interface GetSpanInfoResponse {
  data: GetTraceData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface GetTraceByLogIDRequest {
  /** space id */
  space_id: string;
  log_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
}

export interface GetTraceByLogIDResponse {
  data: GetTraceData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface GetTraceData {
  spans: Array<span.Span>;
  traces_advance_info?: TraceAdvanceInfo;
  /** 是否是完整的tree數據，false：僅包含tree結構信息, true：包含tree結構信息和span的詳細信息 */
  is_complete_trace?: boolean;
}

export interface GetTraceRequest {
  /** space id */
  space_id: string;
  trace_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  log_id?: string;
}

export interface GetTraceResponse {
  data: GetTraceData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface GetTracesMetaInfoData {
  /** 字段元信息 */
  field_metas: Record<string, FieldMeta>;
}

export interface GetTracesMetaInfoRequest {
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** 查詢的 span 標籤頁類型，不填默認是 root span */
  span_list_type?: flow_devops_fornaxob_common.SpanListType;
  space_id?: Int64;
}

export interface GetTracesMetaInfoResponse {
  data?: GetTracesMetaInfoData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface IngestTracesRequest {
  /** span列表 */
  spans?: Array<Span>;
  Base?: base.Base;
}

export interface IngestTracesResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface Item {
  status: ItemStatus;
  fields?: Record<string, string>;
  /** 錯誤信息 */
  errors?: Array<ItemError>;
}

export interface ItemError {
  type?: datasetv2.ItemErrorType;
  /** 有錯誤的字段名，非必填 */
  field_names?: Array<string>;
}

export interface ListAllSpansRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list<string> AppID (agw.js_conv="str" api.body = "app_id" go.tag="json:\"app_id\"")           // app id 字段作廢 */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search 全文本搜索，會搜input、output、bot_version, os_version這四個字段。可以傳入多個關鍵詞，每個關鍵詞之間是and關係 */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** 是否僅獲取 root span */
  is_root_span_only?: boolean;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListAllSpansResponse {
  data: ListTracesData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface ListAnnotationEvaluatorsRequest {
  workspace_id: Int64;
  name?: string;
}

export interface ListAnnotationEvaluatorsResponse {
  evaluators: Array<AnnotationEvaluator>;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface ListLLMSpansRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list<string> AppID (agw.js_conv="str" api.body = "app_id" go.tag="json:\"app_id\"")           // app id 字段作廢 */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search 全文本搜索，會搜input、output、bot_version, os_version這四個字段。可以傳入多個關鍵詞，每個關鍵詞之間是and關係 */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** 平臺類型，不填默認是fornax */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListLLMSpansResponse {
  data: ListTracesData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface ListTracesData {
  spans: Array<span.Span>;
  /** 下一頁的分頁token，前端拉取下一頁數據時回傳。 */
  next_page_token: string;
  /** 是否有更多數據 */
  has_more: boolean;
  /** Span的後處理信息 */
  spans_extra?: Record<string, SpanExtra>;
}

export interface ListTracesRequest {
  /** space id */
  space_id: string;
  /** ms */
  start_time: string;
  /** ms, end_at >= start_at */
  end_time: string;
  /** 4: optional list<string> AppID (agw.js_conv="str" api.body = "app_id" go.tag="json:\"app_id\"")           // app id 字段作廢 */
  filters?: Record<string, flow_devops_fornaxob_fieldfilter.FieldFilter>;
  /** Full-Text search 全文本搜索，會搜input、output、bot_version, os_version這四個字段。可以傳入多個關鍵詞，每個關鍵詞之間是and關係 */
  full_text_search?: Array<string>;
  /** default 1000 */
  limit?: number;
  /** The ORDER BY is used to sort the records, in ascending or descending order.

        ORDER BY with multiple field: The system will sort the results by field1(order_by[0]), then by field2(order_by[1])

        ⚠️  WARNING: only support start_time

         Example:
        [
            {
                "field_name": "start_time",
                "order_type": "desc"
            }
        ] */
  order_by?: Array<flow_devops_fornaxob_common.OrderBy>;
  /** The page token is generated after the first query and passed in the subsequent queries
     to determine the starting point for the next page of results. */
  page_token?: string;
  target_env?: flow_devops_fornaxob_common.EnvType;
  transferred?: boolean;
  'x-boe-env'?: string;
  /** 平臺類型，不填默認是psm */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  query_and_or?: flow_devops_fornaxob_fieldfilterv2.Relation;
}

export interface ListTracesResponse {
  data: ListTracesData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface OtelIngestTracesRequest {
  /** pb/json bytes數據 */
  body: Blob;
  /** 數據類型,可選application/x-protobuf或application/json */
  ContentType: string;
  /** 數據編碼類型,可選gzip */
  ContentEncoding: string;
  /** 空間ID */
  SpaceID: string;
  Base?: base.Base;
}

export interface OtelIngestTracesResponse {
  /** pb bytes數據 */
  body?: Blob;
  BaseResp?: base.BaseResp;
}

export interface PreviewExportTracesToEvaluationRequest {
  workspace_id: Int64;
  span_ids: Array<string>;
  evaluation_set: EvaluationSetConfig;
  start_time?: Int64;
  end_time?: Int64;
  /** 平臺類型 */
  platform_type?: flow_devops_fornaxob_common.PlatformType;
  /** 導入方式，不填默認爲追加 */
  export_type?: ExportType;
  field_mappings?: Array<task.FieldMapping>;
}

export interface PreviewExportTracesToEvaluationResponse {
  /** 預覽數據 */
  items?: Array<Item>;
  /** 概要錯誤信息 */
  errors?: Array<datasetv2.ItemErrorGroup>;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface SearchTraceV3Request {
  /** space id */
  space_id: string;
  /** 當前支持logid/traceid */
  id: string;
  search_type: SearchTraceV3Type;
  target_env?: flow_devops_fornaxob_common.EnvType;
  /** 訪問boe數據時指定泳道，非業務使用，其它接口的相同字段作用一樣 */
  'x-boe-env'?: string;
  transferred?: boolean;
  /** SearchTraceV3Type爲LogID時生效，可選往後查詢多久，不傳默認往後查一小時
hour */
  scan_span_in_hour?: string;
}

export interface SearchTraceV3Response {
  data: GetTraceData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code?: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg?: string;
}

export interface Span {
  /** Span 開始時間 */
  started_at_micros: string;
  /** LogID */
  logid?: string;
  /** SpanID */
  span_id: string;
  /** 父SpanID */
  parent_id: string;
  /** TraceID */
  trace_id: string;
  /** Span 耗時（已廢棄，使用DurationMicros） */
  duration: number;
  /** PSM */
  psm?: string;
  /** CallType */
  call_type?: string;
  /** SpaceID */
  workspace_id: string;
  /** Span名稱 */
  span_name: string;
  /** Span類型 */
  span_type: string;
  /** 方法名 */
  method: string;
  /** 狀態碼 */
  status_code: number;
  /** 輸入 */
  input: string;
  /** 輸出 */
  output: string;
  /** 對象存儲信息 */
  object_storage?: string;
  /** string類型系統tag */
  system_tags_string?: Record<string, string>;
  /** long類型系統tag */
  system_tags_long?: Record<string, Int64>;
  /** double類型系統tag */
  system_tags_double?: Record<string, number>;
  /** string類型自定義tag */
  tags_string?: Record<string, string>;
  /** long類型自定義tag */
  tags_long?: Record<string, Int64>;
  /** double類型自定義tag */
  tags_double?: Record<string, number>;
  /** bool類型自定義tag(兼容老結構用) */
  tags_bool?: Record<string, boolean>;
  /** byte類型自定義tag(兼容老結構用) */
  tags_bytes?: Record<string, string>;
  /** Span 耗時(微秒) */
  duration_micros?: string;
}

export interface SpanExtra {
  datasets?: Array<string>;
}

export interface TokenCost {
  /** 輸入消耗token數 */
  input: number;
  /** 輸出消耗token數 */
  output: number;
}

export interface TraceAdvanceInfo {
  trace_id: string;
  tokens: TokenCost;
}

/** Trace查詢參數 */
export interface TraceQueryParams {
  trace_id: string;
  start_time: string;
  end_time: string;
}
/* eslint-enable */
