/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface BaseInfo {
  created_by?: UserInfo;
  updated_by?: UserInfo;
  /** 創建時間,ms timestamp */
  created_at?: Int64;
  /** 更新時間,ms timestamp */
  updated_at?: Int64;
}

export interface UserInfo {
  /** 姓名 */
  name?: string;
  /** 英文名稱 */
  en_name?: string;
  /** 用戶頭像url */
  avatar_url?: string;
  /** 72 * 72 頭像 */
  avatar_thumb?: string;
  /** 用戶應用內唯一標識 */
  open_id?: string;
  /** 用戶應用開發商內唯一標識 */
  union_id?: string;
  /** 企業標識 */
  tenant_key?: string;
  /** 用戶在租戶內的唯一標識 */
  user_id?: string;
  /** 用戶郵箱 */
  email?: string;
}
/* eslint-enable */
