/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as agw_common from './agw_common';
import * as common from './common';
import * as queries from './queries';

export type Int64 = string | number;

export enum AuthStatus {
  AuthStatusNormal = 0,
  AuthStatusGeoLocationUnableParse = 1,
  AuthStatusGeoLocationIllegal = 2,
}

export enum BotAuthType {
  AuthTypeGeoLocation = 1,
}

export enum Operation {
  And = 0,
  Or = 1,
  Not = 2,
}

export interface AddBotAuthReq {
  /** Bot機器人ID */
  bot_id: string;
  /** 授權類型 */
  auth_type: BotAuthType;
  /** AGW loader通用參數( */
  agw_common_param?: agw_common.AgwCommonParam;
}

export interface AddBotAuthResp {
  code: number;
  msg: string;
}

export interface APIQueryRequest {
  /** 空間ID，用於權限校驗 */
  space_id: string;
  /** Bot機器人ID */
  bot_id: string;
  /** 指標名。枚舉值：dau/dnu/wau/wnu/message_count/retention_rate/token */
  metrics_type: string;
  /** 時間類型。枚舉值：hour/day/week/month/quarter/year */
  time_type: string;
  /** 時間範圍。 */
  time_range: TimeRange;
  /** 其他過濾維度 */
  filter?: Filter;
  /** 過濾器抽象 */
  criterias?: Array<Criteria>;
}

export interface APIQueryResponse {
  data: ObQueryData;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface BatchAPIQueryRequest {
  /** 空間ID，用於權限校驗 */
  space_id: string;
  /** Bot機器人ID */
  bot_id: string;
  /** 多指標名稱 */
  metrics_types: Array<string>;
  /** 時間範圍 */
  time_range: TimeRange;
  /** 需要返回的數據類型，枚舉value/group_list/point_list/ranking，因爲同一個指標可能需要不同的數據類型 */
  data_type: string;
  /** 全局過濾維度 */
  filter?: BatchFilter;
  /** 聚合維度，維度聚合指標需要，目前只有單維度 */
  group_type?: Array<string>;
  /** 時間聚合類型，多軸圖/排名需要，枚舉：hour/day/week/month/quarter/year */
  period_type?: string;
  /** 固定時間範圍類型，不可累加指標需要 */
  time_range_type?: string;
  /** 是不是請求實時數據，實時數據用於展示實時圖標 */
  is_realtime?: boolean;
}

export interface BatchAPIQueryResponse {
  data: Array<BatchObData>;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface BatchAPIQueryV2Request {
  /** 場景參數  不同場景使用的通用參數 */
  scene_param: common.SceneCommonParam;
  /** 多指標名稱 */
  metrics_types: Array<string>;
  /** 需要返回的數據類型，枚舉value/group_list/point_list/ranking，因爲同一個指標可能需要不同的數據類型 */
  data_type: string;
  /** 數據源。枚舉：user_overview，connector_group，user_engagement，error_code_group_value。一個數據源可能可以按不同的 data_type 進行解析 */
  data_source_type: string;
  /** 全局過濾維度 */
  filter?: BatchFilter;
  /** 聚合維度，維度聚合指標需要，目前只有單維度 */
  group_type?: Array<string>;
  /** 時間聚合類型，多軸圖/排名需要，枚舉：day、week、month、quarter */
  period_type?: string;
  /** 固定時間範圍類型。枚舉：last_7_days、last_30_days、last_90_days、last_180_days、acc */
  time_range_type?: string;
}

export interface BatchAPIQueryV2Response {
  data: Array<BatchObData>;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface BatchFilter {
  /** 渠道名 */
  connector_id?: Array<string>;
}

export interface BatchObData {
  /** 指標類型 */
  metrics_type: string;
  /** 返回的數據類型 */
  data_type: string;
  /** 指標總值 */
  value?: Value;
  /** 聚合結果列表，按照維度拆分 */
  group_list?: Array<Record<string, string>>;
  /** 折線圖point列表 */
  point_list?: Array<Point>;
  /** 排名 */
  ranking?: RankValue;
}

export interface BotAuthData {
  /** 權限類型 */
  auth_type: BotAuthType;
  /** 授權是否有異常情況，比如地理位置授權時強制改寫了location（因爲無法解析/位置不合規） */
  auth_status?: AuthStatus;
  /** 地理位置授權信息，內含location */
  geo_location?: GeoLocation;
}

export interface BotSatisfaction {
  score: number;
  increment: number;
  hasScore: boolean;
}

export interface BotSatisfactionRequest {
  space_id: string;
  bot_id: string;
  /** 時間範圍。 */
  time_range: TimeRange;
  /** 指定的渠道列表 */
  connector_ids?: Array<string>;
}

export interface BotSatisfactionResponse {
  data: BotSatisfaction;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface Criteria {
  criteria?: Criteria;
  op?: Operation;
  key: string;
  value: string;
}

export interface DeleteBotAuthReq {
  /** Bot機器人ID */
  bot_id: string;
  /** 權限類型 */
  auth_type: BotAuthType;
}

export interface DeleteBotAuthResp {
  code: number;
  msg: string;
}

export interface Dim {
  user_type: string;
  connector_name: string;
  retention_period: string;
  model_name: string;
  message_type: string;
}

export interface EvalSupportChannel {
  status: string;
  channels: Array<string>;
}

export interface EvalSupportChannelRequest {
  bot_id: string;
  space_id: string;
}

export interface EvalSupportChannelResponse {
  data: EvalSupportChannel;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface Filter {
  /** 用戶類型。枚舉值：new_user/old_user。每個字段不傳的話，代表不進行過濾。 */
  user_type?: Array<string>;
  /** 渠道名 */
  connector_name?: Array<string>;
  /** 留存週期。枚舉值：1d/7d/30d */
  retention_period?: Array<string>;
  /** 大模型名稱，如GPT-3.5 */
  model_name?: Array<string>;
}

export interface GeoLocation {
  /** 大地區，注意: 中國大陸、香港、澳門、臺灣都有自己的code */
  country_identifier?: string;
  country_name?: string;
  /** 局地，國內是省份 */
  subdivision_identifier?: string;
  subdivision_name?: string;
  /** 城市 */
  city_identifier?: string;
  city_name?: string;
  /** 大地區，注意: 中國大陸、香港、澳門、臺灣都有自己的code */
  origin_country_identifier?: string;
  origin_country_name?: string;
  /** 局地，國內是省份 */
  origin_subdivision_identifier?: string;
  origin_subdivision_name?: string;
  /** 城市 */
  origin_city_identifier?: string;
  origin_city_name?: string;
  /** 原客戶端ip */
  client_ip?: string;
  /** 授權時間戳 */
  auth_timestamp?: string;
}

export interface GetBotFgRequest {
  space_id: string;
  bot_id: string;
}

export interface GetBotFgResponse {
  /** queries頁面的fg開關 */
  enable_queries?: boolean;
  code: Int64;
  msg: string;
}

export interface GetQueriesDataRequest {
  space_id: string;
  bot_id: string;
  /** 時間範圍 */
  time_range: TimeRange;
  /** key: field名稱，對應 GetQueriesFieldMetasResponse.field_metas 的key */
  filters?: Record<string, queries.QueriesFilter>;
  /** 排序字段，填入filters的key */
  order_by?: string;
  /** asc/desc */
  sort_order?: string;
  /** offset */
  page_token?: Int64;
  /** 默認和最多都是20個 */
  size?: Int64;
}

export interface GetQueriesDataResponse {
  data?: Array<queries.QueriesData>;
  page_token?: Int64;
  has_more?: boolean;
  code: Int64;
  msg: string;
}

export interface GetQueriesFieldMetasRequest {
  space_id: string;
  bot_id: string;
}

export interface GetQueriesFieldMetasResponse {
  /** key: field名稱，如"channel"，"intention"等，對應 GetQueriesDataRequest.filters 的key */
  field_metas?: Record<string, queries.FieldMeta>;
  code: Int64;
  msg: string;
}

export interface ObData {
  /** 指標的時間點。時間戳格式，精確到毫秒 */
  metrics_time: Int64;
  /** 指標的值 */
  value: string;
  /** 指標的維度 */
  dim: Dim;
  /** 數據標籤名稱 */
  name?: Array<string>;
  /** 數據標籤名稱附加信息 */
  tag?: string;
  /** 數據標籤展示名稱（可被前端直接展示） */
  label_name?: string;
  /** 數據標籤的id，唯一標識標籤，用於作爲跳轉頁面時的篩選條件 */
  label_id?: string;
}

export interface ObQueryData {
  list: Array<ObData>;
}

export interface Point {
  /** 指標的時間點。時間戳格式，精確到毫秒 */
  metrics_time: Int64;
  /** 指標的值 */
  value: string;
}

export interface PreCheckAddBotAuthReq {
  /** Bot機器人ID */
  bot_id: string;
  /** 授權類型 */
  auth_type: BotAuthType;
  /** AGW loader通用參數( */
  agw_common_param?: agw_common.AgwCommonParam;
}

export interface PreCheckAddBotAuthResp {
  data?: BotAuthData;
  code: number;
  msg: string;
}

export interface RankValue {
  /** 本週期排名 */
  value?: string;
  /** 上週期排名 */
  last_period_value?: string;
  /** 類目名稱 */
  category_name?: string;
}

export interface TimeRange {
  /** 開始時間。時間戳，精確到毫秒 */
  start: Int64;
  /** 結束時間。時間戳，精確到毫秒 */
  end: Int64;
}

export interface UserIntentSatisfactionRanking {
  starling_key: string;
  frequency: Int64;
  score: number;
  contribution: number;
  label_id: string;
  parent_starling_key: string;
}

export interface UserIntentSatisfactionRankingRequest {
  space_id: string;
  bot_id: string;
  /** 時間範圍。 */
  time_range: TimeRange;
  label_depth: string;
  /** 指定的渠道列表 */
  connector_ids?: Array<string>;
}

export interface UserIntentSatisfactionRankingResponse {
  data: UserIntentSatisfactionRankings;
  /** 給API接口使用。RPC接口不要使用該字段 */
  code: Int64;
  /** 給API接口使用。RPC接口不要使用該字段 */
  msg: string;
}

export interface UserIntentSatisfactionRankings {
  data: Array<UserIntentSatisfactionRanking>;
}

export interface Value {
  /** 本週期值 */
  value?: string;
  /** 上週期值 */
  last_period_value?: string;
}

export interface ViewBotAuthReq {
  /** Bot機器人ID */
  bot_id: string;
}

export interface ViewBotAuthResp {
  data_list?: Array<BotAuthData>;
  code: number;
  msg: string;
}
/* eslint-enable */
