/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';
import * as ob_query from './ob_query';

export type Int64 = string | number;

export interface ExportQueryToCsvV2Request {
  /** space id */
  space_id: string;
  /** 場景參數  不同場景使用的通用參數 */
  scene_param: common.SceneCommonParam;
  /** 篩選參數 */
  query_filter?: QueryFilterV2;
}

export interface ExportQueryToCsvV2Response {
  body?: Blob;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface GetQueryEnumsV2Request {
  /** space id */
  space_id: string;
  /** 場景參數  不同場景使用的通用參數參數 */
  scene_param: common.SceneCommonParam;
}

export interface GetQueryEnumsV2Response {
  intent?: Array<ob_query.Intent>;
  /** key: connector_id, value: connector_name */
  connectors?: Array<ob_query.KV>;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface GetQueryStatV2Request {
  /** space id */
  space_id: string;
  /** 場景參數  不同場景使用的通用參數 */
  scene_param: common.SceneCommonParam;
  query_filter?: QueryFilterV2;
}

export interface GetQueryStatV2Response {
  data: ob_query.GetQueryStatData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface ListQueryV2Request {
  /** space id */
  space_id: string;
  /** 場景參數  不同場景使用的通用參數 */
  scene_param: common.SceneCommonParam;
  /** 篩選參數 */
  query_filter?: QueryFilterV2;
  /** default 20 max 200 */
  limit?: number;
  /** 上次請求帶過來的分頁參數 */
  page_token?: string;
}

export interface ListQueryV2Response {
  data: Array<QueryDataV2>;
  /** 下一頁的分頁token，前端拉取下一頁數據時回傳 */
  next_page_token: string;
  /** 是否有更多數據 */
  has_more: boolean;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface QueryDataV2 {
  query_id?: string;
  /** trace_id，用於查詢trace細節 */
  trace_id?: string;
  /** 狀態 */
  status?: ob_query.Status;
  /** 用戶ID */
  user_id?: string;
  /** 對話ID */
  message_id?: string;
  /** 會話ID */
  session_id?: string;
  /** 用戶輸入 */
  input?: string;
  /** bot輸出 */
  output?: string;
  /** 模型輸入長度 */
  input_tokens?: number;
  /** 模型輸出長度 */
  output_tokens?: number;
  /** 發起請求時間 */
  start_time?: string;
  /** 整體耗時 */
  latency?: Int64;
  /** 首token時延 */
  latency_first_resp?: Int64;
  /** 渠道名稱 */
  connector?: string;
  /** 意圖標籤 */
  intent?: string;
  /** 意圖字段生產狀態 */
  intent_status?: ob_query.CalFieldStatus;
  /** session字段生產狀態 */
  session_id_status?: ob_query.CalFieldStatus;
  /** 會話ID（connector platform上報原始值） */
  conversation_id?: string;
  /** 發佈管理新增
運行id */
  workflow_execute_id?: string;
  trigger_id?: string;
  /** 觸發器name--來源name, */
  trigger_name?: string;
  /** Project版本 對外用戶填寫的 */
  version?: string;
  /** Project版本 時間戳 */
  version_code?: string;
  /** 運行token */
  total_tokens?: number;
}

export interface QueryFilterV2 {
  start_time?: ob_query.TimeRange;
  status?: Array<ob_query.Status>;
  user_ids?: Array<string>;
  message_ids?: Array<string>;
  session_ids?: Array<string>;
  input?: string;
  output?: string;
  input_tokens?: ob_query.I64Range;
  output_tokens?: ob_query.I64Range;
  latency?: ob_query.I64Range;
  latency_first_resp?: ob_query.I64Range;
  connector_ids?: Array<string>;
  second_class_intents?: Array<string>;
  /** 發佈管理新增 */
  workflow_execute_ids?: Array<string>;
  trigger_ids?: Array<string>;
  trigger_name?: string;
  version_codes?: Array<string>;
  total_tokens?: ob_query.I64Range;
}
/* eslint-enable */
