/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

/** 聚合方式 */
export enum AggregateType {
  Unknown = 1,
  Avg = 2,
  P50 = 3,
  P99 = 4,
  P999 = 5,
  P90 = 6,
  Sum = 7,
}

/** 降採樣間隔 */
export enum DownsampleInterval {
  Unknown = 1,
  /** 30 second */
  DI30S = 2,
  /** 1 minute */
  DI1M = 3,
  /** 2 minute */
  DI2M = 4,
  /** 5 minute */
  DI5M = 5,
  /** 10 minute */
  DI10M = 6,
  /** 20 minute */
  DI20M = 7,
  /** 30 minute */
  DI30M = 8,
}

/** 運維視圖的類型 */
export enum MetricsType {
  Unknown = 1,
  /** 每秒收到的查詢次數，反映了該Bot的查詢負載情況 */
  BotQueryQPS = 2,
  /** 查詢成功率，反映了Bot在當前負載下的穩定性 */
  BotQuerySuccessRate = 3,
  /** 從被Bot收到查詢到返回第一條Tokens的時延，反映了查詢方可感知到的Bot響應速度 */
  BotQueryLatencyFirstResp = 4,
  /** 從Bot收到查詢到返回全部Tokens的時延，反映了Bot的整體性能 */
  BotQueryLatency = 5,
  /** 每秒的工作流調用次數，反映了工作流的負載情況 */
  WorkflowRunQPS = 6,
  /** 工作流的調用成功率，反映了該工作流在當前負載下穩定性 */
  WorkflowRunSuccessRate = 7,
  /** 反映了工作流的執行耗時 */
  WorkflowRunLatency = 8,
  /** 每秒的插件調用次數。反映了插件負載情況 */
  PluginRunQPS = 9,
  /** 插件的調用成功率，反映了插件在當前負載下的穩定性 */
  PluginRunSuccessRate = 10,
  /** 插件的響應時長，反映了插件的整體性能 */
  PluginRunLatency = 11,
  /** 每秒的代碼對應函數片段的被調用次數。反映了執行負載 */
  CodeRunQPS = 12,
  /** 代碼對應函數的調用成功率，反映了對應負載下的穩定性 */
  CodeRunSuccessRate = 13,
  /** 代碼對應函數的執行耗時，反映了整體性能 */
  CodeRunLatency = 14,
  /** 每秒知識庫的召回次數，反映了知識庫的召回負載 */
  KnowledgeRecallQPS = 15,
  /** 知識庫的每次召回的片段數量 */
  KnowledgeRecallSegments = 16,
  /** 知識庫的召回成功率，反映了知識庫在當前負載下的穩定性情況 */
  KnowledgeRecallSuccessRate = 17,
  /** 知識庫的召回耗時，反映了知識庫的召回性能 */
  KnowledgeRecallLatency = 18,
  /** 每秒大模型的調用次數，反映了大模型的調用負載 */
  LLMQueryQPS = 19,
  /** 大模型的調用成功率，反映了大模型在當前負載下的穩定性 */
  LLMQuerySuccessRate = 20,
  /** 大模型的響應時長，反映了大模型的整體性能 */
  LLMQueryLatency = 21,
  /** 大模型每秒返回的Token數量 */
  LLMOutputTokensQPS = 22,
  /** 每秒的hook調用次數。反映了hook負載情況 */
  HookRunQPS = 23,
  /** hook的調用成功率，反映了hook在當前負載下的穩定性 */
  HookRunSuccessRate = 24,
  /** hook的平均耗時，反映了hook的整體性能 */
  HookRunLatency = 25,
}

export interface Curve {
  tag_kvs: Record<string, string>;
  points: Array<Point>;
}

export interface GetMetricsData {
  curves: Array<Curve>;
  /** 降採樣間隔 */
  interval: DownsampleInterval;
}

export interface GetMetricsRequest {
  /** space id */
  space_id: string;
  /** bot id */
  bot_id: string;
  /** s */
  start_time: string;
  /** s, end_at >= start_at */
  end_time: string;
  metrics_type: MetricsType;
  aggregate_type?: AggregateType;
  tag_kvs?: Record<string, Array<string>>;
  top_k?: number;
}

export interface GetMetricsResponse {
  data: GetMetricsData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface GetTagVHistoricalOptionsData {
  options: Array<TagVOption>;
}

export interface GetTagVHistoricalOptionsRequest {
  /** space id */
  space_id: string;
  /** bot id */
  bot_id: string;
  tag_k: string;
  choices?: Record<string, Array<string>>;
  /** s */
  start_time: string;
  /** s, end_at >= start_at */
  end_time: string;
  metrics_type: MetricsType;
  top_k?: number;
}

export interface GetTagVHistoricalOptionsResponse {
  data: GetTagVHistoricalOptionsData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface GetTagVLatestOptionsData {
  options: Array<TagVOption>;
}

export interface GetTagVLatestOptionsRequest {
  /** space id */
  space_id: string;
  /** bot id */
  bot_id: string;
  tag_k: string;
  choices?: Record<string, Array<string>>;
}

export interface GetTagVLatestOptionsResponse {
  data: GetTagVLatestOptionsData;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  code: number;
  /** 僅供http請求使用; 內部RPC不予使用，統一通過BaseResp獲取Code和Msg */
  msg: string;
}

export interface Point {
  x: Int64;
  x_alias: string;
  y: number;
}

export interface TagVOption {
  key: string;
  label: string;
}
/* eslint-enable */
