/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum InputComponentType {
  /** 文本輸入框，圖 4 控件 */
  Text = 1,
  /** 單選，圖 4 控件 */
  SingleSelect = 2,
  /** 多選，圖 4 控件 */
  MultiSelect = 3,
  /** 字段選擇器，圖 4 控件 */
  FieldSelector = 4,
}

export enum OutputSubComponentType {
  /** 沒有子 component */
  None = 0,
  /** 輸出類型爲 object */
  Object = 1,
}

/** base 就是多維表格的英文名。所以飛書多維表格是 FeishuBase */
export interface FeishuBaseConfig {
  /** markdown，對應“#配置多維飛書表格\n將你的...“ */
  description: string;
  /** 所有類型 id 到 info 的映射 */
  output_type_list: Array<OutputTypeInfo>;
  output_type: number;
  /** markdown, 對應“捷徑輸出類型”旁邊的 i */
  output_desc?: string;
  output_sub_component: OutputSubComponent;
  input_config: Array<InputConfig>;
  /** markdown, 對應“配置多維表格字段”旁邊的 i */
  input_desc?: string;
  input_type_list: Array<InputTypeInfo>;
  /** 輸出類型選中 object 後，object value 可選的類型列表 */
  object_value_type_list: Array<OutputTypeInfo>;
  /** 完善上架信息,  */
  to_complete_info?: ToCompleteInfo;
}

export interface GetFeishuBaseConfigRequest {
  bot_id: string;
}

export interface GetFeishuBaseConfigResponse {
  config?: FeishuBaseConfig;
  code: number;
  msg?: string;
}

export interface InputComponent {
  type: InputComponentType;
  /** 僅 Type == Text 有用 */
  max_char?: number;
  /** Type in [SingleSelect, MultiSelect] */
  choice?: Array<string>;
  /** Type == FieldSelector */
  supported_type?: Array<number>;
}

export interface InputConfig {
  field: string;
  title: string;
  placeholder?: string;
  input_component: InputComponent;
  required?: boolean;
  /** markdown, 對應 user_query 旁邊的 i */
  desc?: string;
  /** 失效了。需要重新配置的時候纔會出現 */
  invalid?: boolean;
}

export interface InputTypeInfo {
  id: number;
  name: string;
}

export interface OutputSubComponent {
  type: OutputSubComponentType;
  /** 僅 Type == object 會有 */
  item_list?: Array<OutputSubComponentItem>;
  /** eg: 結構化輸出配置右邊的 i */
  struct_output_desc?: string;
  /** 結構化輸出，id 列的說明 */
  struct_id_desc?: string;
  /** 結構化輸出，主屬性說明 */
  struct_primary_desc?: string;
}

export interface OutputSubComponentItem {
  key: string;
  /** 同 FeishuBaseConfig.OutputType */
  output_type: number;
  /** 主屬性, 標記該屬性爲用於排序的主屬性。 */
  is_primary?: boolean;
  /** 標記該屬性會作爲Object字段的篩選、分組依據。 */
  is_group_by_key?: boolean;
}

export interface OutputTypeInfo {
  /** 會增加，就不整成 enum 了。 */
  id: number;
  /** 名稱，例如“文本”，“對象”等 */
  name: string;
  /** markdown, 對應圖 3 中 “需要在 Persona ...“ */
  tips?: string;
}

export interface ToCompleteInfo {
  /** 完善信息的填寫地址 */
  url: string;
  /** 是否填好 */
  completed: boolean;
}

export interface UpdateFeishuBaseCompleteStatusRequest {
  bot_id: string;
}

export interface UpdateFeishuBaseCompleteStatusResponse {
  code: number;
  msg?: string;
}
/* eslint-enable */
