/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as copilot_common from './copilot_common';

export type Int64 = string | number;

export enum BotExeType {
  Create = 1,
  Update = 2,
  Delete = 3,
}

export enum BotSpecies {
  /** bot種類 */
  Default = 0,
  Function = 1,
}

export enum BotStatus {
  Using = 0,
  Deleted = 1,
}

export enum BotType {
  /** bot類型 */
  User = 0,
  Coco = 1,
  GuanFang = 2,
}

export enum ModelCacheType {
  PrefixCache = 1,
}

export enum ModelParamType {
  Float = 1,
  Int = 2,
  Boolean = 3,
  String = 4,
}

export enum ModelProvider {
  GptOpenApi = 1,
  GptEngine = 2,
  MaaS = 3,
  QianFan = 4,
  BytedLLMServer = 5,
}

export enum PromptTemplateType {
  GPT_TOOLS = 0,
  GPT_TOOLS_DATASET = 1,
  GPT_DATASET = 2,
  GPT_NOTHING = 3,
  SEED_MUSIC = 4,
}

export enum RecommendStatus {
  /** 個性化推薦狀態 */
  Enable = 0,
  Disable = 1,
}

export interface BytedLLMServerConf {
  psm?: string;
  idc?: Array<string>;
  cluster?: string;
  /** 配置值爲orca或者ultraman或者genai */
  request_type?: string;
  /** 使用genai時必填 */
  chat_template?: string;
  /** 自定義orca框架的模型出入參 */
  orca_model_param?: OrcaModelParamConf;
}

export interface Capability {
  /** 是否支持 function 調用 */
  function_call?: boolean;
  /** 是否支持頭條卡片類型 */
  card?: boolean;
  /** 是否支持視頻搜索 */
  media?: boolean;
  /** 執行策略 */
  proxy?: copilot_common.ModelProxy;
  /** 支持工具 */
  tool?: boolean;
  /** seed模型輸出爲api_name，而非plugin + api_name，若拼接會導致調插件失敗。此標識可阻止拼接 */
  fixed_function?: boolean;
  /** for seed_strong_character_with_mem，在 bot_prompt_template_jinja 中引用 */
  profile_memory?: boolean;
  /** 從歷史消息中恢復，用於豆包語音鏈路，作用在 Seed SC 模型上  */
  resume_segment?: boolean;
  /** 是否支持複雜參數調用，例如 */
  complex_function_call?: boolean;
  /** Deprecated: 使用 multimodal_types 取代。是否支持多模態協議，如圖片識別 */
  multi_modal?: boolean;
  /** 是否支持 json_mode */
  json_mode?: boolean;
  /** 是否支持消息命名 */
  nameable?: boolean;
  /** 多模態支持的文件類型，遵循 MIME 標準 */
  multimodal_types?: Array<string>;
  /** 是否支持預搜索，aka 續寫  */
  pre_query?: boolean;
  /** 是否支持搜索增強，會插入 type=search_enhance 的 tool */
  search_enhance?: boolean;
  /** 是否展示thinking */
  cot_display?: boolean;
  /** 支持的緩存類型 */
  cache?: Array<ModelCacheType>;
  /** 是否支持續寫 */
  prefill_resp?: boolean;
  /** 允許展示的如意卡片列表 */
  ala_src_allow_list?: Array<string>;
  /** 是否支持批量調用 */
  batch?: boolean;
}

export interface GptEngineConf {
  /** seed 運行時 */
  runtime?: string;
  /** ab 參數，通過 json 序列化 */
  ab_param?: string;
  /** seed app_id */
  app_id?: string;
  /** cluster */
  cluster?: string;
}

export interface GptOpenApiConf {
  /** 基礎請求地址 */
  openai_api_base?: string;
  /** API 協議版本 */
  openai_api_version?: string;
  /** AZURE / OPEN_AI / AZURE_AD */
  openai_api_type?: string;
}

export interface LegacyFields {
  /** 原 model_name 取值 */
  model_name?: Int64;
}

export interface MaasAuthConf {
  ak?: string;
  sk?: string;
  /** 調用方舟的時候不指定大模型名稱 而是指定 endpoint */
  endpoint?: string;
  host?: string;
  region?: string;
}

export interface MaasConf {
  auth?: MaasAuthConf;
  /**  */
  plugins?: Array<string>;
  extra?: Record<string, string>;
  using_stream?: boolean;
  api_version?: string;
  /** 火山方舟節點的暱稱 */
  endpoint_name?: string;
  /** 火山方舟節點創建時間 */
  endpoint_create_time?: Int64;
}

export interface ModelConf {
  /** 超時時間[ms] */
  timeout?: number;
  /** 重試次數 */
  retry_times?: number;
  /** deprecated 回覆輸出方式 */
  print_behavior?: copilot_common.PrintBehavior;
  /** Maas 特有的配置 */
  maas?: MaasConf;
  /** 千帆特有的配置 */
  qianfan?: QianFanConf;
  /** gpt openapi 配置 */
  gpt_openapi?: GptOpenApiConf;
  /** gpt engine 配置 */
  gpt_engine?: GptEngineConf;
  /** byted llm server 配置 */
  byted_llm_server?: BytedLLMServerConf;
  /** 提供模型的平臺，openai maas 等 */
  provider?: ModelProvider;
}

export interface ModelParameter {
  /** 配置字段，如max_tokens */
  name?: string;
  /** 類型 */
  type?: ModelParamType;
  /** 是否必填 */
  is_required?: boolean;
  /** 數值類型參數，允許設置的最小值 */
  min?: string;
  /** 數值類型參數，允許設置的最大值 */
  max?: string;
  /** float類型參數的精度 */
  precision?: number;
  /** 不同風格的參數默認值 */
  default_value?: Record<string, string>;
  /** 枚舉值，如response_format支持text,markdown,json */
  options?: Array<string>;
  /** 是否自動修正該參數到[min, max]範圍內， 默認爲false */
  auto_fix?: boolean;
}

export interface ModelQuota {
  /** 最大總 token 數量 */
  token_limit?: Int64;
  /** 最終回覆最大 token 數量 */
  token_resp?: Int64;
  /** Prompt 系統最大 token 數量 */
  token_system?: Int64;
  /** Prompt 用戶輸入最大 token 數量 */
  token_user_in?: Int64;
  /** Prompt 工具輸入最大 token 數量 */
  token_tools_in?: Int64;
  /** Prompt 工具輸出最大 token 數量 */
  token_tools_out?: Int64;
  /** Prompt 數據最大 token 數量 */
  token_data?: Int64;
  /** Prompt 歷史最大 token 數量 */
  token_history?: Int64;
  /** Prompt 歷史最大 token 數量 */
  token_cut_switch?: boolean;
  /** 輸入成本 */
  price_in?: number;
  /** 輸出成本 */
  price_out?: number;
  /** Bot 提示詞配置 token 數量 */
  token_persona?: number;
  /** 容量，用於監控 */
  request_per_minute?: Int64;
  /** 容量，用於監控 */
  token_per_minute?: Int64;
}

export interface OrcaCustomerParam {
  string_lists?: Record<string, Array<string>>;
  int_lists?: Record<string, Array<Int64>>;
  float_lists?: Record<string, Array<number>>;
  string_arrays?: Record<string, Array<Array<string>>>;
}

export interface OrcaModelParamConf {
  /** openai */
  openai_req_key?: string;
  openai_resp_key?: string;
  /** customer */
  in_customer_param?: OrcaCustomerParam;
}

export interface PromptConf {
  /** 模版配置 tcc: bot_prompt_sequence */
  sequence?: string;
  /** 模版前綴 tcc: bot_prompt_template */
  prefix?: string;
  /** 模版後綴 tcc: bot_prompt_template */
  suffix?: string;
  /** 是否人格化 */
  is_sc?: boolean;
  /** 不開啓ReACT(response_format) */
  close_react?: boolean;
  /** user prompt是否必須 */
  is_up_required?: boolean;
}

export interface QianFanAuthConf {
  client_id?: string;
  client_secret?: string;
}

export interface QianFanConf {
  auth?: QianFanAuthConf;
}
/* eslint-enable */
