/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export enum ChargeItemType {
  ChargeItemTypeNew = 1,
  ChargeItemTypeExpand = 2,
  ChargeItemTypeShrink = 3,
  ChargeItemTypeUpgrade = 4,
  ChargeItemTypeDowngrade = 5,
  ChargeItemTypeRemove = 6,
}

export interface ByteTree {
  /** 必填
rds傳_read/_write兩個psm，其他產品傳一個 */
  PSMs?: Array<string>;
  /** TreeOperationCreate/TreeOperationDelete 時必填
服務樹provider */
  Provider?: string;
  /** 需要掛載的服務樹的位置 */
  ParentNodeID?: Int64;
  /** 租戶ID，用於選賬號邏輯 */
  TenantID?: string;
  /** 環境：boe/prod/ppe */
  Env?: string;
  /** 對應的region，比如cn */
  Region?: string;
  /** 對應的partition，比如cn */
  Partition?: string;
  /** TreeOperationCreate 時必填
控制面對應資源的鏈接 */
  ResourceLink?: ResourceLink;
  /** 掛樹操作人 */
  OpUser?: string;
  /** TreeOperationCreate 時選填
服務樹描述 */
  Description?: string;
  /** 該資源初始化時候IAM的owner的個人賬號 */
  OwnerList?: Array<string>;
  /** 該資源初始化時候IAM的owner的服務賬號 */
  ServiceAccountList?: Array<string>;
  /** 服務樹標籤 */
  Tags?: Record<string, string>;
  /** 僅MQ掛載group的時候需要 */
  GroupName?: string;
  /** 僅MQ掛載topic的時候需要 */
  TopicName?: string;
}

/** 配置單 */
export interface ChargeItem {
  Flavor: string;
  BeforeValue: number;
  AfterValue: number;
  ChargeItemType: ChargeItemType;
  /** 根據業務是否按VDC分配quota而定 */
  VDC?: string;
  /** babi售賣區，有的計費項比較奇怪，這裏支持直接傳值 */
  SalesArea?: string;
  IsForPrice?: boolean;
}

export interface DataMessage18 {}

export interface DataMessage20 {
  format_regions_backend?: Array<DataMessage20FormatRegionsBackendMessage>;
}

export interface DataMessage20FormatRegionsBackendMessage {
  backend?: boolean;
  frontend?: boolean;
  region?: string;
}

export interface Error {
  CodeN: Int64;
  Code: string;
  Message: string;
}

export interface GetOrderConfigRequest {
  env: string;
  function_id: string;
  parent_node_id: Int64;
  psm: string;
  service_id: string;
  region: string;
  cluster?: OrderConfigCluster;
  mq_event?: OrderConfigMqEvent;
}

export interface GetOrderConfigResp {
  ResponseMetaData: ResponseMetaData;
  /** 用於掛樹預檢查和選火山賬號使用 */
  ByteTree: ByteTree;
  /** 10: optional ark.ArkData ArkData
99: optional list<OrderConfig> OrderConfigs // 兼容tce等組件可以跨region下單 */
  OrderConfig?: OrderConfig;
}

export interface getRegionsEnabledRequest {}

export interface GetRegionsEnabledResponse {
  code?: number;
  data?: DataMessage20;
  error?: string;
}

export interface getRegionZonesRequest {}

export interface GetRegionZonesResponse {
  code?: number;
  data?: Record<string, Array<string>>;
  error?: string;
}

export interface getRuntimeRequest {}

export interface GetRuntimeResponse {
  code?: number;
  /** region will be key name */
  data?: Record<string, Array<Runtime>>;
  error?: string;
}

export interface OrderConfig {
  PID: string;
  ProductID: string;
  Region: string;
  NeedConvertToInnerChargeItem?: boolean;
  ChargeItems: Array<ChargeItem>;
}

export interface OrderConfigCluster {
  http_trigger_disable?: boolean;
  pod_type: string;
  replica_limit: Record<string, common.PodReplicaLimit>;
  resource_limit: common.Resource;
}

export interface OrderConfigMqEvent {
  resource: common.Resource;
  type: string;
}

export interface PrescanRequest {
  hours: string;
  /** region name */
  region: string;
  /** zone */
  zone: string;
}

export interface PrescanResponse {
  code?: number;
  data?: DataMessage18;
  error?: string;
}

export interface ResourceLink {
  Schema?: string;
  Action?: string;
  /** 在Thrift中沒有完全直接對應的any原生類型 */
  Params?: Record<string, string>;
}

export interface ResponseMetaData {
  RequestId: string;
  Service: string;
  Error: Error;
}

export interface Runtime {
  category?: string;
  default_template?: string;
  function_type?: string;
  key?: string;
  name?: string;
  show?: boolean;
  supported_protocols?: Array<string>;
  supported_domains?: Array<string>;
}
/* eslint-enable */
