/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as user from './user';

export type Int64 = string | number;

export interface AuthComponentSDKRequest {
  /** 一個隨機字符串，由數字、字母組成 */
  noncestr?: string;
  /** 時間戳（毫秒） */
  timestamp?: Int64;
  /** 組件頁面url */
  url?: string;
  Base?: base.Base;
}

export interface AuthComponentSDKResponse {
  signature?: string;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface GetSessionInfoRequest {
  Base?: base.Base;
}

export interface GetSessionInfoResponse {
  /** 登錄用戶信息 */
  user_info?: user.UserInfoDetail;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface GetUserInfoRequest {
  /** 選填用戶ID */
  user_id?: string;
  /** 選填用戶名 */
  user_name?: string;
  Base?: base.Base;
}

export interface GetUserInfoResponse {
  /** 用戶信息 */
  user_info?: user.UserInfoDetail;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface IsUserInGrayData {
  uid?: string;
}

export interface IsUserInGrayRequest {
  /** 灰度策略 */
  strategy?: string;
  Base?: base.Base;
}

export interface IsUserInGrayResponse {
  data?: IsUserInGrayData;
  BaseResp?: base.BaseResp;
}

export interface KickUserReq {
  extUserID: string;
  'Zti-Token': string;
  Base?: base.Base;
}

export interface KickUserResp {
  BaseResp?: base.BaseResp;
}

export interface LoginRequest {
  /** 登錄授權碼 */
  code?: string;
  /** 登錄流程重定向uri */
  state?: string;
  /** 指定 sessionID */
  session_id?: string;
  Base?: base.Base;
}

export interface LoginResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface LogoutRequest {
  Base?: base.Base;
}

export interface LogoutResponse {
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface MGetUserInfoRequest {
  /** fornax UserID列表 */
  user_ids?: Array<string>;
  /** SsoUserName列表 */
  user_names?: Array<string>;
  /** 飛書UserID列表 */
  ext_user_ids?: Array<string>;
  Base?: base.Base;
}

export interface MGetUserInfoResponse {
  /** 用戶信息列表 */
  user_infos?: Array<user.UserInfoDetail>;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}

export interface QueryUserInfoRequest {
  /** 用戶名模糊搜索 */
  name_like: string;
  /** 分頁大小，默認爲20 */
  page_size?: number;
  /** 分頁Token */
  page_token?: string;
  Base?: base.Base;
}

export interface QueryUserInfoResponse {
  /** 用戶信息列表 */
  user_infos?: Array<user.UserInfoDetail>;
  /** 分頁Token */
  page_token?: string;
  /** 是否還有下一頁 */
  has_more?: boolean;
  code?: number;
  msg?: string;
  BaseResp?: base.BaseResp;
}
/* eslint-enable */
