/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as flow_devops_evaluation_task from './flow_devops_evaluation_task';
import * as flow_devops_evaluation_evaluator from './flow_devops_evaluation_evaluator';
import * as model from './model';
import * as flow_devops_evaluation_dataset from './flow_devops_evaluation_dataset';

export type Int64 = string | number;

export enum DatasetPreHandlerType {
  None = 0,
  PromptTemplate = 1,
}

export enum InputPreHandlerType {
  None = 0,
  URL = 1,
}

export enum MerlinSeedModelType {
  Unknown = 0,
  Hdfs = 1,
}

export enum OfflineEvalTaskModelSource {
  Unknown = 0,
  MerlinSeed = 1,
  FornaxSftTask = 2,
  Opensource = 3,
}

export enum OfflineEvalTaskStatus {
  Preparing = 0,
  Launching = 1,
  Inferring = 2,
  Evaluating = 3,
  Success = 4,
  Failed = 5,
  Terminating = 6,
  Terminated = 7,
  PartialFailed = 8,
}

export interface InferResExportStatus {
  /** 結果文件的 hdfs 地址 */
  hdfsPath?: string;
  /** 當前文件的導出進度 */
  cursor?: string;
  /** 是否導出完成 */
  isExported?: boolean;
}

export interface OfflineEvalProduction {
  datasetID?: string;
  resultSetID?: string;
  caseTaskID?: string;
  /** 每次讀取時需要rpc獲得EvalCaseTask(Get和List都需要)，寫時不應該寫到數據庫裏 */
  evalCaseTask?: flow_devops_evaluation_task.Task;
  /** 最後寫入的一條數據的 ID */
  lastOutputCursor?: Int64;
}

export interface OfflineEvalTask {
  id?: string;
  name?: string;
  desc?: string;
  model?: OfflineEvalTaskModel;
  datasets?: Array<OfflineEvalTaskDataset>;
  /** 每次讀取時需要rpc獲得RuleGroup.Rules(只Get需要，List不需要) */
  evalRuleGroup?: flow_devops_evaluation_evaluator.RuleGroup;
  resource?: model.SftTaskResource;
  ckptConfig?: OfflineEvalTaskCkptConfig;
  status?: OfflineEvalTaskStatus;
  provider?: model.Provider;
  providerTaskID?: string;
  caseID?: string;
  ckptResult?: OfflineEvalTaskCkptResult;
  errCode?: string;
  errMessage?: string;
  displayErrMsg?: string;
  /** 規則組是否已刪除 */
  isRuleGroupDeleted?: boolean;
  /** Fornax空間ID */
  spaceID?: string;
  /** 創建人ID */
  createdBy?: string;
  /** 創建時間，秒 */
  createdAt?: string;
  /** 更新人ID */
  updatedBy?: string;
  /** 更新時間，秒 */
  updatedAt?: string;
}

export interface OfflineEvalTaskCkptConfig {
  /** key是name */
  items?: Record<string, OfflineEvalTaskCkptConfigItem>;
}

export interface OfflineEvalTaskCkptConfigItem {
  name?: string;
  def?: string;
  nextCkptName?: string;
  maxRetryTime?: string;
  retryIntervalMilliSecond?: string;
  /** 重試時間間隔的變化方式，支持固定間隔和隨時間漸進式變化 */
  retryIntervalChangeType?: string;
  /** 每重試x次，重試時間間隔會發生變化 */
  retryIntervalChangeTimes?: string;
  /** 每次重試時間間隔變化的步長，單位爲ms，可以爲負數 */
  retryIntervalChangeStep?: string;
  customConfigs?: Record<string, string>;
  /** 觸發下一個checkpoint的時間間隔，單位爲ms */
  triggerNextCkptIntervalMilliSecond?: string;
}

export interface OfflineEvalTaskCkptResult {
  /** 評測集上傳到hdfs的地址 */
  datasetHdfsAddress?: string;
  /** 推理結果保存的hdfs地址，可能爲文件夾 */
  inferResultHdfsAddress?: string;
  /** 推理結果導出進度 */
  resultExportStatuses?: Array<InferResExportStatus>;
  /** merlin推理任務狀態 */
  merlinDataProcessingInstanceStatusGroup?: string;
  /** merlin推理任務狀態詳情 */
  merlinDataProcessingInstanceStatus?: string;
  /** 傳入離線推理任務的數據列名 */
  inferTaskColumnName?: string;
  /** 離線評測產物 */
  evalProductions?: Array<OfflineEvalProduction>;
  /** 結果集是否導出完成 */
  resultSetExported?: boolean;
  /** merlin seed離線推理任務實際上就是在merlin任務用例外包了一層，在這裏記錄這個merlin任務用例id */
  merlinJobID?: string;
  /** merlin seed離線推理任務鏈接 */
  merlinSeedTaskUrl?: string;
  /** merlin 任務實例是否終止 */
  merlinJobTerminated?: boolean;
  /** 保存除了 plainText 以外的類型的數據的原始信息 */
  originDataColumnName?: string;
}

export interface OfflineEvalTaskDataset {
  evalDataset?: flow_devops_evaluation_dataset.DatasetInfo;
  /** 數據集預處理 */
  datasetPreHandler?: OfflineEvalTaskDatasetPreHandler;
  /** 模型輸入預處理 */
  inputPreHandler?: OfflineEvalTaskInputPreHandler;
  /** 是否已經上傳到 hdfs */
  uploaded?: boolean;
  /** 上傳進度遊標 */
  uploadCursor?: Int64;
  /** 是否已刪除 */
  isDeleted?: boolean;
}

export interface OfflineEvalTaskDatasetPreHandler {
  type?: DatasetPreHandlerType;
  promptKey?: string;
  promptVersion?: string;
  inputColumn?: string;
  promptID?: string;
  /** prompt是否已刪除 */
  isPromptDeleted?: boolean;
}

export interface OfflineEvalTaskInputPreHandler {
  type?: InputPreHandlerType;
  url?: string;
}

export interface OfflineEvalTaskModel {
  source?: OfflineEvalTaskModelSource;
  identification?: string;
  sftTaskID?: string;
  sftTaskProvider?: model.Provider;
  merlinSeedModelType?: MerlinSeedModelType;
  modelAddress?: string;
  tokenizerAddress?: string;
  networkConfigContext?: string;
  quantConfigContext?: string;
  temperature?: number;
  topP?: number;
  topK?: string;
  maxOutputToken?: string;
  maxContextToken?: string;
  batchSize?: string;
}
/* eslint-enable */
