/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as auth from './auth';

export type Int64 = string | number;

export enum GrayReleaseStrategy {
  /** 不開啓灰度 */
  None = 0,
  /** 實例灰度 */
  InstanceGrayRelease = 1,
}

/** 空間角色類型 */
export enum SpaceRoleType {
  Undefined = 0,
  /** 負責人 */
  Owner = 1,
  /** 開發者 */
  Developer = 2,
  /** 測試人員 */
  Tester = 3,
}

/** 空間類型 */
export enum SpaceType {
  Undefined = 0,
  Personal = 1,
  Team = 2,
  /** 官方空間 */
  Official = 3,
}

export interface ByteTreeNode {
  id?: string;
  name?: string;
  i18nName?: string;
  path?: string;
  i18nPath?: string;
  levelID?: Int64;
  isLeaf?: boolean;
  type?: string;
}

export interface CozeBotFeatureConfig {
  enabled: boolean;
  botIDAllowList?: Array<Int64>;
}

/** 空間配置 */
export interface FeatureConfig {
  /** 開啓特性的空間ID */
  EnabledSpaceIDList?: Array<Int64>;
  /** 是否全量開啓 */
  EnableAll?: boolean;
}

export interface ReleaseApprovalConfig {
  /** 是否開啓審覈 */
  enable?: boolean;
  /** 灰度策略 */
  gray_release_strategy?: GrayReleaseStrategy;
}

/** 空間 */
export interface Space {
  /** 空間ID */
  id?: Int64;
  /** 空間名稱 */
  name?: string;
  /** 空間描述 */
  description?: string;
  /** 空間類型 */
  space_type?: SpaceType;
  /** 空間創建人 */
  creator?: string;
  /** 創建時間 */
  create_tsms?: Int64;
  /** 更新時間 */
  update_tsms?: Int64;
  /** 發佈審覈配置 */
  release_approval_config?: ReleaseApprovalConfig;
  /** 空間來源 */
  space_origin?: string;
  /** 服務樹節點ID */
  tree_node_id?: string;
  /** 具體配置內容 */
  trace_config?: TraceConfig;
}

/** 空間成員 */
export interface SpaceMember {
  /** 空間ID */
  space_id?: Int64;
  /** 成員 */
  member?: auth.AuthPrincipal;
  /** 空間角色類型 */
  space_role_type?: SpaceRoleType;
}

/** 觀測配置 */
export interface TraceConfig {
  /** 是否加密trace 默認false */
  trace_encrypt?: boolean;
  /** ttl天數 默認7，目前合法值有7/30/90 */
  ttl?: number;
}
/* eslint-enable */
