/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum ActionKey {
  /** 複製 */
  Copy = 1,
  /** 刪除 */
  Delete = 2,
  /** 啓用/禁用 */
  EnableSwitch = 3,
  /** 編輯 */
  Edit = 4,
  /** 切換成funcflow */
  SwitchToFuncflow = 8,
  /** 切換成chatflow */
  SwitchToChatflow = 9,
  /** 跨空間複製 */
  CrossSpaceCopy = 10,
}

export enum CopyStatus {
  Successful = 1,
  Processing = 2,
  Failed = 3,
  /** 如果是KeepOrigin，表示該資源不需要做變更，資源方不需要設置Target相關信息；引用方直接忽略即可 */
  KeepOrigin = 4,
  /** 表示回滾到草稿時，資源從有->無的變更 */
  Deleted = 5,
}

export enum ProjectResourceActionKey {
  /** 重命名 */
  Rename = 1,
  /** 創建副本/複製到當前項目 */
  Copy = 2,
  /** 複製到資源庫 */
  CopyToLibrary = 3,
  /** 移動到資源庫 */
  MoveToLibrary = 4,
  /** 刪除 */
  Delete = 5,
  /** 啓用 */
  Enable = 6,
  /** 禁用 */
  Disable = 7,
  /** 切換成funcflow */
  SwitchToFuncflow = 8,
  /** 切換成chatflow */
  SwitchToChatflow = 9,
  /** 修改描述 */
  UpdateDesc = 10,
}

export enum ProjectResourceGroupType {
  Workflow = 1,
  Plugin = 2,
  Data = 3,
}

export enum PublishStatus {
  /** 未發佈 */
  UnPublished = 1,
  /** 已發佈 */
  Published = 2,
}

export enum ResourceCopyScene {
  /** 複製項目內的資源，淺拷貝 */
  CopyProjectResource = 1,
  /** 複製項目資源到Library，複製後要發佈 */
  CopyResourceToLibrary = 2,
  /** 移動項目資源到Library，複製後要發佈，後置要刪除項目資源 */
  MoveResourceToLibrary = 3,
  /** 複製Library資源到項目 */
  CopyResourceFromLibrary = 4,
  /** 複製項目，連帶資源要複製。複製當前草稿。 */
  CopyProject = 5,
  /** 項目發佈到渠道，連帶資源需要發佈（含商店）。以當前草稿發佈。 */
  PublishProject = 6,
  /** 複製項目模板。 */
  CopyProjectTemplate = 7,
  /** 項目發佈到模板，以項目的指定版本發佈成臨時模板。 */
  PublishProjectTemplate = 8,
  /** 模板審覈通過，上架，根據臨時模板複製正式模板。 */
  LaunchTemplate = 9,
  /** 草稿版本存檔 */
  ArchiveProject = 10,
  /** 線上版本加載到草稿，草稿版本加載到草稿 */
  RollbackProject = 11,
  /** 單個資源跨空間複製 */
  CrossSpaceCopy = 12,
  /** 項目跨空間複製 */
  CrossSpaceCopyProject = 13,
}

export enum ResType {
  Plugin = 1,
  Workflow = 2,
  Imageflow = 3,
  Knowledge = 4,
  UI = 5,
  Prompt = 6,
  Database = 7,
  Variable = 8,
  Voice = 9,
}

export enum SyncOperation {
  Upsert = 1,
  Delete = 2,
}

/** struct ResourceCopyExtraInfo{
    // 表示操作資源後，資源要改成該名稱
    1 : optional string ResourceName (go.tag = "json:\"resource_name\"", agw.key = "resource_name")
    // 表示資源發佈後的版本號
    2 : optional string VersionNum  (go.tag = "json:\"version_num\"", agw.key = "version_num")
    // 該版本的版本描述
    3 : optional string VersionDesc  (go.tag = "json:\"version_desc\"", agw.key = "version_desc")
    // 每個資源不同的信息，對插件，是個人信息收集聲明。schema和各個資源方約定
    4 : optional string ResourceExtendInfo  (go.tag = "json:\"resource_extend_info\"", agw.key = "resource_extend_info")
} */
export enum TaskStatus {
  Successed = 1,
  Processing = 2,
  Failed = 3,
  Canceled = 4,
}

export interface ResourceCopyCheckFailedReason {
  ResourceLocator?: ResourceLocator;
  ResName?: string;
  Reason?: string;
}

export interface ResourceCopyEnv {
  Scene?: ResourceCopyScene;
  /** 原項目ID。如果被複制的資源在項目中，則有值。場景：CopyProjectResource、CopyResourceToLibrary、MoveResourceToLibrary、CopyProject */
  OriginProjectID?: Int64;
  /** 目標項目ID。如果複製後的資源要賦值project_id，則有值。場景：CopyProjectResource、CopyResourceFromLibrary、CopyProject */
  TargetProjectID?: Int64;
  /** 被用戶選擇複製/移動的資源ID。如果操作的目標是資源，則有值。場景：CopyProjectResource、CopyResourceToLibrary、MoveResourceToLibrary、CopyResourceFromLibrary */
  ResourceLocator?: ResourceLocator;
  /** 當次任務的唯一約束，控制冪等。有則傳，發起任務時不用傳 */
  TaskUniqKey?: string;
  /** 項目發佈時，項目版本。場景：PublishProject、PublishProjectTemplate */
  TargetProjectVersion?: Int64;
  OriginProjectSpaceID?: Int64;
  TargetProjectSpaceID?: Int64;
  /** 操作者用戶id */
  CurrentUserID?: Int64;
  /** 發佈模板時，原項目版本。or 複製模板時，模板的項目版本。 */
  OriginProjectVersion?: Int64;
  /** 0/default-app，默認是app也就是之前的project; 1-bot或者叫agent */
  ProjectType?: number;
}

/** 每個資源的複製結果，包含前後映射信息 */
export interface ResourceCopyResult {
  OriginResourceLocator?: ResourceLocator;
  TargetResourceLocator?: ResourceLocator;
  CopyStatus?: CopyStatus;
  /** 發佈版本號或版本名，0.0.1 */
  TargetPublishVersionNum?: string;
  /** 其他的信息，比如plugin的tool映射信息。schema和各資源方約定 */
  TargetResInfo?: string;
  /** 複製不成功的原因 */
  FailedReason?: string;
}

/** 用於定位一個資源數據的結構：某資源的某版本 */
export interface ResourceLocator {
  ResID?: Int64;
  ResType?: ResType;
  /** 廢棄，不要使用 */
  PublishVersion?: Int64;
  /** 資源的當前版本，爲nil或空字符串都看作是最新版本。項目發佈版本或Library發佈版本。 */
  PublishVersionStr?: string;
}
/* eslint-enable */
